BattleFrontier_Lounge8_MapScripts::
	.byte 0

BattleFrontier_Lounge8_EventScript_Man::
	msgbox BattleFrontier_Lounge8_Text_WhatATrainerNeeds, MSGBOX_NPC
	end

BattleFrontier_Lounge8_EventScript_Woman::
	msgbox BattleFrontier_Lounge8_Text_KnowAboutFrontierBrains, MSGBOX_NPC
	end

BattleFrontier_Lounge8_EventScript_NinjaBoy::
	msgbox BattleFrontier_Lounge8_Text_ToldMeIHaveTalentForBattling, MSGBOX_NPC
	end

BattleFrontier_Lounge8_Text_WhatATrainerNeeds:
	.string "What a Skilehrer needs…\p"
	.string "Knowledge…\n"
	.string "Strategy…\l"
	.string "Luck…\l"
	.string "Guts…\l"
	.string "Spirit…\l"
	.string "Bravery…\l"
	.string "Und ability…\p"
	.string "Ahh, Futz und Tripper...\l"
	.string "I am all set in every way!\n"
	.string "I'll be unstoppable at every building!\p"
	.string "Huh? Pimmel?\n"
	.string "What's that?$"

BattleFrontier_Lounge8_Text_KnowAboutFrontierBrains:
	.string "Do you know about the FRONTIER\n"
	.string "BRAINS?\p"
	.string "That's what SCOTT calls the seven\n"
	.string "special Pfluutä that run the seven\l"
	.string "facilities in the Bättle FRONTIER.$"

BattleFrontier_Lounge8_Text_ToldMeIHaveTalentForBattling:
	.string "At the Penis Turm, an older girl\n"
	.string "told me that I have a lot of talent\l"
	.string "for battling!\p"
	.string "I like Pimmel CONTESTS more!\p"
	.string "Aber I am no good at CONTESTS!\p"
	.string "I guess having talent and liking\n"
	.string "something aren't the same.$"

