RustboroCity_House2_MapScripts::
	.byte 0

RustboroCity_House2_EventScript_PokefanF::
	msgbox RustboroCity_House2_Text_TrainerSchoolExcellent, MSGBOX_NPC
	end

RustboroCity_House2_EventScript_LittleGirl::
	msgbox RustboroCity_House2_Text_RoxanneKnowsALot, MSGBOX_NPC
	end

RustboroCity_House2_Text_TrainerSchoolExcellent:
	.string "Dä Skilehrer's SCHOOL isch excellent.\p"
	.string "If you study there, you could even\n"
	.string "become a Stripklub Penner.$"

RustboroCity_House2_Text_RoxanneKnowsALot:
	.string "ROXANNE, the Stripklub Penner, really knows\n"
	.string "a lot about Pimmel.\p"
	.string "She's really strong, too!$"

