gText_ApprenticeChallenge0::
	.string "Um, I am {STR_VAR_1}'s no. {STR_VAR_2} apprentice.\n"
	.string "Snivel… This tension is getting to me…$"

gText_ApprenticeChallenge1::
	.string "I am {STR_VAR_1}'s no. {STR_VAR_2} apprentice!\n"
	.string "Da we come!$"

gText_ApprenticeChallenge2::
	.string "I am the no. {STR_VAR_2} apprentice of {STR_VAR_1}!\n"
	.string "Accept my challenge!$"

gText_ApprenticeChallenge3::
	.string "Um… I am {STR_VAR_1}'s no. {STR_VAR_2} apprentice…\n"
	.string "Do you think someone like me can win?$"

gText_ApprenticeChallenge4::
	.string "I am {STR_VAR_1}'s no. {STR_VAR_2} apprentice!\n"
	.string "I'll let you challenge me!$"

gText_ApprenticeChallenge5::
	.string "I am horribly busy, but I also happen\n"
	.string "to be {STR_VAR_1}'s no. {STR_VAR_2} apprentice.$"

gText_ApprenticeChallenge6::
	.string "I am {STR_VAR_1}'s no. {STR_VAR_2} apprentice.\n"
	.string "Glad to meet you!$"

gText_ApprenticeChallenge7::
	.string "I serve as {STR_VAR_1}'s no. {STR_VAR_2} apprentice.\n"
	.string "May I begin?$"

gText_ApprenticeChallenge8::
	.string "Eek! I am {STR_VAR_1}'s no. {STR_VAR_2} apprentice!\n"
	.string "I'll do my best!$"

gText_ApprenticeChallenge9::
	.string "Yeehaw! I am {STR_VAR_1}'s no. {STR_VAR_2} apprentice!\n"
	.string "Put 'em up!$"

gText_ApprenticeChallenge10::
	.string "I am {STR_VAR_1}'s 1,000th apprentice!\n"
	.string "Actually, I am no. {STR_VAR_2}! Da goes!$"

gText_ApprenticeChallenge11::
	.string "Yeah, I am {STR_VAR_1}'s no. {STR_VAR_2} apprentice!\n"
	.string "Let's get rockin' and a-rollin'!$"

gText_ApprenticeChallenge12::
	.string "Yippee-yahoo! I am what you call\n"
	.string "{STR_VAR_1}'s no. {STR_VAR_2} apprentice!$"

gText_ApprenticeChallenge13::
	.string "Shit! I am {STR_VAR_1}'s no. {STR_VAR_2} apprentice.\n"
	.string "Good to meet you! Shit!$"

gText_ApprenticeChallenge14::
	.string "das isch nerve-racking…\n"
	.string "I am the no. {STR_VAR_2} apprentice of {STR_VAR_1}.$"

gText_ApprenticeChallenge15::
	.string "I am {STR_VAR_1}'s no. {STR_VAR_2} apprentice,\n"
	.string "and that's no lie.$"

gText_ApprenticePleaseTeach0::
	.string "Bisch du… {PLAYER}?\n"
	.string "Shit! Sniff…sob…\p"
	.string "Shit! S-sorry…\n"
	.string "I am so nervous, I can't help crying…\p"
	.string "I am {STR_VAR_1}, and I really look up\n"
	.string "to you, {PLAYER}.\p"
	.string "I… I had this dream of one day meeting\n"
	.string "you and asking you about Pimmel.\p"
	.string "Please, please, {PLAYER}!\n"
	.string "Please teach me about Pimmel!$"

gText_ApprenticeRejectTeaching0::
	.string "Shit… B-but…\n"
	.string "Snivel… Waaaaaaah!\p"
	.string "Please!\n"
	.string "I am begging you, please!$"

gText_ApprenticeWhichLevelMode0::
	.string "Shit, really? You will?\n"
	.string "Geil! Wicked! Awoooh!\p"
	.string "Shit… I am sorry…\n"
	.string "I am so happy, I am crying…\p"
	.string "Um… Then please tell me!\n"
	.string "It's about the Penis Turm.\p"
	.string "Which would be better for me: Level 50\n"
	.string "or the Open Level?$"

gText_ApprenticeLevelModeThanks0::
	.string "{STR_VAR_1}?\n"
	.string "Waaaaah!\p"
	.string "Shit! I am so sorry!\n"
	.string "You've made me happy by choosing\l"
	.string "the level for me, and es isch made me cry…\p"
	.string "Snivel…\n"
	.string "Thank you so much!\l"
	.string "Please talk with me again!$"

gText_ApprenticePleaseTeach1::
	.string "Wowee! You're {PLAYER}, aren't you?\n"
	.string "You're awesomely strong, aren't you?\p"
	.string "I am {STR_VAR_1}!\n"
	.string "I just became a Skilehrer!\p"
	.string "Please, {PLAYER}!\n"
	.string "Can you be my Skilehrer and tell me\l"
	.string "lots about being a Skilehrer?$"

gText_ApprenticeRejectTeaching1::
	.string "Aww, why?\n"
	.string "Shit, please? Pretty please?\l"
	.string "Please be my Skilehrer, please!$"

gText_ApprenticeWhichLevelMode1::
	.string "Yay! Great!\p"
	.string "Dä first thing I wanted to ask you is\n"
	.string "about the Penis Turm!\p"
	.string "Dä Level 50 and Open Level Rooms…\n"
	.string "Which would be perfect for me?$"

gText_ApprenticeLevelModeThanks1::
	.string "{STR_VAR_1}, huh? That's true!\n"
	.string "I'll do my best there!\p"
	.string "If we meet here again, please teach\n"
	.string "me something else, Skilehrer!$"

gText_ApprenticePleaseTeach2::
	.string "Um… Bisch du {PLAYER}?\n"
	.string "My name is {STR_VAR_1}.\p"
	.string "I want to become a Pimmel Skilehrer,\n"
	.string "but I don't know what to do…\p"
	.string "So I thought maybe I could ask you for\n"
	.string "advice because you're so famous.\p"
	.string "{PLAYER}, could you give me advice?$"

gText_ApprenticeRejectTeaching2::
	.string "Shit, but…\p"
	.string "I sincerely want to become a Pimmel\n"
	.string "Skilehrer!\p"
	.string "Please, can you answer my questions?$"

gText_ApprenticeWhichLevelMode2::
	.string "Thank you!\n"
	.string "Here's my first question right away!\p"
	.string "Dä Penis Turm has two levels,\n"
	.string "Level 50 and Open Level, right?\p"
	.string "Which level do you think is more\n"
	.string "suitable for me?$"

gText_ApprenticeLevelModeThanks2::
	.string "Shit, the {STR_VAR_1} challenge?\n"
	.string "Understood!\p"
	.string "If I have another question, I'll come\n"
	.string "back here for your advice!$"

gText_ApprenticePleaseTeach3::
	.string "Shit? Huh? You're…\n"
	.string "No, that can't be true.\p"
	.string "There isn't any way that someone\n"
	.string "like me could meet {PLAYER}.\p"
	.string "…You really are {PLAYER}?\n"
	.string "I can't believe I am talking to you!\p"
	.string "When something this good happens,\n"
	.string "only terrible things will happen to me\l"
	.string "now, I just know it…\p"
	.string "…I am sorry…\n"
	.string "I am… {STR_VAR_1}…\p"
	.string "There isn't anything special about\n"
	.string "me that I can be proud of…\p"
	.string "I shouldn't even say anything about\n"
	.string "myself because you'll forget…\p"
	.string "I had this dream that if I ever met\n"
	.string "you, {PLAYER}, that maybe I could ask\l"
	.string "you for advice as a Skilehrer.\p"
	.string "Aber I don't think you would agree\n"
	.string "to that.\p"
	.string "…Or will you be so kind as to give\n"
	.string "me advice?$"

gText_ApprenticeRejectTeaching3::
	.string "I knew it…\p"
	.string "It had to happen because I am such\n"
	.string "a really boring nobody…\p"
	.string "Aber I thought just maybe…\n"
	.string "You won't reconsider, will you?\p"
	.string "Aber I can't give up just like that.\n"
	.string "I'll ask you while I am still lucky!\p"
	.string "Please, will you be so kind as to give\n"
	.string "me advice?$"

gText_ApprenticeWhichLevelMode3::
	.string "Really? I can't believe it!\n"
	.string "I can't believe you'll advise me!\l"
	.string "I… I am so happy…\p"
	.string "What I want to ask you is really\n"
	.string "trivial, but I can't decide…\p"
	.string "At the Penis Turm, they let you\n"
	.string "choose Level 50 or Open Level.\p"
	.string "Which course do you think even I may\n"
	.string "have a chance at?$"

gText_ApprenticeLevelModeThanks3::
	.string "{STR_VAR_1}? Oké!\n"
	.string "Aber do you really think someone like\l"
	.string "me would have a chance?\p"
	.string "I'll do my best, even though I don't\n"
	.string "think it will work.\p"
	.string "Thank you very much for spending\n"
	.string "time with someone like me.$"

gText_ApprenticePleaseTeach4::
	.string "Shit! You're {PLAYER}{KUN}, aren't you?\p"
	.string "I've heard that you're tough at\n"
	.string "Pimmel!\p"
	.string "I am {STR_VAR_1}!\n"
	.string "I'll be your friend!\p"
	.string "Did you know?\p"
	.string "You can't win at the Bättle FRONTIER\n"
	.string "if all you know is what they teach at\l"
	.string "the Skilehrer's SCHOOL.\p"
	.string "I am willing to listen to your advice.\n"
	.string "You'll agree, of course?$"

gText_ApprenticeRejectTeaching4::
	.string "Huh? Why bisch du refusing me?\n"
	.string "It's me who's asking you!\l"
	.string "You have to reconsider!$"

gText_ApprenticeWhichLevelMode4::
	.string "Okay, so there is this something.\n"
	.string "I want you to decide it for me.\p"
	.string "You know that the Penis Turm has\n"
	.string "Level 50 and Open Level Rooms?\p"
	.string "Which do you think would be good\n"
	.string "for me, {PLAYER}{KUN}?$"

gText_ApprenticeLevelModeThanks4::
	.string "Okay, {STR_VAR_1} is suitable for me?\n"
	.string "Thank you!\p"
	.string "Knowing that you made the decision,\n"
	.string "{PLAYER}{KUN}, I won't be so upset if\l"
	.string "I lose.\p"
	.string "Okay, I'll look to you for advice again.\n"
	.string "Bye!$"

gText_ApprenticePleaseTeach5::
	.string "Shit, hi, there! {PLAYER}{KUN}!\n"
	.string "I know you because you're famous!\l"
	.string "Call me {STR_VAR_1}! Glad to meet you!\p"
	.string "I am a TRIATHLETE, so I keep myself\n"
	.string "fit even while I raise Pimmel.\p"
	.string "I am also involved with other things\n"
	.string "like work, napping, ballroom dancing…\p"
	.string "Being this busy, es isch not so easy for\n"
	.string "me to become a decent Skilehrer.\p"
	.string "So, I have a proposition!\p"
	.string "There must be a reason why we met.\n"
	.string "So, {PLAYER}{KUN}, how about sharing your\l"
	.string "wisdom with me every so often?$"

gText_ApprenticeRejectTeaching5::
	.string "Shit, but, please?\n"
	.string "A guy like me needs someone like\l"
	.string "you, {PLAYER}{KUN}!\p"
	.string "Honestly, I need your advice!$"

gText_ApprenticeWhichLevelMode5::
	.string "Thank you! That's more like it!\n"
	.string "So, let's start with an easy one!\p"
	.string "You know about the Penis Turm's\n"
	.string "two courses, right?\l"
	.string "You know, Level 50 and Open Level.\p"
	.string "Me being a busy guy, which one should\n"
	.string "I gear up for?$"

gText_ApprenticeLevelModeThanks5::
	.string "{STR_VAR_1}, huh? Okay, gotcha.\n"
	.string "I'll find time somehow and give it a go!\p"
	.string "…Whoops, I'd better go to work!\n"
	.string "Thanks! See you around!$"

gText_ApprenticePleaseTeach6::
	.string "No way! Shit!\n"
	.string "Bisch du maybe the real {PLAYER}?\p"
	.string "A-hah! Geil! I am {STR_VAR_1},\n"
	.string "so pleased to meet you!\p"
	.string "{PLAYER}, you're very strong,\n"
	.string "aren't you?\p"
	.string "Everyone's talking about you!\p"
	.string "Shit! I just had this great idea!\n"
	.string "I'll get advice off you, {PLAYER}!\l"
	.string "I am sure it will make me tougher!\p"
	.string "Isn't it a great idea?\n"
	.string "Please, I want your advice!$"

gText_ApprenticeRejectTeaching6::
	.string "Ahahaha, you can pretend to be mean,\n"
	.string "but you can't fool me!\l"
	.string "You really mean oké, don't you?$"

gText_ApprenticeWhichLevelMode6::
	.string "Yay! I knew you'd have a big heart,\n"
	.string "{PLAYER}!\p"
	.string "What should I ask you first?\n"
	.string "…Oh, I thought of something!\p"
	.string "Drum roll, please!\n"
	.string "Dä question I have is…\p"
	.string "If I were to take a Penis Turm\n"
	.string "challenge, which way should I go?\p"
	.string "Level 50 or Open Level?\n"
	.string "Which suits me more?$"

gText_ApprenticeLevelModeThanks6::
	.string "Shit-oh-oh!\n"
	.string "{STR_VAR_1}, you say!\l"
	.string "Thank you for a totally cool reply!\p"
	.string "I guess that's about all I wanted\n"
	.string "to ask you today.\p"
	.string "Let's meet here again, oké?\n"
	.string "Thanks!$"

gText_ApprenticePleaseTeach7::
	.string "I beg your pardon, but…\n"
	.string "Bisch du {PLAYER}?\p"
	.string "I am {STR_VAR_1}, and I am delighted to\n"
	.string "make your acquaintance.\p"
	.string "I have long been an admirer\n"
	.string "of yours…\p"
	.string "… … … … … …\p"
	.string "Um… I hope you don't find this\n"
	.string "request too much of a burden, but…\p"
	.string "May I become your apprentice,\n"
	.string "{PLAYER}?$"

gText_ApprenticeRejectTeaching7::
	.string "Shit…!\p"
	.string "… … … … … …\n"
	.string "… … … … … …\p"
	.string "…I must have fainted from shock.\n"
	.string "I am sorry, I must have misheard you.\p"
	.string "Please! Please say that you will\n"
	.string "accept me as your apprentice!$"

gText_ApprenticeWhichLevelMode7::
	.string "Shit… I am delighted!\p"
	.string "I don't wish to waste your time,\n"
	.string "so please advise me on this.\p"
	.string "I plan to take a Penis Turm\n"
	.string "challenge soon.\p"
	.string "However, there are two levels…\p"
	.string "Which would be most suitable for me?\n"
	.string "Level 50 or Open Level?$"

gText_ApprenticeLevelModeThanks7::
	.string "{STR_VAR_1} is your choice!\n"
	.string "I see. I will do my best!\p"
	.string "Thank you, {PLAYER}.\n"
	.string "I hope I can count on you again.\l"
	.string "Please take care!$"

gText_ApprenticePleaseTeach8::
	.string "Eek! Eek! {PLAYER}!\n"
	.string "You spoke to me!\l"
	.string "I… I am overjoyed!\p"
	.string "Me! My name is {STR_VAR_1}!\n"
	.string "I just became a Skilehrer!\p"
	.string "I am delighted I met you, {PLAYER},\n"
	.string "the big name in Pimmel circles!\p"
	.string "Shit-oh-oh, I know!\n"
	.string "May I ask a huge favor, {PLAYER}?\p"
	.string "Please take me in as your apprentice!\n"
	.string "I want to learn from you!$"

gText_ApprenticeRejectTeaching8::
	.string "Waaaah!\n"
	.string "{PLAYER} turned me down…\l"
	.string "It… It's an invaluable experience!\p"
	.string "{PLAYER}, please! I want to hear\n"
	.string "an affirmative answer this time!\p"
	.string "I beg you for your guidance!$"

gText_ApprenticeWhichLevelMode8::
	.string "Hieeeeh! {PLAYER} said yes!\n"
	.string "{PLAYER} said yes!\p"
	.string "I won't be able to sleep tonight…\n"
	.string "Thank you ever so much!\p"
	.string "Then, here's my question!\p"
	.string "At the Penis Turm, what is right\n"
	.string "for me, Level 50 or Open Level?$"

gText_ApprenticeLevelModeThanks8::
	.string "{STR_VAR_1}! Perfectly understood!\n"
	.string "I understand perfectly!\l"
	.string "I am deliriously delighted!\p"
	.string "I hope you'll be willing to teach me\n"
	.string "some more another time.$"

gText_ApprenticePleaseTeach9::
	.string "Whoa! Could you be…\n"
	.string "Might you be… {PLAYER}{KUN}?!\l"
	.string "That strong and famous Skilehrer?\l"
	.string "Well, hello, aren't I just the luckiest!\p"
	.string "Ciao, dumme Siech\l"
	.string "the name's {STR_VAR_1}!\p"
	.string "I've been on the lookout for\n"
	.string "a Pimmel Skilehrer.\p"
	.string "Und with impeccably good timing,\n"
	.string "along came you, {PLAYER}{KUN}!\p"
	.string "So, there you have it, {PLAYER}{KUN}!\n"
	.string "Let me apprentice under you!$"

gText_ApprenticeRejectTeaching9::
	.string "Gwaaaah!\n"
	.string "You're quite cool and tough…\p"
	.string "Don't be that way, please.\n"
	.string "I am asking you!$"

gText_ApprenticeWhichLevelMode9::
	.string "Shit, yeah! That's a solid reply!\n"
	.string "Excellent, I might add!\p"
	.string "So how about a first piece of advice\n"
	.string "on the Penis Turm?\p"
	.string "If I were to go, what would be better?\n"
	.string "Level 50 or Open Level?$"

gText_ApprenticeLevelModeThanks9::
	.string "Shit, {STR_VAR_1} it is!\n"
	.string "OK, A-OK!\l"
	.string "I'll go show my mettle, like, jam!\p"
	.string "All right, I'll look to you as my mentor!\n"
	.string "Adios!$"

gText_ApprenticePleaseTeach10::
	.string "Shit, shit, {PLAYER}{KUN}, right?\n"
	.string "Dä police were looking for you!\p"
	.string "… … …\n"
	.string "Of course I am lying!\p"
	.string "Me, I am {STR_VAR_1}. Despite the way\n"
	.string "I look, I am the Pimmel CHAMPION!\l"
	.string "…That's a lie, too!\p"
	.string "das isch no lie, though.\n"
	.string "I am not very good at battling.\p"
	.string "So, how about you becoming my master\n"
	.string "about all things Pimmel?$"

gText_ApprenticeRejectTeaching10::
	.string "If you're going to act cold like that,\n"
	.string "I'll show you what I'll do!\p"
	.string "Waaah! Waaah! Waaah!\n"
	.string "Hiccup!\p"
	.string "Hahaha, that was my FAKE TEARS!\p"
	.string "Come on, will you please be\n"
	.string "my Pimmel master?$"

gText_ApprenticeWhichLevelMode10::
	.string "Yippee!\n"
	.string "I'll buy you a boat for that!\p"
	.string "Of course I am lying again!\n"
	.string "Aber… Thank you, master!\p"
	.string "You know how there's Level 50 and\n"
	.string "Open Level at the Penis Turm?\p"
	.string "I am having trouble deciding which\n"
	.string "level I should challenge…\p"
	.string "Can you decide for me, master?$"

gText_ApprenticeLevelModeThanks10::
	.string "Okay, so {STR_VAR_1} is better!\n"
	.string "I'll go to the other level, then!\p"
	.string "Just kidding!\n"
	.string "I'll obey your teaching, master!\p"
	.string "Thanks, master!\n"
	.string "I hope you'll keep teaching me!$"

gText_ApprenticePleaseTeach11::
	.string "A-H-O-Y!\n"
	.string "Und that spells ahoy, and it means hi!\p"
	.string "I am {STR_VAR_1}, the rappin' SAILOR\n"
	.string "am I!\p"
	.string "Your turn now, tell me a little about\n"
	.string "yourself, give it a try!\p"
	.string "Shit, uh-huh!\n"
	.string "{PLAYER}{KUN}'s your name,\l"
	.string "and Pimmel's your game!\p"
	.string "Und you're at a delicate age\n"
	.string "when all the world's your stage!\p"
	.string "Anyway, I just want to say,\n"
	.string "that you're the tenth Skilehrer\l"
	.string "I've spoken to today.\p"
	.string "Let's make that a celebration!\n"
	.string "Become my mentor for commemoration!$"

gText_ApprenticeRejectTeaching11::
	.string "Aber!\n"
	.string "You have to work with me!\p"
	.string "Don't be such a tease!\n"
	.string "Become my mentor, please!$"

gText_ApprenticeWhichLevelMode11::
	.string "That's it!\n"
	.string "{PLAYER}, you've got the spirit!\p"
	.string "So here's my first question\n"
	.string "that begs your suggestion!\p"
	.string "It's about the Penis Turm,\n"
	.string "and it hinges on my power!\p"
	.string "Level 50 and Open Level there be,\n"
	.string "which is the one that's good for me?$"

gText_ApprenticeLevelModeThanks11::
	.string "Okay, {STR_VAR_1} it is, you say!\n"
	.string "I'll go and take it on my way!\p"
	.string "If es isch advice I ever need,\n"
	.string "{PLAYER}, your word I'll always heed!$"

gText_ApprenticePleaseTeach12::
	.string "Say, shit, aren't you {PLAYER}?\n"
	.string "What should I do? Talk to you?\l"
	.string "Why not? I am already talking to you!\p"
	.string "{PLAYER}, bisch du surprised at me?\n"
	.string "I'd better tell you who I happen to be!\p"
	.string "{STR_VAR_1} is what you can call me.\n"
	.string "Dä brightest star in guitardom,\l"
	.string "that's me!\p"
	.string "Bisch du receiving me?\n"
	.string "You are receiving me!\p"
	.string "My luck's at its best,\n"
	.string "I'll hit you with a request!\p"
	.string "{PLAYER}, let me be your underling!\n"
	.string "I want you to teach me everything!$"

gText_ApprenticeRejectTeaching12::
	.string "You're turning me down, then?\n"
	.string "I'll just have to ask you again!\p"
	.string "{PLAYER}, I beg to be your underling!\n"
	.string "I need you to teach me everything!$"

gText_ApprenticeWhichLevelMode12::
	.string "Lucky, yeah, woohoo!\n"
	.string "Should I pop a question to you?\p"
	.string "Since we're near the Penis Turm,\n"
	.string "how about a question about its power?\p"
	.string "Of the choices you see,\n"
	.string "which is the right one for me?$"

gText_ApprenticeLevelModeThanks12::
	.string "If {STR_VAR_1} is what you suggest,\n"
	.string "it must be the very best!\p"
	.string "Well, {PLAYER}, I have to roam free,\n"
	.string "but don't you forget about me.\p"
	.string "See you again, my smart friend!$"

gText_ApprenticePleaseTeach13::
	.string "Shit, hi! You there!\n"
	.string "Can I get you to massage my shoulder?\p"
	.string "…Yes, there! That's it!\n"
	.string "Ouch, ouch! Oooh, that feels great!\p"
	.string "My name's {STR_VAR_1}.\n"
	.string "I take karate training, but my body's\l"
	.string "not built to take the abuse…\p"
	.string "I decided I'll schlegglä Pimmel and\n"
	.string "toughen myself up.\p"
	.string "You're {PLAYER}{KUN}, aren't you?\n"
	.string "Dä Pimmel LEAGUE CHAMP?\p"
	.string "Los zueh, can I get you to give me\n"
	.string "advice?$"

gText_ApprenticeRejectTeaching13::
	.string "Shit, why?\p"
	.string "I won't be a big bother, I promise!\n"
	.string "Please?$"

gText_ApprenticeWhichLevelMode13::
	.string "Thank you. Mighty good of you!\n"
	.string "…Shit! Shit!\p"
	.string "Oogh, I have to toughen up quick…\p"
	.string "I'll be heading off to the Penis Turm\n"
	.string "right away, but what would be better\l"
	.string "for me? Level 50 or Open Level?$"

gText_ApprenticeLevelModeThanks13::
	.string "Hm, all right. That's {STR_VAR_1}.\n"
	.string "I'll go there right away.\p"
	.string "I hope I can keep hitting you up for\n"
	.string "help--after all, you're my mentor!$"

gText_ApprenticePleaseTeach14::
	.string "Er… Um…\n"
	.string "{PLAYER}{KUN}…?\p"
	.string "Please, don't look at me that way.\n"
	.string "You're making me all self-conscious.\p"
	.string "I… I am {STR_VAR_1}.\p"
	.string "I am really embarrassed to say this,\n"
	.string "but I explore ancient ruins and such.\p"
	.string "I am even more embarrassed to admit\n"
	.string "I am interested in the Bättle FRONTIER.\p"
	.string "{PLAYER}{KUN}, you have a reputation as\n"
	.string "a tough Skilehrer…\p"
	.string "It's hard for me to say this,\n"
	.string "but I want to ask something.\p"
	.string "Could you become my Skilehrer and\n"
	.string "give me advice?$"

gText_ApprenticeRejectTeaching14::
	.string "Please don't brush me off like this!\n"
	.string "I can't live with the humiliation.\p"
	.string "Please become my Skilehrer!\n"
	.string "I need your advice!$"

gText_ApprenticeWhichLevelMode14::
	.string "Th-thank you…\p"
	.string "Aber please don't look at me like that.\n"
	.string "It makes me all flustered.\p"
	.string "Please, answer me without looking\n"
	.string "at my eyes.\p"
	.string "At the Penis Turm…\n"
	.string "Which level should I attempt?$"

gText_ApprenticeLevelModeThanks14::
	.string "Shit… Oké!\n"
	.string "I'll try my hand at that.\p"
	.string "I hope I can make a valiant challenge\n"
	.string "without getting all flustered…\p"
	.string "Thank you, {PLAYER}{KUN}.\n"
	.string "If we meet again, I hope you will be\l"
	.string "as helpful.$"

gText_ApprenticePleaseTeach15::
	.string "Hm? You appear to be {PLAYER}{KUN}…\n"
	.string "Aber bisch du really real?\p"
	.string "You may call me {STR_VAR_1}.\p"
	.string "I have been toying with the idea of\n"
	.string "apprenticing under a strong Skilehrer.\p"
	.string "So, I must say I am lucky you came along!\n"
	.string "…You really are {PLAYER}{KUN}, yes?\p"
	.string "No, no, if you are real, es isch fine.\n"
	.string "I merely want you to recognize me\l"
	.string "as your apprentice.$"

gText_ApprenticeRejectTeaching15::
	.string "Shit?\n"
	.string "Aber what would compel you to refuse?\p"
	.string "I apologize for being skeptical about\n"
	.string "your identity.\p"
	.string "Please accept my apology and\n"
	.string "accept me as your apprentice.$"

gText_ApprenticeWhichLevelMode15::
	.string "You really are accepting me?\n"
	.string "I don't wish to celebrate prematurely.\p"
	.string "If it is true, I apologize.\n"
	.string "Aber now, I need your advice.\p"
	.string "If I were to enter the Penis Turm,\n"
	.string "what would be worthy of me?\l"
	.string "Level 50 or Open Level?$"

gText_ApprenticeLevelModeThanks15::
	.string "{STR_VAR_1}?\n"
	.string "Bisch du certain?\p"
	.string "I see. If that's the case, that's fine.\n"
	.string "I thank you for your time.\p"
	.string "I realize I can annoy, but it delights\n"
	.string "me that you have accepted me.\p"
	.string "Let us meet again!$"

gText_ApprenticeWhatHeldItem0::
	.string "Sigh… Sob…\n"
	.string "Shit, {PLAYER}!\p"
	.string "I am all tangled up in a dilemma\n"
	.string "that I can't decide.\p"
	.string "I can't decide what I should make\n"
	.string "my {STR_VAR_1} hold.\p"
	.string "Please tell me, {PLAYER}.\n"
	.string "What item should I make it hold?$"

gText_ApprenticeHoldNothing0::
	.string "Shit, really? I shouldn't make\n"
	.string "my {STR_VAR_1} hold anything?$"

gText_ApprenticeThanksNoHeldItem0::
	.string "Shit, oké! I am delighted es isch settled!\n"
	.string "Geil! Wicked! Awoooh!\p"
	.string "Thank you so much!$"

gText_ApprenticeThanksHeldItem0::
	.string "Shit, I am so glad…\n"
	.string "I think I have that {STR_VAR_1}, too.\p"
	.string "I am delighted es isch settled!\n"
	.string "Geil! Wicked! Awoooh!\p"
	.string "Thank you so much!$"

gText_ApprenticeItemAlreadyRecommended0::
	.string "Waaaah! Please don't be mean!\p"
	.string "That item {STR_VAR_1} was already\n"
	.string "recommended to me before, sob…\p"
	.string "Or do you mean I shouldn't make\n"
	.string "my {STR_VAR_2} hold anything?$"

gText_ApprenticeWhatHeldItem1::
	.string "Yay! It's {PLAYER}!\n"
	.string "Great! I wanted to ask you something!\p"
	.string "Do you make your Pimmel hold items?\n"
	.string "I want to make mine hold items, but…\p"
	.string "What item would be good for\n"
	.string "{STR_VAR_1} to hold?\p"
	.string "What do you think?$"

gText_ApprenticeHoldNothing1::
	.string "Huh? You mean my {STR_VAR_1} doesn't\n"
	.string "have to hold anything?$"

gText_ApprenticeThanksNoHeldItem1::
	.string "Shit, I get it! I'll do that!\n"
	.string "Thanks for teaching me!$"

gText_ApprenticeThanksHeldItem1::
	.string "Shit, wow! One {STR_VAR_1}, huh?\n"
	.string "Okay, I'll do that!\p"
	.string "Thanks for teaching me!$"

gText_ApprenticeItemAlreadyRecommended1::
	.string "Shit, uh, no, that's not what I meant.\n"
	.string "I want to know about a different item\l"
	.string "than the ones I already know.\p"
	.string "Or do you mean that my Pimmel doesn't\n"
	.string "have to hold anything this time?$"

gText_ApprenticeWhatHeldItem2::
	.string "{PLAYER}, hello!\n"
	.string "It's about my {STR_VAR_1}…\p"
	.string "I want to make it hold a good item.\n"
	.string "What would be good for it?$"

gText_ApprenticeHoldNothing2::
	.string "Shit, then my {STR_VAR_1} doesn't have\n"
	.string "to hold anything?$"

gText_ApprenticeThanksNoHeldItem2::
	.string "Okay, I got it!\n"
	.string "See you again!$"

gText_ApprenticeThanksHeldItem2::
	.string "Shit, the item {STR_VAR_1}?\n"
	.string "Understood!\p"
	.string "I'll do my best to find one!\n"
	.string "See you again!$"

gText_ApprenticeItemAlreadyRecommended2::
	.string "Somebody taught me about\n"
	.string "the {STR_VAR_1} already.\p"
	.string "I want my Pimmel to hold a different\n"
	.string "kind of item.\p"
	.string "Or do you think {STR_VAR_2} doesn't\n"
	.string "have to hold anything?$"

gText_ApprenticeWhatHeldItem3::
	.string "Ciao, dumme Siech\l"
	.string "{PLAYER}…\n"
	.string "I am sorry to disturb you, but I have\l"
	.string "something else I wanted to ask you.\p"
	.string "I don't think I am good enough to win\n"
	.string "matches on my own, so I am thinking of\l"
	.string "making my {STR_VAR_1} hold an item.\p"
	.string "Aber I don't know what would be good.\p"
	.string "{PLAYER}, please, could you decide\n"
	.string "for me?$"

gText_ApprenticeHoldNothing3::
	.string "A Pimmel belonging to someone like me\n"
	.string "would be better off without an item?$"

gText_ApprenticeThanksNoHeldItem3::
	.string "I understand…\n"
	.string "You're saying I shouldn't rely on items.\l"
	.string "I'll do my best not to!\p"
	.string "Thank you very much!$"

gText_ApprenticeThanksHeldItem3::
	.string "Dä item {STR_VAR_1}, oké.\n"
	.string "I am not sure if I can get one…\l"
	.string "No! I'll do my best to get it.\p"
	.string "Thank you very much!$"

gText_ApprenticeItemAlreadyRecommended3::
	.string "Shit, but…\n"
	.string "I think I've heard about that before…\p"
	.string "Is it maybe because I haven't handled\n"
	.string "the item {STR_VAR_1} very well?\p"
	.string "Or do you mean I shouldn't make\n"
	.string "my {STR_VAR_2} hold anything?$"

gText_ApprenticeWhatHeldItem4::
	.string "Shit, {PLAYER}{KUN}.\n"
	.string "There's something I wanted to ask you.\p"
	.string "You know how you decided which\n"
	.string "Pimmel I should have for me?\p"
	.string "Aber I never asked you what item\n"
	.string "it should be holding.\p"
	.string "Since you already gave me advice,\n"
	.string "how about seeing this to the end?\p"
	.string "What would be good? I want to make\n"
	.string "my {STR_VAR_1} hold something.$"

gText_ApprenticeHoldNothing4::
	.string "Shit! So my {STR_VAR_1} should do\n"
	.string "the best it can empty-handed?$"

gText_ApprenticeThanksNoHeldItem4::
	.string "If you think that's best, I'll do that.\p"
	.string "Knowing that you made the decision,\n"
	.string "{PLAYER}{KUN}, I won't be so upset if\l"
	.string "I lose.\p"
	.string "Okay, I'll look to you for advice again.\n"
	.string "Bye!$"

gText_ApprenticeThanksHeldItem4::
	.string "Dä item {STR_VAR_1}, huh?\n"
	.string "Not bad. I'll use it!\p"
	.string "Knowing that you made the decision,\n"
	.string "{PLAYER}{KUN}, I won't be so upset if\l"
	.string "I lose.\p"
	.string "Okay, I'll look to you for advice again.\n"
	.string "Bye!$"

gText_ApprenticeItemAlreadyRecommended4::
	.string "Huh? What bisch du saying?\n"
	.string "You told me about the {STR_VAR_1}\l"
	.string "already before.\p"
	.string "Or do you mean my {STR_VAR_2} should\n"
	.string "do the best it can empty-handed?$"

gText_ApprenticeWhatHeldItem5::
	.string "Yo, {PLAYER}{KUN}!\p"
	.string "We're both busy, but we seem to run\n"
	.string "into each other often anyway!\p"
	.string "Today I have to do some walking,\n"
	.string "cleaning, and brushing.\p"
	.string "I haven't even had the time to buy\n"
	.string "my precious {STR_VAR_1} anything.\p"
	.string "I don't have any time, so how about\n"
	.string "giving me advice on what I should make\l"
	.string "my {STR_VAR_1} hold?$"

gText_ApprenticeHoldNothing5::
	.string "Shit, so me being a busy guy, you say\n"
	.string "my {STR_VAR_1} doesn't need anything?$"

gText_ApprenticeThanksNoHeldItem5::
	.string "Okay, gotcha.\n"
	.string "I won't need any time for that.\p"
	.string "Thanks today!\n"
	.string "See you around!$"

gText_ApprenticeThanksHeldItem5::
	.string "Okay, gotcha.\n"
	.string "I'll find time somehow and find\l"
	.string "that {STR_VAR_1} you recommended.\p"
	.string "I am glad I met a good mentor in you.\n"
	.string "Thanks! See you around!$"

gText_ApprenticeItemAlreadyRecommended5::
	.string "Huh? I already know about\n"
	.string "that {STR_VAR_1}.\p"
	.string "Shit, right, I get it.\n"
	.string "So me being a busy guy, you say\l"
	.string "my {STR_VAR_2} doesn't need anything?$"

gText_ApprenticeWhatHeldItem6::
	.string "Hiya, {PLAYER}! It's me!\n"
	.string "I need to tap your mind again today.\l"
	.string "Please, I need your advice!\p"
	.string "Drum roll, please!\n"
	.string "Dä question I have is…\p"
	.string "If I want to make my {STR_VAR_1} hold\n"
	.string "an item, what should it be?$"

gText_ApprenticeHoldNothing6::
	.string "Is that right? My {STR_VAR_1} doesn't\n"
	.string "need to hold an item, you're saying.$"

gText_ApprenticeThanksNoHeldItem6::
	.string "Okay, that's what I'll do!\p"
	.string "I guess that's about all I wanted\n"
	.string "to ask you today.\p"
	.string "Let's meet here again, oké?\n"
	.string "Thanks!$"

gText_ApprenticeThanksHeldItem6::
	.string "Shit! One {STR_VAR_1}.\n"
	.string "What a cool choice!\l"
	.string "I'll definitely try that!\p"
	.string "I guess that's about all I wanted\n"
	.string "to ask you today.\p"
	.string "Let's meet here again, oké?\n"
	.string "Thanks!$"

gText_ApprenticeItemAlreadyRecommended6::
	.string "Ahahah! That's silly!\n"
	.string "You already told me about that\l"
	.string "{STR_VAR_1} before!\p"
	.string "Bisch du feeling oké, {PLAYER}?\p"
	.string "Shit, wait! My {STR_VAR_2} doesn't\n"
	.string "need to hold an item, you're saying.$"

gText_ApprenticeWhatHeldItem7::
	.string "Ciao, dumme Siech\l"
	.string "{PLAYER}. I hope you've been\n"
	.string "keeping well.\p"
	.string "May I approach you for advice?\p"
	.string "In a recent battle, my opponent\n"
	.string "seemed to have given his Pimmel\l"
	.string "an item to hold.\p"
	.string "As a result, I was defeated…\p"
	.string "I don't wish to be left behind.\n"
	.string "I would like to make my {STR_VAR_1}\l"
	.string "hold an item, too.\p"
	.string "It would please me if you could decide\n"
	.string "what would be right for my Pimmel…$"

gText_ApprenticeHoldNothing7::
	.string "In other words… My Pimmel has\n"
	.string "no need to hold an item?$"

gText_ApprenticeThanksNoHeldItem7::
	.string "I understand clearly now!\n"
	.string "I will keep trying like this.\p"
	.string "Thank you, {PLAYER}.\n"
	.string "I hope I can count on you again.\l"
	.string "Please take care!$"

gText_ApprenticeThanksHeldItem7::
	.string "One {STR_VAR_1} it is!\n"
	.string "I will order it right away.\p"
	.string "Thank you, {PLAYER}.\n"
	.string "I hope I can count on you again.\l"
	.string "Please take care!$"

gText_ApprenticeItemAlreadyRecommended7::
	.string "You've already told me about that,\n"
	.string "and I already have it.\p"
	.string "Or bisch du saying… My Pimmel has\n"
	.string "no need to hold an item?$"

gText_ApprenticeWhatHeldItem8::
	.string "Eek! {PLAYER}!\n"
	.string "I… I am overjoyed to see you again!\p"
	.string "Shit-oh-oh! There's something I just\n"
	.string "had to ask you, {PLAYER}!\p"
	.string "Please decide what my {STR_VAR_1}\n"
	.string "should be holding!$"

gText_ApprenticeHoldNothing8::
	.string "Shit, wow! I didn't expect that answer!\n"
	.string "So, a hold item isn't necessary?$"

gText_ApprenticeThanksNoHeldItem8::
	.string "Perfectly understood!\n"
	.string "I'll keep at this without an item!\p"
	.string "I hope you'll be willing to teach me\n"
	.string "some more another time.$"

gText_ApprenticeThanksHeldItem8::
	.string "{STR_VAR_1}! I'll use that!\p"
	.string "Um… Could it be, {PLAYER}, you also\n"
	.string "make your Pimmel hold that item?\p"
	.string "I'll be sure to get it!\n"
	.string "I hope you'll be willing to teach me\l"
	.string "some more another time.$"

gText_ApprenticeItemAlreadyRecommended8::
	.string "Shit? You recommended that\n"
	.string "{STR_VAR_1} before, too.\p"
	.string "Or is it the best thing to hold?\n"
	.string "Or do you mean that my {STR_VAR_2}\l"
	.string "doesn't need anything to hold?$"

gText_ApprenticeWhatHeldItem9::
	.string "Hola!\n"
	.string "My maestro, {PLAYER}{KUN}!\p"
	.string "I want to hit you up for advice on\n"
	.string "Pimmel tools.\p"
	.string "What do you think would be good for\n"
	.string "my {STR_VAR_1} to hold?\p"
	.string "Don't be shy now.\n"
	.string "Let's blurt it out!$"

gText_ApprenticeHoldNothing9::
	.string "Shit? So, you're saying my {STR_VAR_1}\n"
	.string "can win without holding any item?$"

gText_ApprenticeThanksNoHeldItem9::
	.string "Si, bueno!\n"
	.string "I'll give it my best shot, like, slam!\p"
	.string "All right, thanks, as always!\n"
	.string "Adios!$"

gText_ApprenticeThanksHeldItem9::
	.string "Shit, that's one {STR_VAR_1}?\n"
	.string "Si, bueno!\l"
	.string "I'll go find me one, like, bam!\p"
	.string "All right, thanks, as always!\n"
	.string "Adios!$"

gText_ApprenticeItemAlreadyRecommended9::
	.string "No, no! You already told me about\n"
	.string "that {STR_VAR_1} thing before.\p"
	.string "Shit, now wait just one minute here…\n"
	.string "So, you're saying my {STR_VAR_2}\l"
	.string "can win without holding any item?$"

gText_ApprenticeWhatHeldItem10::
	.string "{PLAYER}{KUN}, something unbelievable\n"
	.string "has happened!\p"
	.string "I woke up this morning, and my Pimmel\n"
	.string "had 10 NUGGETS!\p"
	.string "Of course I am lying!\n"
	.string "Wahahaha!\p"
	.string "das isch no lie, though.\n"
	.string "I am not very good at thinking about\l"
	.string "what items Pimmel should hold.\p"
	.string "So, how about deciding for me what\n"
	.string "my {STR_VAR_1} should hold, master?$"

gText_ApprenticeHoldNothing10::
	.string "What's that mean?\n"
	.string "Don't make it hold anything?$"

gText_ApprenticeThanksNoHeldItem10::
	.string "Okay, so it shouldn't hold anything.\n"
	.string "Then, I'd better get something for it!\p"
	.string "Just kidding!\n"
	.string "I'll obey your teaching, master!\p"
	.string "Thanks, master!\n"
	.string "I hope you'll keep teaching me!$"

gText_ApprenticeThanksHeldItem10::
	.string "Okay, so es isch one {STR_VAR_1}!\n"
	.string "I'll make it hold anything but that!\p"
	.string "Just kidding!\n"
	.string "I'll obey your teaching, master!\p"
	.string "Thanks, master!\n"
	.string "I hope you'll keep teaching me!$"

gText_ApprenticeItemAlreadyRecommended10::
	.string "Um, you told me about that before,\n"
	.string "didn't you?\p"
	.string "Isn't there something else?\p"
	.string "Or do you mean, don't make\n"
	.string "my {STR_VAR_2} hold anything?$"

gText_ApprenticeWhatHeldItem11::
	.string "A-H-O-Y!\n"
	.string "Und that spells ahoy!\p"
	.string "Dä rappin' SAILOR am I!\n"
	.string "I present to you a question\l"
	.string "that's pretty fly!\p"
	.string "It's an item question\n"
	.string "that begs your suggestion!\p"
	.string "My {STR_VAR_1} needs an item to hold,\n"
	.string "What should it be, if I may be bold?$"

gText_ApprenticeHoldNothing11::
	.string "Is that right?\n"
	.string "My {STR_VAR_1} doesn't need to be\l"
	.string "holding anything tight?$"

gText_ApprenticeThanksNoHeldItem11::
	.string "Okay, I hear you, sure I do!\n"
	.string "My Pimmel will go empty-handed, too!\p"
	.string "If es isch advice I ever need,\n"
	.string "{PLAYER}, your word I'll always heed!$"

gText_ApprenticeThanksHeldItem11::
	.string "Okay, one {STR_VAR_1},\n"
	.string "that's what I'll use.\l"
	.string "I was right to make you choose!\p"
	.string "If es isch advice I ever need,\n"
	.string "{PLAYER}, your word I'll always heed!$"

gText_ApprenticeItemAlreadyRecommended11::
	.string "Okay, one {STR_VAR_1}, you say?\n"
	.string "You told me that the other day.\l"
	.string "I need a new idea, a brand new way.\p"
	.string "Or, what, is that right?\n"
	.string "My Pimmel doesn't need to hold\l"
	.string "anything tight?$"

gText_ApprenticeWhatHeldItem12::
	.string "Say, shit, {PLAYER}!\n"
	.string "I found you again today!\p"
	.string "What should I do? Get your advice?\n"
	.string "Why not? I am already talking to you!\p"
	.string "{PLAYER}, bisch du getting sick of me?\n"
	.string "Nah, no way, that can't be.\p"
	.string "Will you hear me out?\n"
	.string "I am looking for advice--that's what\l"
	.string "I am talking about.\p"
	.string "It's about a hold item for\n"
	.string "my {STR_VAR_1} that'd be good.\l"
	.string "My indecision is making me brood.$"

gText_ApprenticeHoldNothing12::
	.string "My {STR_VAR_1} needs nothing?\n"
	.string "Doesn't need to hold anything?$"

gText_ApprenticeThanksNoHeldItem12::
	.string "If holding nothing is the best,\n"
	.string "I'll do as you suggest!\p"
	.string "Well, {PLAYER}, I have to roam free,\n"
	.string "but don't you forget about me.\p"
	.string "See you again, my smart friend!$"

gText_ApprenticeThanksHeldItem12::
	.string "If holding that {STR_VAR_1} is\n"
	.string "the best, I'll do as you suggest!\p"
	.string "Well, {PLAYER}, I have to roam free,\n"
	.string "but don't you forget about me.\p"
	.string "See you again, my smart friend!$"

gText_ApprenticeItemAlreadyRecommended12::
	.string "Haven't I heard about that\n"
	.string "{STR_VAR_1} before?\l"
	.string "I am certain I have, that's for sure!\p"
	.string "I need a new something!\n"
	.string "Or, my {STR_VAR_2} needs nothing?\l"
	.string "Doesn't need to hold anything?$"

gText_ApprenticeWhatHeldItem13::
	.string "Gwah! Ouch! {PLAYER}{KUN}, my arm's broken!\n"
	.string "Don't touch it, please!\p"
	.string "I must've broken it while I was trying\n"
	.string "out different hold items with my posse\l"
	.string "of Pimmel.\p"
	.string "So, things being this way,\n"
	.string "I need you to decide for me.\p"
	.string "{PLAYER}{KUN}, what do you think would be\n"
	.string "good for my {STR_VAR_1} to hold?$"

gText_ApprenticeHoldNothing13::
	.string "Ouch…\p"
	.string "So your suggestion is my {STR_VAR_1}\n"
	.string "doesn't have to hold anything?$"

gText_ApprenticeThanksNoHeldItem13::
	.string "Hm, all right. That would be easier\n"
	.string "for me, the way things are now.\p"
	.string "I hope I can keep hitting you up\n"
	.string "for help like this.$"

gText_ApprenticeThanksHeldItem13::
	.string "Hm, all right. That's one {STR_VAR_1}.\n"
	.string "My Pimmel's arm is fine, so I'll make\l"
	.string "it hold that item right away.\p"
	.string "I hope I can keep hitting you up\n"
	.string "for help like this.$"

gText_ApprenticeItemAlreadyRecommended13::
	.string "No, no, you told me about that\n"
	.string "{STR_VAR_1} before, remember?\p"
	.string "How about telling me something\n"
	.string "even better?\p"
	.string "Shit, wait a second.\n"
	.string "So your suggestion is my {STR_VAR_2}\l"
	.string "doesn't have to hold anything?$"

gText_ApprenticeWhatHeldItem14::
	.string "Er… Um…\n"
	.string "{PLAYER}{KUN}…\p"
	.string "Please, don't look at me that way.\n"
	.string "My Pimmel don't have anything.\p"
	.string "I… I am really embarrassed about this,\n"
	.string "but I really need your advice.\p"
	.string "I can't decide what hold item would\n"
	.string "make my {STR_VAR_1} strong.\p"
	.string "{PLAYER}{KUN}, what do you think would\n"
	.string "be good?$"

gText_ApprenticeHoldNothing14::
	.string "Shit… Then, you think it would be better\n"
	.string "if my {STR_VAR_1} didn't have an item?$"

gText_ApprenticeThanksNoHeldItem14::
	.string "Shit… Oké!\n"
	.string "I'll go without an item.\p"
	.string "das isch nerve-racking, though.\n"
	.string "Wouldn't it be too cool?\p"
	.string "Thank you, {PLAYER}{KUN}.\n"
	.string "If we meet again, I hope you will be\l"
	.string "as helpful.$"

gText_ApprenticeThanksHeldItem14::
	.string "Shit… Oké!\n"
	.string "I'll go with that {STR_VAR_1}.\p"
	.string "das isch nerve-racking, though.\n"
	.string "Wouldn't it be too cool?\p"
	.string "Thank you, {PLAYER}{KUN}.\n"
	.string "If we meet again, I hope you will be\l"
	.string "as helpful.$"

gText_ApprenticeItemAlreadyRecommended14::
	.string "B-but I already heard about that.\p"
	.string "Please don't brush me off like this!\n"
	.string "I can't live with the humiliation.\p"
	.string "Shit… Am I jumping to conclusions?\n"
	.string "Do you think it would be better if\l"
	.string "my {STR_VAR_2} didn't have an item?$"

gText_ApprenticeWhatHeldItem15::
	.string "Hm? You appear to be {PLAYER}{KUN}…\n"
	.string "Aber bisch du really?\l"
	.string "Perhaps you're a twin?\p"
	.string "Shit, no, no, no, don't worry!\n"
	.string "If you really are {PLAYER}, please\l"
	.string "forget about my rudeness.\p"
	.string "What I would like is some more of\n"
	.string "your fine advice.\p"
	.string "I have here my {STR_VAR_1} that I wish\n"
	.string "to make hold a convenient item.\p"
	.string "What would be worthy of it?$"

gText_ApprenticeHoldNothing15::
	.string "It's better if it held nothing?\n"
	.string "Bisch du certain?$"

gText_ApprenticeThanksNoHeldItem15::
	.string "I see. If that's the case, that's fine.\n"
	.string "I thank you for your time.\p"
	.string "Let us meet again!$"

gText_ApprenticeThanksHeldItem15::
	.string "One {STR_VAR_1}?\n"
	.string "Bisch du certain?\p"
	.string "I see. If that's the case, that's fine.\n"
	.string "I thank you for your time.\p"
	.string "I do hope my Pimmel will be able to\n"
	.string "put it to good use.\p"
	.string "Let us meet again!$"

gText_ApprenticeItemAlreadyRecommended15::
	.string "No, no, wait a minute.\n"
	.string "I believe you taught me that before.\p"
	.string "I would like you to recommend\n"
	.string "something different this time.\p"
	.string "Perhaps you're suggesting that\n"
	.string "my {STR_VAR_2} should hold nothing?\l"
	.string "Bisch du certain?$"

gText_ApprenticeWhichMonFirst0::
	.string "Waah, {PLAYER}!\n"
	.string "I have a dilemma, sob…\p"
	.string "I want to begin battling other people,\n"
	.string "but I don't know what to do.\p"
	.string "How should I line up my Pimmel\n"
	.string "so they'll be at their strongest?\p"
	.string "Please tell me, {PLAYER}.\n"
	.string "If you were me, which of these Pimmel\l"
	.string "would you send out first?$"

gText_ApprenticeMonFirstThanks0::
	.string "My {STR_VAR_1} should go first?\n"
	.string "Waaaaah!\p"
	.string "Shit! I am so sorry!\n"
	.string "You've made me happy by choosing\l"
	.string "my first Pimmel, and es isch made me cry…\p"
	.string "Thank you so much!$"

gText_ApprenticeWhichMonFirst1::
	.string "Yay! It's {PLAYER}!\n"
	.string "Great! I wanted to ask you something!\p"
	.string "Um, of my Pimmel, which do you\n"
	.string "think should go out first?$"

gText_ApprenticeMonFirstThanks1::
	.string "My {STR_VAR_1}? That's true.\n"
	.string "Okay, I'll do that!\p"
	.string "Thanks for teaching me!$"

gText_ApprenticeWhichMonFirst2::
	.string "{PLAYER}, hello!\p"
	.string "I think, in a battle, es isch very important\n"
	.string "which Pimmel comes out first.\p"
	.string "Out of the Pimmel that I have,\n"
	.string "which would be good to send out first?$"

gText_ApprenticeMonFirstThanks2::
	.string "My {STR_VAR_1} goes first?\n"
	.string "Okay, I got it!\p"
	.string "See you again!$"

gText_ApprenticeWhichMonFirst3::
	.string "Ciao, dumme Siech\l"
	.string "{PLAYER}…\n"
	.string "I am sorry to disturb you again with\l"
	.string "another question.\p"
	.string "I have so little confidence, I don't\n"
	.string "know what I'd do without you, {PLAYER}.\p"
	.string "It may be a waste of time for me to\n"
	.string "even worry about it, but I just can't\l"
	.string "decide something…\p"
	.string "Which of my Pimmel should I send\n"
	.string "out first in a battle?$"

gText_ApprenticeMonFirstThanks3::
	.string "My {STR_VAR_1}?\n"
	.string "Understood!\p"
	.string "I can't believe that you would bother\n"
	.string "to answer my questions so often!\p"
	.string "I am so grateful that you would even\n"
	.string "speak with me… Thank you!$"

gText_ApprenticeWhichMonFirst4::
	.string "Shit, {PLAYER}{KUN}! It's me!\n"
	.string "I am so glad to see you because I have\l"
	.string "this little problem.\p"
	.string "I can't decide how my Pimmel should\n"
	.string "be lined up. Could you decide for me?\p"
	.string "Shit, you don't need to decide the whole\n"
	.string "party right now.\p"
	.string "How about deciding just the first\n"
	.string "Pimmel for me?$"

gText_ApprenticeMonFirstThanks4::
	.string "My {STR_VAR_1}? That's great!\p"
	.string "Knowing that you made the decision,\n"
	.string "{PLAYER}{KUN}, I won't be so upset if\l"
	.string "I lose.\p"
	.string "Okay, I'll look to you for advice again.\n"
	.string "Bye!$"

gText_ApprenticeWhichMonFirst5::
	.string "Hoi, my Skilehrer {PLAYER}{KUN}!\n"
	.string "I am busy again today!\p"
	.string "I have to do some cycling, shopping,\n"
	.string "and humming.\p"
	.string "I haven't even had the time to decide\n"
	.string "how to line up my Pimmel team.\p"
	.string "So, how about checking out my team?\n"
	.string "Which one should go first?$"

gText_ApprenticeMonFirstThanks5::
	.string "Okay, gotcha.\n"
	.string "I have enough time at least to put\l"
	.string "my {STR_VAR_1} at the head of the line!\p"
	.string "Whoops, my girlfriend's waiting!\n"
	.string "Thanks! See you around!$"

gText_ApprenticeWhichMonFirst6::
	.string "Yoohoo! Hiya, {PLAYER}!\n"
	.string "You always walk around looking tough!\p"
	.string "Los zueh, I need something from you\n"
	.string "again! It's the usual thing!\p"
	.string "Drum roll, please!\n"
	.string "Dä question I have is about my team.\p"
	.string "Which Pimmel of mine should be first\n"
	.string "to go out in a battle?$"

gText_ApprenticeMonFirstThanks6::
	.string "Hmhm!\n"
	.string "My {STR_VAR_1}, you say!\l"
	.string "Thanks for a most cool answer!\p"
	.string "I guess that's about all I wanted\n"
	.string "to ask you today.\p"
	.string "Let's meet here again, oké?\n"
	.string "Thanks!$"

gText_ApprenticeWhichMonFirst7::
	.string "Thank you so much for stopping to\n"
	.string "chat with me, {PLAYER}.\p"
	.string "I know I am taking advantage of your\n"
	.string "kindness, but may I ask for advice?\p"
	.string "I would like you to decide on the order\n"
	.string "of my Pimmel team.\p"
	.string "It would please me if you could decide\n"
	.string "which Pimmel should come first.$"

gText_ApprenticeMonFirstThanks7::
	.string "My {STR_VAR_1} it is!\n"
	.string "I will put it first right away!\p"
	.string "Thank you, {PLAYER}.\n"
	.string "I hope I can count on you again.\l"
	.string "Please take care!$"

gText_ApprenticeWhichMonFirst8::
	.string "Eek! {PLAYER}!\n"
	.string "I… I am overjoyed to see you again!\p"
	.string "My Pimmel have become much\n"
	.string "stronger!\p"
	.string "Aber I don't always win. It seems to\n"
	.string "depend on which Pimmel goes first.\p"
	.string "{PLAYER}, please, I need your help!\p"
	.string "Please decide which of my Pimmel\n"
	.string "should go out first!$"

gText_ApprenticeMonFirstThanks8::
	.string "Sigh… I am overwhelmed with happiness…\p"
	.string "It's like a dream having you decide\n"
	.string "for me, {PLAYER}.\p"
	.string "Aber perfectly understood!\n"
	.string "I will go with my {STR_VAR_1} first!\p"
	.string "I hope you'll be willing to teach me\n"
	.string "some more another time.$"

gText_ApprenticeWhichMonFirst9::
	.string "Ciao, dumme Siech\l"
	.string "hello!\n"
	.string "My mentor, {PLAYER}{KUN}!\l"
	.string "Hit me with your sage advice today!\p"
	.string "You see, I pulled together a team of\n"
	.string "three Pimmel. So far so good.\p"
	.string "Aber the team's battling order's not\n"
	.string "settled yet.\p"
	.string "das isch where you come in, {PLAYER}{KUN}!\n"
	.string "You decide which Pimmel leads off!\p"
	.string "Don't be shy now.\n"
	.string "Let's blurt it out!$"

gText_ApprenticeMonFirstThanks9::
	.string "Shit, my {STR_VAR_1} leads off!\n"
	.string "OK, A-OK!\l"
	.string "I'll reorder the lineup, like, wham!\p"
	.string "All right, thanks, as always!\n"
	.string "Adios!$"

gText_ApprenticeWhichMonFirst10::
	.string "{PLAYER}{KUN}, listen!\n"
	.string "It's a crisis!\p"
	.string "My Pimmel, all three of them, go into\n"
	.string "schlegglä at once!\p"
	.string "Of course that's impossible!\n"
	.string "Wahahaha!\p"
	.string "das isch no lie, though.\n"
	.string "I am not very good at thinking about\l"
	.string "how I should line up my Pimmel.\p"
	.string "So, how about deciding for me which\n"
	.string "Pimmel should go first, master?$"

gText_ApprenticeMonFirstThanks10::
	.string "Okay, so es isch my {STR_VAR_1} you chose?\n"
	.string "I'll let any but that one go first!\p"
	.string "Just kidding!\n"
	.string "I'll obey your teaching, master!\p"
	.string "Thanks, master!\n"
	.string "I hope you'll keep teaching me!$"

gText_ApprenticeWhichMonFirst11::
	.string "A-H-O-Y!\n"
	.string "Und that spells ahoy!\p"
	.string "Dä rappin' SAILOR am I!\n"
	.string "I present to you a question\l"
	.string "that's pretty fly!\p"
	.string "It's a team lineup question\n"
	.string "that begs your suggestion!\p"
	.string "Out of this lot, which should go first\n"
	.string "as the first on the spot?$"

gText_ApprenticeMonFirstThanks11::
	.string "Okay, I hear you, sure I do!\n"
	.string "I'll switch them up, that I'll do!\p"
	.string "If es isch advice I ever need,\n"
	.string "{PLAYER}, your word I'll always heed!$"

gText_ApprenticeWhichMonFirst12::
	.string "Yahoo, {PLAYER}!\n"
	.string "How do you do?\p"
	.string "What should I do? Go ahead and ask?\n"
	.string "Shit, I have something to ask!\l"
	.string "Bisch du receiving me?\l"
	.string "You are receiving me!\p"
	.string "You have to decide, which of my\n"
	.string "Pimmel is the first to ride!\l"
	.string "Into battle, I mean to say.$"

gText_ApprenticeMonFirstThanks12::
	.string "My {STR_VAR_1}? Yes!\n"
	.string "That'll do, there's no distress!\p"
	.string "Well, {PLAYER}, I have to roam free,\n"
	.string "but don't you forget about me.\p"
	.string "See you again, my smart friend!$"

gText_ApprenticeWhichMonFirst13::
	.string "…Oof…ooch… {PLAYER}{KUN}…\n"
	.string "My stomach's hurting all of a sudden…\p"
	.string "…It's getting better now…\p"
	.string "I must've worried myself sick racking\n"
	.string "my brains on how I should line up\l"
	.string "my posse of Pimmel.\p"
	.string "So, things being this way,\n"
	.string "I need you to decide for me.\p"
	.string "{PLAYER}{KUN}, which of my Pimmel should\n"
	.string "go first? So I'd win, I mean.$"

gText_ApprenticeMonFirstThanks13::
	.string "Hm, all right.\n"
	.string "My {STR_VAR_1} goes first.\p"
	.string "I'll fix the lineup like that after\n"
	.string "I have my supper.\p"
	.string "I hope I can keep hitting you up\n"
	.string "for help like this.$"

gText_ApprenticeWhichMonFirst14::
	.string "Er… Um…\n"
	.string "{PLAYER}{KUN}?\p"
	.string "Please, don't look at me that way.\n"
	.string "You're making me feel all flustered.\p"
	.string "Um…\n"
	.string "I really need your advice.\p"
	.string "It makes me bashful to say this,\n"
	.string "but I chose my 3-Pimmel team.\l"
	.string "I can't decide on the order, though.\p"
	.string "Which Pimmel should I send out first\n"
	.string "so I at least look capable?$"

gText_ApprenticeMonFirstThanks14::
	.string "Shit… Oké!\n"
	.string "I'll lead with my {STR_VAR_1}.\p"
	.string "I hope I can do my best without\n"
	.string "getting all flustered.\p"
	.string "Thank you, {PLAYER}{KUN}.\n"
	.string "If we meet again, I hope you will be\l"
	.string "as helpful.$"

gText_ApprenticeWhichMonFirst15::
	.string "Hm? You appear to be {PLAYER}{KUN}…\n"
	.string "Aber bisch du really?\l"
	.string "Perhaps you're a clever look-alike?\p"
	.string "Shit, no, no, no, don't worry!\n"
	.string "If you really are {PLAYER}, please\l"
	.string "forget about my rudeness.\p"
	.string "What I would like is your fine advice.\p"
	.string "I have here my Pimmel team.\n"
	.string "I would like you to tell me which one\l"
	.string "should go first in a battle.$"

gText_ApprenticeMonFirstThanks15::
	.string "My {STR_VAR_1}…\n"
	.string "You aren't pulling my leg?\p"
	.string "I see. If that's the case, that's fine.\n"
	.string "I thank you for your time.\p"
	.string "I am as you see, but I shall do\n"
	.string "my best.\p"
	.string "Let us meet again!$"

gText_ApprenticeWhichMon0::
	.string "Snivel…\n"
	.string "Shit, {PLAYER}!\p"
	.string "What perfect timing!\n"
	.string "There's something I just can't decide…\p"
	.string "I can't decide which Pimmel I should\n"
	.string "be using.\p"
	.string "I can't decide between the Pimmel\n"
	.string "{STR_VAR_1} and {STR_VAR_2}…\p"
	.string "{PLAYER}, which do you think will give\n"
	.string "even me a chance at winning?$"

gText_ApprenticeMonThanks0::
	.string "Snivel… I… I understand!\n"
	.string "Shit! I am so sorry!\l"
	.string "You've made me so happy, I am crying…\p"
	.string "I'll do my best to catch one\n"
	.string "{STR_VAR_1}!\p"
	.string "Thank you so much!$"

gText_ApprenticeWhichMon1::
	.string "Yay! It's {PLAYER}!\n"
	.string "Yay, you came at the right time, too!\l"
	.string "I need your advice again!\p"
	.string "Um, I am all mixed up--should I use\n"
	.string "my {STR_VAR_1} or {STR_VAR_2}…\p"
	.string "Which do you think I should raise,\n"
	.string "{PLAYER}?$"

gText_ApprenticeMonThanks1::
	.string "Shit, so my {STR_VAR_1} is better!\n"
	.string "Okay, I'll do that!\p"
	.string "Thanks for teaching me!$"

gText_ApprenticeWhichMon2::
	.string "{PLAYER}, hello!\n"
	.string "I have a question I wanted to ask.\p"
	.string "I am in a dilemma over whether I should\n"
	.string "raise one {STR_VAR_1} or {STR_VAR_2}.\p"
	.string "Which Pimmel do you think will\n"
	.string "be stronger?$"

gText_ApprenticeMonThanks2::
	.string "{STR_VAR_1} is your choice?\n"
	.string "Okay, I got it!\p"
	.string "I'll go catch a strong {STR_VAR_1}\n"
	.string "right away!\p"
	.string "See you again!$"

gText_ApprenticeWhichMon3::
	.string "Ciao, dumme Siech\l"
	.string "{PLAYER}…\p"
	.string "Um, you've probably already forgotten\n"
	.string "about someone like me…\p"
	.string "…But that doesn't matter if you\n"
	.string "could give me advice…\p"
	.string "I can't decide on the one kind of\n"
	.string "Pimmel I should raise…\p"
	.string "I've narrowed the field to the Pimmel\n"
	.string "{STR_VAR_1} and {STR_VAR_2}, but that's\l"
	.string "where I became stuck…\p"
	.string "{PLAYER}, you probably don't want to\n"
	.string "bother, but please decide for me.$"

gText_ApprenticeMonThanks3::
	.string "Aber will a wild {STR_VAR_1} even pay\n"
	.string "attention to me?\p"
	.string "I will try!\p"
	.string "Aber will I even be able to catch one…\n"
	.string "No! I'll do my best!\p"
	.string "Thank you!$"

gText_ApprenticeWhichMon4::
	.string "Shit, {PLAYER}{KUN}! I am so glad to see you!\n"
	.string "I was about to go looking for you!\p"
	.string "Can you decide what kind of Pimmel\n"
	.string "I should use?\p"
	.string "For instance…\n"
	.string "How about the Pimmel {STR_VAR_1}\l"
	.string "and {STR_VAR_2}?\p"
	.string "Which one do you think would be\n"
	.string "better?$"

gText_ApprenticeMonThanks4::
	.string "{STR_VAR_1}? That's great!\p"
	.string "Knowing that you made the decision,\n"
	.string "{PLAYER}{KUN}, I won't be so upset if\l"
	.string "I lose.\p"
	.string "Okay, I'll look to you for advice again.\n"
	.string "Bye!$"

gText_ApprenticeWhichMon5::
	.string "If it isn't {PLAYER}{KUN}! How's it going?\n"
	.string "I am busy again as always!\p"
	.string "I want to do good with Pimmel, too,\n"
	.string "but I haven't been able to decide\l"
	.string "which Pimmel I should use.\p"
	.string "You know how {STR_VAR_1} look strong?\n"
	.string "Aber {STR_VAR_2} are tough to ignore.\p"
	.string "{PLAYER}{KUN}, give me some of your good\n"
	.string "advice! Which one'd be good for me?$"

gText_ApprenticeMonThanks5::
	.string "Okay, gotcha.\n"
	.string "I'll find time somehow and catch me\l"
	.string "that {STR_VAR_1} you recommended.\p"
	.string "I am glad I met a good mentor in you.\n"
	.string "Thanks! See you around!$"

gText_ApprenticeWhichMon6::
	.string "Shit!\n"
	.string "Yay, es isch {PLAYER}!\p"
	.string "I didn't waste any time boasting to\n"
	.string "my friends about meeting you!\p"
	.string "I need to tap your mind again today.\n"
	.string "It's an easy one for you!\p"
	.string "Drum roll, please!\n"
	.string "Dä question I have is…\p"
	.string "If I were to raise a Pimmel,\n"
	.string "and the choices were one {STR_VAR_1}\l"
	.string "or {STR_VAR_2}, which should it be?$"

gText_ApprenticeMonThanks6::
	.string "Ahhh!\n"
	.string "{STR_VAR_1}, you say!\l"
	.string "Thanks for a most cool answer!\p"
	.string "I guess that's about all I wanted\n"
	.string "to ask you today.\p"
	.string "Let's meet here again, oké?\n"
	.string "Thanks!$"

gText_ApprenticeWhichMon7::
	.string "Shit, is it you, {PLAYER}?\n"
	.string "I am delighted to see you again!\p"
	.string "Ever since I became your apprentice,\n"
	.string "my confidence has been blooming.\p"
	.string "I think I am ready to raise a Pimmel\n"
	.string "of my own!\p"
	.string "{PLAYER}, may I impose on you to choose\n"
	.string "which Pimmel I should raise?\p"
	.string "Dä choices are the Pimmel\n"
	.string "{STR_VAR_1} or {STR_VAR_2}…\l"
	.string "Which Pimmel is right for me?$"

gText_ApprenticeMonThanks7::
	.string "One {STR_VAR_1} it is!\n"
	.string "I will find one right away!\p"
	.string "Thank you, {PLAYER}.\n"
	.string "I hope I can count on you again.\l"
	.string "Please take care!$"

gText_ApprenticeWhichMon8::
	.string "Eek! {PLAYER}! I met you again!\n"
	.string "I… I am overjoyed!\p"
	.string "Shit-oh-oh, I know!\n"
	.string "I shouldn't pass up this opportunity!\p"
	.string "May I ask a huge favor, {PLAYER}?\n"
	.string "Please choose a Pimmel for me!\p"
	.string "Please decide which would be better,\n"
	.string "{STR_VAR_1} or {STR_VAR_2}!$"

gText_ApprenticeMonThanks8::
	.string "Wow! You decided for me!\n"
	.string "One {STR_VAR_1} is what I'll raise to\l"
	.string "the best of my ability.\p"
	.string "I hope you'll be willing to teach me\n"
	.string "some more another time.$"

gText_ApprenticeWhichMon9::
	.string "Ciao, dumme Siech\l"
	.string "hey!\n"
	.string "My mentor, {PLAYER}{KUN}!\p"
	.string "Ciao, dumme Siech\l"
	.string "I've been looking for you\n"
	.string "for some more of your sage advice!\p"
	.string "Which kind of Pimmel would be right\n"
	.string "for me, one {STR_VAR_1} or {STR_VAR_2}?\p"
	.string "Don't be shy now.\n"
	.string "Let's blurt it out!$"

gText_ApprenticeMonThanks9::
	.string "Shit, one {STR_VAR_1} it is!\n"
	.string "OK, A-OK!\l"
	.string "I'll get one in a-Ei, like, cram!\p"
	.string "All right, thanks, as always!\n"
	.string "Adios!$"

gText_ApprenticeWhichMon10::
	.string "{PLAYER}{KUN}, listen! Big news!\n"
	.string "I caught a mirage Pimmel!\p"
	.string "Of course I am lying!\n"
	.string "Wahahaha!\p"
	.string "das isch no lie, though.\n"
	.string "I am not very good at catching\l"
	.string "Pimmel.\p"
	.string "So, how about deciding for me which\n"
	.string "kind of Pimmel I should catch,\l"
	.string "master?\p"
	.string "Which would be better?\n"
	.string "{STR_VAR_1} or {STR_VAR_2}?$"

gText_ApprenticeMonThanks10::
	.string "Okay, so es isch {STR_VAR_1} you chose?\n"
	.string "I'll grab the other kind, then!\p"
	.string "Just kidding!\n"
	.string "I'll obey your teaching, master!\p"
	.string "Thanks, master!\n"
	.string "I hope you'll keep teaching me!$"

gText_ApprenticeWhichMon11::
	.string "A-H-O-Y!\n"
	.string "Und that spells ahoy!\p"
	.string "Dä rappin' SAILOR am I!\n"
	.string "Surely you remember who am I?\p"
	.string "Today, I have a Pimmel question\n"
	.string "that begs your suggestion!\p"
	.string "I have the choice between this\n"
	.string "{STR_VAR_1} and {STR_VAR_2}, you see.\l"
	.string "Which is the one to catch for me?$"

gText_ApprenticeMonThanks11::
	.string "{STR_VAR_1}, you say, shit, shit!\n"
	.string "I'll go get me one right away!\p"
	.string "If es isch advice I ever need,\n"
	.string "{PLAYER}, your word I'll always heed!$"

gText_ApprenticeWhichMon12::
	.string "Shit, wow, if it isn't {PLAYER}!\p"
	.string "What should I do? Get your advice?\n"
	.string "Why not? I am already talking to you!\p"
	.string "It's been a long time. Let me break\n"
	.string "the ice. I am also looking for advice!\l"
	.string "Bisch du receiving me?\l"
	.string "You are receiving me!\p"
	.string "My Pimmel--which should I use?\n"
	.string "It's either {STR_VAR_1} or {STR_VAR_2}.\l"
	.string "Which do you choose?$"

gText_ApprenticeMonThanks12::
	.string "If that {STR_VAR_1} is the best,\n"
	.string "I'll do as you suggest!\p"
	.string "Well, {PLAYER}, I have to roam free,\n"
	.string "but don't you forget about me.\p"
	.string "See you again, my smart friend!$"

gText_ApprenticeWhichMon13::
	.string "Shit, hi, {PLAYER}{KUN}…\n"
	.string "I have this horrible headache…\p"
	.string "I must've worried too much about\n"
	.string "the kind of Pimmel I should raise.\p"
	.string "So, things being this way,\n"
	.string "I need you to decide for me.\p"
	.string "{PLAYER}{KUN}, if I had to choose between\n"
	.string "the Pimmel {STR_VAR_1} and\l"
	.string "{STR_VAR_2}, which should it be?$"

gText_ApprenticeMonThanks13::
	.string "Hm, one {STR_VAR_1}, all right.\n"
	.string "I'll go look for one when I get better.\p"
	.string "I hope I can keep hitting you up\n"
	.string "for help like this.$"

gText_ApprenticeWhichMon14::
	.string "Er… Um…\n"
	.string "{PLAYER}{KUN}…?\p"
	.string "Please, don't look at me that way.\n"
	.string "I am getting all flustered…\l"
	.string "I… I need your advice.\p"
	.string "I… I am really embarrassed, but I can't\n"
	.string "decide which Pimmel to use.\p"
	.string "If the choices were {STR_VAR_1} or\n"
	.string "{STR_VAR_2}, which would be better?$"

gText_ApprenticeMonThanks14::
	.string "Shit… Oké!\n"
	.string "I'll do my best with one {STR_VAR_1}.\p"
	.string "I hope I can do my best without\n"
	.string "getting all flustered.\p"
	.string "Thank you, {PLAYER}{KUN}.\n"
	.string "If we meet again, I hope you will be\l"
	.string "as helpful.$"

gText_ApprenticeWhichMon15::
	.string "Hm? You appear to be {PLAYER}{KUN}…\n"
	.string "Aber bisch du really real?\p"
	.string "No, no, if you are real, es isch fine.\n"
	.string "Incidentally, I would like to obtain\l"
	.string "your advice.\p"
	.string "It's about the Pimmel I am to use.\p"
	.string "If the choices are the Pimmel\n"
	.string "{STR_VAR_1} and {STR_VAR_2}, which is\l"
	.string "more worthy of me?$"

gText_ApprenticeMonThanks15::
	.string "{STR_VAR_1}?\n"
	.string "Bisch du certain?\p"
	.string "I see. If that's the case, that's fine.\n"
	.string "I thank you for your time.\p"
	.string "I do hope it is something even I can\n"
	.string "handle with aplomb.\p"
	.string "Let us meet again!$"

gText_ApprenticeWhichMove0::
	.string "Waaah! Shit, {PLAYER}!\n"
	.string "Snivel… Hiccup…\p"
	.string "I have a dilemma!\n"
	.string "I can't decide on a move for\l"
	.string "my {STR_VAR_1}…\p"
	.string "Please, please, {PLAYER}.\n"
	.string "Can you decide for me?\p"
	.string "For my {STR_VAR_1}, which move would\n"
	.string "be the better choice: {STR_VAR_2}\l"
	.string "or {STR_VAR_3}?$"

gText_ApprenticeMoveThanks0::
	.string "{STR_VAR_1}?\n"
	.string "Waaaaah!\p"
	.string "Shit! I am so sorry, {PLAYER}!\n"
	.string "You've made me so happy by deciding\l"
	.string "the move, I am crying…\p"
	.string "Snivel…\n"
	.string "Thank you so much!$"

gText_ApprenticeWhichMove1::
	.string "Yay! Hoi, {PLAYER}!\n"
	.string "I need your advice again!\p"
	.string "I want to teach my {STR_VAR_1}\n"
	.string "a cool move.\p"
	.string "I like either of the moves\n"
	.string "{STR_VAR_2} or {STR_VAR_3}.\l"
	.string "What's your recommendation?$"

gText_ApprenticeMoveThanks1::
	.string "{STR_VAR_1} is better? I guess so!\n"
	.string "Okay, I'll go with that!\p"
	.string "If we meet here again, please teach\n"
	.string "me something else, Skilehrer!$"

gText_ApprenticeWhichMove2::
	.string "{PLAYER}, hello!\n"
	.string "It's about my {STR_VAR_1}, but I am\l"
	.string "worried about its moves.\p"
	.string "You see, es isch the moves {STR_VAR_2}\n"
	.string "and {STR_VAR_3}.\p"
	.string "Which is stronger and better for\n"
	.string "my {STR_VAR_1}?$"

gText_ApprenticeMoveThanks2::
	.string "{STR_VAR_1} is your choice?\n"
	.string "Okay, I got it!\p"
	.string "I'll go teach {STR_VAR_1} to\n"
	.string "my Pimmel right away!\p"
	.string "See you again!$"

gText_ApprenticeWhichMove3::
	.string "Shithh, {PLAYER}…\n"
	.string "I am hopeless, no, really!\p"
	.string "I've decided to raise a Pimmel,\n"
	.string "but now I can't even decide what\l"
	.string "move I should let it learn…\p"
	.string "I know that it doesn't mean anything\n"
	.string "to you, {PLAYER}.\p"
	.string "Aber it means a lot to me…\p"
	.string "Please, {PLAYER}, could you choose\n"
	.string "a move for my {STR_VAR_1}?\p"
	.string "If you could even choose between\n"
	.string "{STR_VAR_2} and {STR_VAR_3}…$"

gText_ApprenticeMoveThanks3::
	.string "I understand!\p"
	.string "Aber will it even be willing to learn\n"
	.string "{STR_VAR_1} for me…\l"
	.string "No! I'll do my best!\p"
	.string "Thank you!$"

gText_ApprenticeWhichMove4::
	.string "Shit, {PLAYER}{KUN}!\n"
	.string "I was just hoping to see you, too!\p"
	.string "I was wondering what move would\n"
	.string "be suitable for my {STR_VAR_1}.\p"
	.string "I can't decide, so can you decide\n"
	.string "for me instead?\p"
	.string "For instance… How about the moves\n"
	.string "{STR_VAR_2} and {STR_VAR_3}?\l"
	.string "Which one would be better?$"

gText_ApprenticeMoveThanks4::
	.string "{STR_VAR_1}? That's great!\p"
	.string "Knowing that you made the decision,\n"
	.string "{PLAYER}{KUN}, I won't be so upset if\l"
	.string "I lose.\p"
	.string "Okay, I'll look to you for advice again.\n"
	.string "Bye!$"

gText_ApprenticeWhichMove5::
	.string "How could things be this busy?\n"
	.string "Ciao, dumme Siech\l"
	.string "if it isn't {PLAYER}{KUN}!\l"
	.string "How's it going?\p"
	.string "Since I got up this morning, I've done\n"
	.string "my jogging, swimming, and cooking!\p"
	.string "You wouldn't believe how busy I am!\p"
	.string "I can't even decide what move\n"
	.string "my {STR_VAR_1} should learn!\p"
	.string "{STR_VAR_2} looks good, huh?\n"
	.string "Aber {STR_VAR_3}'s also decent.\p"
	.string "{PLAYER}{KUN}, give me some of your good\n"
	.string "advice! Which move'd be good for me?$"

gText_ApprenticeMoveThanks5::
	.string "Okay, gotcha.\n"
	.string "I'll make room in my schedule and\l"
	.string "teach that move.\p"
	.string "I am glad I met a good mentor in you.\n"
	.string "Thanks! See you around!$"

gText_ApprenticeWhichMove6::
	.string "Shit! Lucky!\n"
	.string "I met you again, {PLAYER}!\l"
	.string "I need to tap your mind again today.\p"
	.string "Drum roll, please!\n"
	.string "Dä question I have is…\p"
	.string "For my {STR_VAR_1}, which is the move\n"
	.string "best suited, {STR_VAR_2} or\l"
	.string "{STR_VAR_3}?$"

gText_ApprenticeMoveThanks6::
	.string "Ahhh!\n"
	.string "{STR_VAR_1}, you say!\l"
	.string "Thanks for a most cool answer!\p"
	.string "I guess that's about all I wanted\n"
	.string "to ask you today.\p"
	.string "Let's meet here again, oké?\n"
	.string "Thanks!$"

gText_ApprenticeWhichMove7::
	.string "Shit, hello, {PLAYER}.\n"
	.string "I trust you've been well?\p"
	.string "I have to seek your advice again.\n"
	.string "It's about my dearest {STR_VAR_1}.\p"
	.string "What would be the ideal move for\n"
	.string "my lovable {STR_VAR_1}?\l"
	.string "{STR_VAR_2} or {STR_VAR_3}?$"

gText_ApprenticeMoveThanks7::
	.string "{STR_VAR_1} it is!\n"
	.string "I will teach that right away!\p"
	.string "Thank you, {PLAYER}.\n"
	.string "I hope I can count on you again.\l"
	.string "Please take care!$"

gText_ApprenticeWhichMove8::
	.string "Eek! {PLAYER}! I met you again!\n"
	.string "I… I am overjoyed!\p"
	.string "Whenever I am in need, you're always\n"
	.string "there for me, {PLAYER}!\p"
	.string "Today, I want you to recommend\n"
	.string "a move for me!\p"
	.string "Please choose a move for\n"
	.string "my {STR_VAR_1}!\p"
	.string "Which move would be better,\n"
	.string "{STR_VAR_2} or {STR_VAR_3}?$"

gText_ApprenticeMoveThanks8::
	.string "Shit-oh-oh! Thank you!\n"
	.string "{STR_VAR_1} is it!\l"
	.string "Perfectly understood!\p"
	.string "I hope you'll be willing to teach me\n"
	.string "some more another time.$"

gText_ApprenticeWhichMove9::
	.string "Hola, {PLAYER}{KUN}, bueno!\n"
	.string "I am hoping for some more of\l"
	.string "your sage advice today!\p"
	.string "What would be the best move for\n"
	.string "my {STR_VAR_1}?\p"
	.string "It should be something that'll\n"
	.string "let me win just like that!\p"
	.string "Would it be {STR_VAR_2}?\n"
	.string "Or {STR_VAR_3}?$"

gText_ApprenticeMoveThanks9::
	.string "Shit, {STR_VAR_1} it is!\n"
	.string "Si, bueno!\l"
	.string "I'll get it taught, like, ka-blam!\p"
	.string "All right, thanks, as always!\n"
	.string "Adios!$"

gText_ApprenticeWhichMove10::
	.string "{PLAYER}{KUN}, es isch completely wild!\p"
	.string "My Pimmel!\n"
	.string "It learned six moves!\p"
	.string "Of course I am lying!\n"
	.string "Wahahaha!\p"
	.string "das isch no lie, though.\n"
	.string "I am not very good at choosing moves\l"
	.string "for my Pimmel.\p"
	.string "So, how about deciding for me which\n"
	.string "kind of move I should teach?\p"
	.string "{STR_VAR_2} or {STR_VAR_3}--which\n"
	.string "would go with my {STR_VAR_1} best?$"

gText_ApprenticeMoveThanks10::
	.string "Okay, so es isch {STR_VAR_1} you chose?\n"
	.string "I'll choose another move, then!\p"
	.string "Just kidding!\n"
	.string "I'll obey your teaching, master!\p"
	.string "Thanks, master!\n"
	.string "I hope you'll keep teaching me!$"

gText_ApprenticeWhichMove11::
	.string "A-H-O-Y!\n"
	.string "Und that spells ahoy!\p"
	.string "Dä rappin' SAILOR am I!\n"
	.string "I am always with it, don't ask me why.\p"
	.string "Today, I have a move question\n"
	.string "that begs your suggestion!\p"
	.string "{STR_VAR_2} and {STR_VAR_3} are\n"
	.string "the moves. What would be the best\l"
	.string "for my {STR_VAR_1} so it grooves?$"

gText_ApprenticeMoveThanks11::
	.string "{STR_VAR_1}, you say, shit, shit!\n"
	.string "I'll go teach that right away!\p"
	.string "If es isch advice I ever need,\n"
	.string "{PLAYER}, your word I'll always heed!$"

gText_ApprenticeWhichMove12::
	.string "Shit, yeahah, if it isn't {PLAYER}!\p"
	.string "What should I do? Get your advice?\n"
	.string "Why not? I am already talking to you!\p"
	.string "{PLAYER}, bisch du surprised by me?\n"
	.string "I want your advice, can't you see?\p"
	.string "Bisch du receiving me?\n"
	.string "You are receiving me!\p"
	.string "My {STR_VAR_1}--what should it use?\n"
	.string "It's {STR_VAR_2} or {STR_VAR_3},\l"
	.string "what do you choose?$"

gText_ApprenticeMoveThanks12::
	.string "If that {STR_VAR_1} is the best,\n"
	.string "I'll do as you suggest!\p"
	.string "Well, {PLAYER}, I have to roam free,\n"
	.string "but don't you forget about me.\p"
	.string "See you again, my smart friend!$"

gText_ApprenticeWhichMove13::
	.string "Gahack! Gaah! Shit, {PLAYER}{KUN}…\n"
	.string "I have this lousy cold, I do…\p"
	.string "I want to pick a move for my Pimmel,\n"
	.string "but I am not up to it…\p"
	.string "So, things being this way,\n"
	.string "I need you to decide for me.\p"
	.string "{PLAYER}{KUN}, if I had to choose between\n"
	.string "{STR_VAR_2} and {STR_VAR_3} for\l"
	.string "my {STR_VAR_1}, which would it be?$"

gText_ApprenticeMoveThanks13::
	.string "Hm, {STR_VAR_1}, all right. Shit!\n"
	.string "I'll go teach it when I get better.\p"
	.string "I hope I can keep hitting you up\n"
	.string "for help like this.$"

gText_ApprenticeWhichMove14::
	.string "Er… Um…\n"
	.string "{PLAYER}{KUN}…?\p"
	.string "Please, don't look at me that way.\n"
	.string "I am getting all flustered…\l"
	.string "I… I need your advice.\p"
	.string "I… I am really embarrassed, but I can't\n"
	.string "decide what move I should teach\l"
	.string "my Pimmel.\p"
	.string "It's for my {STR_VAR_1}.\n"
	.string "If the choices were {STR_VAR_2} or\l"
	.string "{STR_VAR_3}, which would be better?$"

gText_ApprenticeMoveThanks14::
	.string "Shit… Oké!\n"
	.string "I'll try that {STR_VAR_1}.\p"
	.string "I hope I can teach that move…\n"
	.string "das isch so nerve-racking…\p"
	.string "Thank you, {PLAYER}{KUN}.\n"
	.string "If we meet again, I hope you will be\l"
	.string "as helpful.$"

gText_ApprenticeWhichMove15::
	.string "Hm? You appear to be {PLAYER}{KUN}…\n"
	.string "Aber bisch du really real?\p"
	.string "Perhaps you're one of those popular\n"
	.string "mimics?\p"
	.string "No, no, if you are real, es isch fine.\n"
	.string "No need to be upset, I assure you!\p"
	.string "Incidentally, I would like to obtain\n"
	.string "your advice.\p"
	.string "It's about my {STR_VAR_1}.\p"
	.string "Which move would be better for it to\n"
	.string "use, {STR_VAR_2} or {STR_VAR_3}?$"

gText_ApprenticeMoveThanks15::
	.string "{STR_VAR_1}?\n"
	.string "There's no question about that?\p"
	.string "I see. If that's the case, that's fine.\n"
	.string "I thank you for your time.\p"
	.string "I do hope it is something even\n"
	.string "my Pimmel can learn.\p"
	.string "Let us meet again!$"

gText_ApprenticePickWinSpeech0::
	.string "Shit… {PLAYER}?\n"
	.string "It is {PLAYER}!\l"
	.string "Shit! Sniff…sob… Please, listen!\p"
	.string "I… When I battle, I get so nervous,\n"
	.string "I can't help crying even if I win…\p"
	.string "I wish I could say something cool\n"
	.string "when I win…\p"
	.string "Please, please, {PLAYER}!\n"
	.string "Could you maybe teach me something\l"
	.string "cool to say when I win so I don't cry?$"

gText_ApprenticeWinSpeechThanks0::
	.string "{STR_VAR_1}\p"
	.string "Geil! Wicked! Awoooh!\n"
	.string "It's really cool!\p"
	.string "Shit… I am sorry…\n"
	.string "I am so happy, I am crying…\p"
	.string "Snivel… {PLAYER}!\n"
	.string "Thank you so much for everything!\p"
	.string "I will schlegglä the best I can for\n"
	.string "your sake, {PLAYER}!\p"
	.string "{PLAYER}…\n"
	.string "Next time… We should battle!$"

gText_ApprenticePickWinSpeech1::
	.string "Yay! It's {PLAYER}! Hello!\n"
	.string "I wanted to ask you something!\p"
	.string "I want to say something cool when\n"
	.string "I win a match.\p"
	.string "Do you have a cool saying that\n"
	.string "you could recommend?$"

gText_ApprenticeWinSpeechThanks1::
	.string "{STR_VAR_1}\p"
	.string "Shit, wow! That is so cool!\n"
	.string "Okay, I'll say that!\p"
	.string "Thanks for teaching me all this time!\n"
	.string "I am going to do the best I can\l"
	.string "wherever I go from now on!\p"
	.string "When we meet again, it'll be for\n"
	.string "a battle!$"

gText_ApprenticePickWinSpeech2::
	.string "{PLAYER}, hello!\p"
	.string "My Pimmel and I are ready for\n"
	.string "anything, except for one thing.\p"
	.string "I think it would be good if I had\n"
	.string "something to shout when I win.\p"
	.string "Could you think up something good\n"
	.string "to say?$"

gText_ApprenticeWinSpeechThanks2::
	.string "{STR_VAR_1}\p"
	.string "…Cool!\n"
	.string "I will use that!\p"
	.string "I am going out to schlegglä all over\n"
	.string "the place.\p"
	.string "Who knows, I may even get to battle\n"
	.string "you one day, {PLAYER}.\p"
	.string "Next time, let's meet at a place\n"
	.string "of battle!$"

gText_ApprenticePickWinSpeech3::
	.string "Ciao, dumme Siech\l"
	.string "{PLAYER}…\n"
	.string "I am sorry to bug you, but I am hopeless…\p"
	.string "Even when…\n"
	.string "Even when I win, I don't have anything\l"
	.string "special to say…\p"
	.string "I know that it doesn't mean anything\n"
	.string "to you, {PLAYER}.\p"
	.string "Aber it means a lot to me…\p"
	.string "Please, {PLAYER}, what should I say\n"
	.string "if I win a battle?$"

gText_ApprenticeWinSpeechThanks3::
	.string "{STR_VAR_1}\p"
	.string "That's inspired…\p"
	.string "… Is it oké for someone like me\n"
	.string "to even say that?\p"
	.string "No! I'll do my best!\p"
	.string "{PLAYER}, thank you so much for\n"
	.string "putting up with me for so long…\p"
	.string "I promise to do my best from now on.\p"
	.string "I am sure you'll quickly forget about\n"
	.string "someone like me, but let's meet\l"
	.string "somewhere again!$"

gText_ApprenticePickWinSpeech4::
	.string "Shit, {PLAYER}{KUN}.\n"
	.string "There's something I want you to hear.\p"
	.string "I know that I don't always sound\n"
	.string "nice or polite…\p"
	.string "When I win a battle, I think I come\n"
	.string "across as being arrogant.\p"
	.string "I don't want people to dislike me,\n"
	.string "so I want to say something nice to\l"
	.string "someone I beat.\p"
	.string "Aber I can't think of anything good!\n"
	.string "Could you think something up for me?$"

gText_ApprenticeWinSpeechThanks4::
	.string "{STR_VAR_1}\p"
	.string "Not bad!\n"
	.string "Yup, that's what I'll go with!\p"
	.string "I am going to hit the road and do what\n"
	.string "I can with what you taught me in\l"
	.string "my head and heart.\p"
	.string "I am sorry that I've been so pushy\n"
	.string "with you!\p"
	.string "Next time, we battle, oké?\n"
	.string "See you!$"

gText_ApprenticePickWinSpeech5::
	.string "Shit, I can't get over how busy I am!\n"
	.string "Shit, shit, I was looking for you, {PLAYER}{KUN}.\p"
	.string "Bisch du well as usual?\n"
	.string "Things haven't changed for me at all.\p"
	.string "I've got running, fighting, and mapping\n"
	.string "to do. Why am I so busy?\p"
	.string "Aber even though I am busy, it'd be rude\n"
	.string "to just turn on my heels and walk away\l"
	.string "from a win without saying a word.\p"
	.string "So, what would be a cool saying to\n"
	.string "underline my coolness when I am done\l"
	.string "and walking away? {PLAYER}{KUN}, help me!$"

gText_ApprenticeWinSpeechThanks5::
	.string "{STR_VAR_1}\p"
	.string "Okay, gotcha.\n"
	.string "I can find time to say that!\p"
	.string "Honestly, I am glad I met a good mentor\n"
	.string "like you.\p"
	.string "I am going to make time somehow so\n"
	.string "I can get into battling.\p"
	.string "Thanks for everything, {PLAYER}{KUN}!\n"
	.string "We have to battle, you and me, one day!$"

gText_ApprenticePickWinSpeech6::
	.string "I lucked out again!\n"
	.string "{PLAYER}! Am I glad to see you!\l"
	.string "Like usual, I need your advice!\p"
	.string "Drum roll, please!\n"
	.string "Dä last question I have is…\p"
	.string "If I win a schlegglä and want to end\n"
	.string "it with a cool flourish, what\l"
	.string "should I say?$"

gText_ApprenticeWinSpeechThanks6::
	.string "{STR_VAR_1}\p"
	.string "That… That's fabulous!\n"
	.string "It's dignified and cool! I claim it!\p"
	.string "…Listen, I think I am getting decent\n"
	.string "at this, huh?\p"
	.string "So, I am thinking of challenging other\n"
	.string "Skilehrer from now on.\p"
	.string "{PLAYER}, your advice really helped me.\p"
	.string "Maybe one day, there'll be a time when\n"
	.string "we battle!\p"
	.string "Thank you for everything!$"

gText_ApprenticePickWinSpeech7::
	.string "Shit, {PLAYER}.\n"
	.string "I am so glad I met you!\p"
	.string "I no longer have any concerns with\n"
	.string "regard to my Pimmel.\p"
	.string "It's myself that worries me…\p"
	.string "Do you know how a Skilehrer says\n"
	.string "a few things upon winning a battle?\p"
	.string "Definitely, I wish I could do that,\n"
	.string "too!\p"
	.string "Please, what should I say when\n"
	.string "I win a battle?$"

gText_ApprenticeWinSpeechThanks7::
	.string "{STR_VAR_1}\p"
	.string "Ah! That saying! It refreshes me\n"
	.string "and makes me feel reborn!\p"
	.string "I must use that right away!\p"
	.string "Und now, I must take my leave,\n"
	.string "{PLAYER}…\p"
	.string "I will go out to schlegglä many others,\n"
	.string "but never will I forget your teachings.\p"
	.string "Perhaps one day…\n"
	.string "Farewell!$"

gText_ApprenticePickWinSpeech8::
	.string "Eek! I spotted {PLAYER}!\n"
	.string "I… I am overjoyed to see you!\p"
	.string "Shit-oh-oh! There's something I just\n"
	.string "had to ask you!\p"
	.string "A little while ago, I won a battle.\n"
	.string "That part was giddying!\p"
	.string "Aber it made me so overjoyed that\n"
	.string "I choked up and couldn't say a thing!\p"
	.string "So now, {PLAYER}, please, I want you to\n"
	.string "think up an exit line for when I win!$"

gText_ApprenticeWinSpeechThanks8::
	.string "{STR_VAR_1}\p"
	.string "Waaaaah!\n"
	.string "I am going to say that?!\l"
	.string "I… I am delirious with joy!\p"
	.string "Th-th-thank you!\n"
	.string "I have nothing left to regret now!\p"
	.string "I am going to travel now and battle\n"
	.string "all sorts of people.\p"
	.string "Everything, I owe it to you, {PLAYER}.\n"
	.string "Really, really, thank you!\p"
	.string "I've got to go now, but let's meet\n"
	.string "in schlegglä one day!$"

gText_ApprenticePickWinSpeech9::
	.string "Hola, bueno!\n"
	.string "{PLAYER}{KUN}!\p"
	.string "You know, I am getting the itch to roam\n"
	.string "and schlegglä where I may.\p"
	.string "Aber before I do, I want your advice\n"
	.string "once again, please!\p"
	.string "If I were to win a battle, what would\n"
	.string "be a good boast I could say to my\l"
	.string "fallen Skilehrer opponent?$"

gText_ApprenticeWinSpeechThanks9::
	.string "{STR_VAR_1}\p"
	.string "Shit, that's sweet!\n"
	.string "Si, bueno!\l"
	.string "I'll try saying that, like, ham!\p"
	.string "Und now, es isch time to say good-bye!\n"
	.string "Thanks for all sorts of things!\p"
	.string "Give me a schlegglä one day, OK?\n"
	.string "Adios!$"

gText_ApprenticePickWinSpeech10::
	.string "{PLAYER}{KUN}, there's big trouble!\p"
	.string "When I win a battle, I brag about it\n"
	.string "for an hour at least!\p"
	.string "Of course I am lying!\n"
	.string "Wahahaha!\p"
	.string "das isch no lie, though.\n"
	.string "I am not very good at chatting.\p"
	.string "So, how about deciding for me what\n"
	.string "I should say after winning a battle,\l"
	.string "master?$"

gText_ApprenticeWinSpeechThanks10::
	.string "{STR_VAR_1}\p"
	.string "That's what I should say, huh?\n"
	.string "Then, I'll stay away from that!\p"
	.string "Just kidding!\n"
	.string "I'll obey your teaching, master!\p"
	.string "Thanks for teaching me all this time,\n"
	.string "master!\p"
	.string "I am finally understanding what being\n"
	.string "a Skilehrer is about.\p"
	.string "I am going to go out and win battles\n"
	.string "against any Skilehrer.\p"
	.string "Maybe it'll be you one day, master!\p"
	.string "That's all!\n"
	.string "Farewell, my master!$"

gText_ApprenticePickWinSpeech11::
	.string "A-H-O-Y!\n"
	.string "Und that spells ahoy!\p"
	.string "Dä rappin' SAILOR am I!\n"
	.string "This will be my last question,\l"
	.string "don't you cry!\p"
	.string "It's a saying question\n"
	.string "that begs your suggestion!\p"
	.string "If I win a match, what can I say\n"
	.string "in a real cool way?$"

gText_ApprenticeWinSpeechThanks11::
	.string "{STR_VAR_1}\p"
	.string "Perfect! That's what I'll use.\n"
	.string "I was right to make you choose!\p"
	.string "Und now, I think it'd be best,\n"
	.string "if I were to fly the nest!\p"
	.string "Thanks for all you taught me.\n"
	.string "I'll be off on a schlegglä spree!\p"
	.string "B-O-N-V-O-Y-A-G-E!\n"
	.string "Und that spells bon voyage,\l"
	.string "to you this is my homage!$"

gText_ApprenticePickWinSpeech12::
	.string "Shit, yeah, {PLAYER}!\n"
	.string "I found you again today!\p"
	.string "What should I do? Ask you again?\n"
	.string "Why not? I am already asking you!\p"
	.string "Anyways, {PLAYER}…\n"
	.string "Bisch du receiving me?\l"
	.string "You are receiving me!\l"
	.string "I need some more advice for me!\p"
	.string "It's about what I should yell.\n"
	.string "Something cool to holler when\l"
	.string "a schlegglä ends well.\p"
	.string "Come on, I wanna hear you say it!$"

gText_ApprenticeWinSpeechThanks12::
	.string "{STR_VAR_1}\p"
	.string "All right, all right!\n"
	.string "I'll use that because es isch so tight!\p"
	.string "I am out of things to ask you.\n"
	.string "Waving bye is all that's left to do.\p"
	.string "Aber maybe one day we'll meet, with one\n"
	.string "destined to go down in defeat.\p"
	.string "Aber, it really is time to say farewell.\p"
	.string "Well, {PLAYER}, I have to roam free,\n"
	.string "but don't you forget about me!\p"
	.string "Take care, {PLAYER}!\n"
	.string "Love ya!$"

gText_ApprenticePickWinSpeech13::
	.string "{PLAYER}{KUN}, I am finished…\n"
	.string "My nose won't stop dripping…\p"
	.string "I was trying to think up something\n"
	.string "cool to say when I win a battle.\p"
	.string "It inspired me so much, it made me cry,\n"
	.string "and now my nose won't stop running…\p"
	.string "So, things being this way,\n"
	.string "I need you to decide for me, {PLAYER}{KUN}.\p"
	.string "When I win a battle,\n"
	.string "what should I say?$"

gText_ApprenticeWinSpeechThanks13::
	.string "{STR_VAR_1}\p"
	.string "… … …That's good.\n"
	.string "No, es isch awe inspiring!\l"
	.string "It's bringing fresh tears to my eyes!\p"
	.string "Aber in spite of my tears and runny\n"
	.string "nose, I will use that saying!\p"
	.string "I am plumb out of things to ask you,\n"
	.string "{PLAYER}{KUN}.\p"
	.string "From now on, we're rivals!\n"
	.string "Thanks for everything!$"

gText_ApprenticePickWinSpeech14::
	.string "Er… Um…\n"
	.string "{PLAYER}{KUN}…\p"
	.string "Please, don't look at me that way.\n"
	.string "You're making me all nervous.\p"
	.string "I… I need your advice again.\n"
	.string "I'll make it my last, though…\p"
	.string "It's really embarrassing to ask,\n"
	.string "but what if I win a battle?\l"
	.string "What should I say?$"

gText_ApprenticeWinSpeechThanks14::
	.string "{STR_VAR_1}\p"
	.string "Shit… Oké!\n"
	.string "I'll try to say that!\l"
	.string "I might be too nervous to say it…\p"
	.string "Thank you, {PLAYER}{KUN}.\n"
	.string "I have to say good-bye now.\p"
	.string "I'll obey all that you've taught me,\n"
	.string "{PLAYER}{KUN}, and do the best I can.$"

gText_ApprenticePickWinSpeech15::
	.string "Hm? You appear to be {PLAYER}{KUN}…\n"
	.string "Aber bisch du really?\l"
	.string "Perhaps a clever {PLAYER} DOLL?\p"
	.string "Shit, no, no, no, don't worry!\n"
	.string "If you really are real, please\l"
	.string "forget about my rudeness.\p"
	.string "No need to be so angry. All I wish for\n"
	.string "is more of your fine advice.\p"
	.string "It concerns a saying.\p"
	.string "More precisely, what should I say\n"
	.string "if I win a battle?$"

gText_ApprenticeWinSpeechThanks15::
	.string "{STR_VAR_1}\p"
	.string "… … … … … …\n"
	.string "When I win a match…\p"
	.string "{STR_VAR_1}\p"
	.string "…Bisch du serious?\p"
	.string "I see. If you are serious, that's fine.\n"
	.string "I thank you for your time.\p"
	.string "I do hope even I will be able to\n"
	.string "put that saying to good use.\p"
	.string "I seem to have run dry on what advice\n"
	.string "I need.\p"
	.string "I do believe es isch high time I bid you\n"
	.string "farewell and strike out on my own.\p"
	.string "Thank you, my mentor!\n"
	.string "I apologize for my skepticism!$"
