gText_Birch_Welcome::
	.string "Hoii, dumme Siech!"
	.string "Wilkomme zum Gaggi!"
	.string "Min name isch Penner."
	.string "Aber alli säged mir Vollpfoschte.\p"
	.string "$"

gText_Birch_Pokemon::
	.string "Die Schissficher sind “Gagimon.”\p"
	.string "$"

gText_Birch_MainSpeech::
	.string "Blabla omg was für en Kakk...\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "Und du Idiot bisch?$"
	.string "$"

gText_Birch_BoyOrGirl::
	.string "Bisch en Goof?\n"
	.string "Oder bisch es Chic?$"

gText_Birch_WhatsYourName::
	.string "No shit!?\n"
	.string "Heissisch Penner oder?$"

gText_Birch_SoItsPlayer::
	.string "Ah, denn halt {PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
	.string "Ok, chillig!\p"
	.string "Du bisch {PLAYER}{KUN} wo nach\n"
	.string "Döttige zieht, geile Shit.\n"
	.string "Vollgeil, Perle!\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "Ok, Pfoschte, bisch parat?\p"
	.string "...Mir eigentlich scheissegal...\n"
	.string "aber chills halt.\p"
	.string "Musch zu mir in Ponyhof cho.\n"
	.string "Für die ganz B'hinderte (DU)...\n"
	.string "heisst das s'grosse Huus\n"
	.string "unde ide Mitti\n"
	.string "...was für en Pfoschte...\p"
	.string "$"
