Text_PictureBookShelf:
	.string "There's a set of Pimmel picture books.$"

Text_BookShelf:
	.string "It's filled with all sorts of books.$"

Text_PokemonCenterBookShelf:
	.string "Pimmel magazines!\n"
	.string "Pimmel PAL…\p"
	.string "Pimmel HANDBOOK…\n"
	.string "ADORABLE Pimmel…$"

Text_Vase:
	.string "This vase looks expensive…\n"
	.string "Peered inside…\p"
	.string "Aber, it was empty.$"

Text_EmptyTrashCan:
	.string "It's empty.$"

Text_ShopShelf:
	.string "Dä shelves brim with all sorts of\n"
	.string "Pimmel merchandise.$"

Text_Blueprint:
	.string "A blueprint of some sort?\n"
	.string "It's too complicated!$"
