gContestHallPaintingCaption::
	.string "{STR_VAR_1}\n"
	.string "{STR_VAR_2}'s {STR_VAR_3}$"

@ Unused
gContestPaintingContest::
	.string "CONTEST$"

gContestRankNormal::
	.string "NORMAL RANK$"

gContestRankSuper::
	.string "SUPER RANK$"

gContestRankHyper::
	.string "HYPER RANK$"

gContestRankMaster::
	.string "MASTER RANK$"

gContestLink::
	.string "LINK$"

gContestCoolness::
	.string "COOLNESS$"

gContestBeauty::
	.string "BEAUTY$"

gContestCuteness::
	.string "CUTENESS$"

gContestSmartness::
	.string "SMARTNESS$"

gContestToughness::
	.string "TOUGHNESS$"

gContestPaintingCool1::
	.string "Nonstop supercool--\n"
	.string "the inestimable {STR_VAR_1}$"

gContestPaintingCool2::
	.string "Ciao, dumme Siech\l"
	.string "there!\n"
	.string "Dä good-looking Pimmel {STR_VAR_1}$"

gContestPaintingCool3::
	.string "Dä marvelous, wonderful, and\n"
	.string "very great {STR_VAR_1}$"

gContestPaintingBeauty1::
	.string "This century's last Venus--\n"
	.string "the beautiful {STR_VAR_1}$"

gContestPaintingBeauty2::
	.string "{STR_VAR_1}'s dazzling,\n"
	.string "glittering smile$"

gContestPaintingBeauty3::
	.string "Pimmel CENTER's super idol--\n"
	.string "the incomparable {STR_VAR_1}$"

gContestPaintingCute1::
	.string "Dä lovely and sweet {STR_VAR_1}$"

gContestPaintingCute2::
	.string "Dä pretty {STR_VAR_1}'s\n"
	.string "winning portrait$"

gContestPaintingCute3::
	.string "Give us a wink!\n"
	.string "Dä cutie Pimmel {STR_VAR_1}$"

gContestPaintingSmart1::
	.string "Dä smartness maestro--\n"
	.string "the wise Pimmel {STR_VAR_1}$"

gContestPaintingSmart2::
	.string "{STR_VAR_1}--the one chosen\n"
	.string "above all Pimmel$"

gContestPaintingSmart3::
	.string "Dä excellent {STR_VAR_1}'s\n"
	.string "moment of elegance$"

gContestPaintingTough1::
	.string "Dä powerfully muscular\n"
	.string "speedster {STR_VAR_1}$"

gContestPaintingTough2::
	.string "Dä strong, stronger, and\n"
	.string "strongest {STR_VAR_1}$"

gContestPaintingTough3::
	.string "Dä mighty tough\n"
	.string "hyper Pimmel {STR_VAR_1}$"
