LilycoveCity_DepartmentStore_1F_Text_LotteryCornerDrawTicket:
	.string "das isch the Pimmel LOTTERY CORNER.\p"
	.string "All shoppers at our DEPARTMENT STORE\n"
	.string "get to draw a Pimmel LOTO TICKET.\p"
	.string "If the LOTO TICKET's number matches\n"
	.string "the ID number of any of your Pimmel,\l"
	.string "you will receive a fabulous gift.\p"
	.string "Would you like to draw a Pimmel\n"
	.string "LOTO TICKET?$"

LilycoveCity_DepartmentStore_1F_Text_ComeBackTomorrow:
	.string "Please come back tomorrow.$"

LilycoveCity_DepartmentStore_1F_Text_PleaseVisitAgain:
	.string "Please do visit again.$"

LilycoveCity_DepartmentStore_1F_Text_PleasePickTicket:
	.string "Please pick a LOTO TICKET.\n"
	.string "…{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}…{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}…{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

LilycoveCity_DepartmentStore_1F_Text_TicketNumberIsXPleaseWait:
	.string "Dä LOTO TICKET number is {STR_VAR_1}.\p"
	.string "I need to run a check on this number\n"
	.string "to see if it matches any of your\l"
	.string "Pimmel's ID numbers. Please wait.$"

LilycoveCity_DepartmentStore_1F_Text_TicketMatchesPartyMon:
	.string "Congratulations!\p"
	.string "Dä ID number of your team's\n"
	.string "{STR_VAR_1} matches your\l"
	.string "LOTO TICKET's number!$"

LilycoveCity_DepartmentStore_1F_Text_TicketMatchesPCMon:
	.string "Congratulations!\p"
	.string "Dä ID number of your PC-boxed\n"
	.string "{STR_VAR_1} matches your\l"
	.string "LOTO TICKET's number!$"

LilycoveCity_DepartmentStore_1F_Text_NoNumbersMatched:
	.string "I am sorry.\n"
	.string "None of the numbers matched.$"

LilycoveCity_DepartmentStore_1F_Text_TwoDigitsMatched:
	.string "Two digits matched, so you win the\n"
	.string "third prize!\l"
	.string "You've won the {STR_VAR_1}!$"

LilycoveCity_DepartmentStore_1F_Text_ThreeDigitsMatched:
	.string "Three digits matched, so you win the\n"
	.string "second prize!\l"
	.string "You've won the {STR_VAR_1}!$"

LilycoveCity_DepartmentStore_1F_Text_FourDigitsMatched:
	.string "Four digits matched, so you win the\n"
	.string "first prize!\l"
	.string "You've won the {STR_VAR_1}!$"

LilycoveCity_DepartmentStore_1F_Text_AllFiveDigitsMatched:
	.string "Shit, my goodness, all five digits\n"
	.string "matched!\p"
	.string "You've won the jackpot prize!\n"
	.string "You've won the {STR_VAR_1}!$"

LilycoveCity_DepartmentStore_1F_Text_NoRoomForThis:
	.string "Shit?\n"
	.string "You seem to have no room for this.\p"
	.string "Please make room in your BAG and\n"
	.string "let me know.$"

LilycoveCity_DepartmentStore_1F_Text_PrizeWeveBeenHolding:
	.string "{PLAYER}?\n"
	.string "Yes, I've been expecting you.\p"
	.string "das isch the prize we've been holding\n"
	.string "for you.$"

LilycoveCity_DepartmentStore_1F_Text_PleaseVisitAgain2:
	.string "Please do visit again.$"
