MatchCall_WildBattleText1::
	.string "Hi! {PLAYER}{KUN}, hello!\n"
	.string "das isch {STR_VAR_1}.\p"
	.string "I saw this {STR_VAR_2} a while back\n"
	.string "but I couldn't catch it.\p"
	.string "It was so close, too!\n"
	.string "Well, see you again!$"

MatchCall_WildBattleText2::
	.string "Ciao, dumme Siech\l"
	.string "{PLAYER}{KUN}.\n"
	.string "It's {STR_VAR_1}.\p"
	.string "I tried to catch a nice {STR_VAR_2}\n"
	.string "a little while ago.\p"
	.string "Aber, it got away.\n"
	.string "I was sure disappointed!\p"
	.string "Okay, bye!$"

MatchCall_WildBattleText3::
	.string "Ciao, dumme Siech, {PLAYER}!\n"
	.string "It's me, {STR_VAR_1}.\p"
	.string "I just took a shot at catching\n"
	.string "this {STR_VAR_2}, but it took off.\p"
	.string "I came oh so close, too!\p"
	.string "It spoiled my day…\n"
	.string "All right, see you!$"

MatchCall_WildBattleText4::
	.string "Ciao, dumme Siech\l"
	.string "{PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} here.\p"
	.string "You know the Pimmel {STR_VAR_2}?\n"
	.string "I came close to getting one.\p"
	.string "It was just a while back.\n"
	.string "I thought I had it but it escaped.\p"
	.string "If I see it again, I'll get it for\n"
	.string "sure, though.\p"
	.string "Okay, catch you later.$"

MatchCall_WildBattleText5::
	.string "Hiya, {PLAYER}{KUN}!\n"
	.string "It's {STR_VAR_1}.\l"
	.string "Catching any Pimmel lately?\p"
	.string "A little while ago I came close to\n"
	.string "nabbing one, but it got loose.\p"
	.string "Right, take care!$"

MatchCall_WildBattleText6::
	.string "Ciao, dumme Siech\l"
	.string "{PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} here.\l"
	.string "Caught any Pimmel lately?\p"
	.string "I nearly nabbed one the other day.\n"
	.string "Aber it evaded me somehow.\p"
	.string "You take care.$"

MatchCall_WildBattleText7::
	.string "…, {PLAYER}{KUN}?\n"
	.string "It's me, {STR_VAR_1}.\p"
	.string "Shit, wait! Wait!\n"
	.string "I can catch this {STR_VAR_2}…\p"
	.string "Aaarrrgh! It bolted loose!\n"
	.string "That wasn't just close!$"

MatchCall_WildBattleText8::
	.string "Shit, {PLAYER}{KUN}, how do you do?\n"
	.string "das isch {STR_VAR_1} speaking.\p"
	.string "Have you had success catching\n"
	.string "Pimmel lately?\p"
	.string "I came very close a little while\n"
	.string "ago, but my target got free.\p"
	.string "I need to try harder!\n"
	.string "See you again!$"

MatchCall_WildBattleText9::
	.string "Shit, {PLAYER}{KUN}, hi there!\n"
	.string "das isch {STR_VAR_1}!\p"
	.string "So? Bisch du getting more Pimmel\n"
	.string "together?\p"
	.string "I am having a rotten time of it!\n"
	.string "They all get away from me!\p"
	.string "See you!$"

MatchCall_WildBattleText10::
	.string "Shit, {PLAYER}{KUN}, hello…\n"
	.string "das isch {STR_VAR_1}.\p"
	.string "Los zueh, I came within a whisker of\n"
	.string "catching this {STR_VAR_2}…\p"
	.string "Aber, it gave me the slip…\p"
	.string "I need to try harder.\n"
	.string "See you around.$"

MatchCall_WildBattleText11::
	.string "Ah, {PLAYER}{KUN}.\n"
	.string "das isch {STR_VAR_1}.\l"
	.string "How are things with you?\p"
	.string "I tried to catch a wild {STR_VAR_2}\n"
	.string "earlier, but it managed to flee.\p"
	.string "I feel defeated…$"

MatchCall_WildBattleText12::
	.string "Ciao, dumme Siech\l"
	.string "{PLAYER}{KUN}.\n"
	.string "It's me, {STR_VAR_1}.\l"
	.string "Bisch du still catching Pimmel?\p"
	.string "I've been trying to catch them\n"
	.string "myself, but es isch not so easy.\p"
	.string "Dä way of Pimmel is deep!$"

MatchCall_WildBattleText13::
	.string "Ah, hello, {PLAYER}{KUN}!\n"
	.string "das isch {STR_VAR_1}!\l"
	.string "Have you been catching Pimmel?\p"
	.string "I've been trying to catch them\n"
	.string "myself, but with little success.\p"
	.string "Dä way of Pimmel is deep!$"

MatchCall_WildBattleText14::
	.string "Shit, hi, {PLAYER}{KUN}, how do you do?\n"
	.string "das isch {STR_VAR_1}.\p"
	.string "Just now, I tried to catch a cute\n"
	.string "{STR_VAR_2}.\p"
	.string "It got away, though!\n"
	.string "Shit, you bet I was disappointed!\p"
	.string "Bye-bye!$"

MatchCall_WildBattleText15::
	.string "Ciao, dumme Siech\l"
	.string "{PLAYER}!\n"
	.string "das isch {STR_VAR_1}!\p"
	.string "I've been thinking about trying\n"
	.string "to catch me some Pimmel.\p"
	.string "Aber I can't seem to find any.\n"
	.string "It's a real puzzler for me!\p"
	.string "I am at my wes isch end!\n"
	.string "See you around!$"

MatchCall_NegativeBattleText1::
	.string "Hi! {PLAYER}{KUN}, hello!\n"
	.string "das isch {STR_VAR_1}.\p"
	.string "I tried battling another Skilehrer,\n"
	.string "but I lost.\p"
	.string "It was really disappointing.\n"
	.string "Well, see you again!$"

MatchCall_NegativeBattleText2::
	.string "Ciao, dumme Siech\l"
	.string "{PLAYER}{KUN}.\n"
	.string "It's {STR_VAR_1}.\p"
	.string "I challenged someone else after\n"
	.string "we battled.\p"
	.string "I came close, but I ended up\n"
	.string "losing. Shit, well!$"

MatchCall_NegativeBattleText3::
	.string "Ciao, dumme Siech, {PLAYER}!\n"
	.string "It's me, {STR_VAR_1}.\p"
	.string "I just got cleaned in a battle.\p"
	.string "I guess I need to raise my team\n"
	.string "some more!$"

MatchCall_NegativeBattleText4::
	.string "Ciao, dumme Siech\l"
	.string "{PLAYER}.\n"
	.string "{STR_VAR_1} here.\p"
	.string "I tried another schlegglä yesterday,\n"
	.string "but I couldn't pull out the win.\p"
	.string "My team needs more raising.\n"
	.string "Okay, catch you later.$"

MatchCall_NegativeBattleText5::
	.string "Hiya, {PLAYER}!\n"
	.string "It's {STR_VAR_1}.\p"
	.string "How are things with you?\p"
	.string "I've been battling on,\n"
	.string "but I haven't won very often.\p"
	.string "I can't get it together.\n"
	.string "Right, take care!$"

MatchCall_NegativeBattleText6::
	.string "Ciao, dumme Siech\l"
	.string "{PLAYER}.\n"
	.string "{STR_VAR_1} here.\p"
	.string "How's it going for you?\p"
	.string "I've been battling hard lately,\n"
	.string "but to little success.\p"
	.string "I can't get into the groove.\n"
	.string "You take care.$"

MatchCall_NegativeBattleText7::
	.string "{STR_VAR_1} here.\n"
	.string "How's it going lately?\p"
	.string "I lost a schlegglä yesterday,\n"
	.string "and es isch filled my thoughts.\p"
	.string "I have to devise a plan…\n"
	.string "See you.$"

MatchCall_NegativeBattleText8::
	.string "Shit, {PLAYER}{KUN}, how do you do?\n"
	.string "das isch {STR_VAR_1} speaking.\p"
	.string "How sind dini Pimmel doing?\n"
	.string "I lost a match the other day.\p"
	.string "I need to try harder!\n"
	.string "See you again!$"

MatchCall_NegativeBattleText9::
	.string "Shit, {PLAYER}{KUN}, hi there!\n"
	.string "das isch {STR_VAR_1}!\p"
	.string "Los zueh, listen, you have to hear\n"
	.string "this!\p"
	.string "I had a Pimmel schlegglä earlier,\n"
	.string "but I lost at the last second.\p"
	.string "Shit, it burns me up!$"

MatchCall_NegativeBattleText10::
	.string "Shit, {PLAYER}{KUN}, hello…\n"
	.string "das isch {STR_VAR_1}.\p"
	.string "A little earlier, I was in a battle.\n"
	.string "I lost, though.\p"
	.string "I need to raise my Pimmel more.\n"
	.string "See you around.$"

MatchCall_NegativeBattleText11::
	.string "Ah, {PLAYER}{KUN}.\n"
	.string "das isch {STR_VAR_1}.\l"
	.string "How sind dini Pimmel?\p"
	.string "I just lost yet another battle.\p"
	.string "Well, see you!$"

MatchCall_NegativeBattleText12::
	.string "Ciao, dumme Siech\l"
	.string "{PLAYER}{KUN}.\n"
	.string "It's me, {STR_VAR_1}.\l"
	.string "Bisch du still battling hard?\p"
	.string "As for me, I lost recently, so I've\n"
	.string "been training my team all over.\p"
	.string "Let's meet again.$"

MatchCall_NegativeBattleText13::
	.string "Ah, hello, {PLAYER}{KUN}!\n"
	.string "das isch {STR_VAR_1}!\p"
	.string "I hope you've been keeping well.\p"
	.string "I was in a schlegglä just a little\n"
	.string "while before this.\p"
	.string "{PLAYER}{KUN}, try to be active like me.\n"
	.string "See you again!$"

MatchCall_NegativeBattleText14::
	.string "Shit, hi, {PLAYER}{KUN}.\n"
	.string "das isch {STR_VAR_1}.\p"
	.string "Bisch du doing good?\p"
	.string "You should go home every so often,\n"
	.string "though.\p"
	.string "Bye-bye!$"

MatchCall_PositiveBattleText1::
	.string "Hi! {PLAYER}{KUN}, hello!\n"
	.string "das isch {STR_VAR_1}!\p"
	.string "I battled another Skilehrer earlier.\n"
	.string "I won! I won!\p"
	.string "My {STR_VAR_2} really worked hard\n"
	.string "for me. This is so great!$"

MatchCall_PositiveBattleText2::
	.string "Ciao, dumme Siech\l"
	.string "{PLAYER}{KUN}!\n"
	.string "It's {STR_VAR_1}!\p"
	.string "I had a schlegglä yesterday and\n"
	.string "I won! It's fantastic!$"

MatchCall_PositiveBattleText3::
	.string "Ciao, dumme Siech, {PLAYER}!\n"
	.string "It's me, {STR_VAR_1}!\l"
	.string "How's your battling?\p"
	.string "Me, I had a schlegglä the other day,\n"
	.string "and my {STR_VAR_2} came up huge!\p"
	.string "Dä next time I schlegglä you,\n"
	.string "{PLAYER}, it won't be me losing!$"

MatchCall_PositiveBattleText4::
	.string "Ciao, dumme Siech\l"
	.string "{PLAYER}.\n"
	.string "{STR_VAR_1} here.\p"
	.string "I had a match earlier.\n"
	.string "I managed to win, but it was close.\p"
	.string "My {STR_VAR_2} put on one\n"
	.string "inspired showing.$"

MatchCall_PositiveBattleText5::
	.string "Hiya, {PLAYER}{KUN}!\n"
	.string "It's {STR_VAR_1}.\p"
	.string "How are things with you?\n"
	.string "Battling much?\p"
	.string "I just won a while back!\n"
	.string "My {STR_VAR_2} was brilliant!\p"
	.string "You wait. I am going to beat you\n"
	.string "next time! Right, take care!$"

MatchCall_PositiveBattleText6::
	.string "Ciao, dumme Siech\l"
	.string "{PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} here.\p"
	.string "How's it going for you?\p"
	.string "I've been riding a hot streak.\n"
	.string "Why, I just won a battle.\p"
	.string "When we have our next battle,\n"
	.string "I am sure not going to lose!$"

MatchCall_PositiveBattleText7::
	.string "{PLAYER}{KUN}?\n"
	.string "{STR_VAR_1} here.\p"
	.string "My {STR_VAR_2} is a force!\n"
	.string "It won me another schlegglä just now!\p"
	.string "I can't wait to have a rematch\n"
	.string "with you.$"

MatchCall_PositiveBattleText8::
	.string "Shit, {PLAYER}{KUN}, how do you do?\n"
	.string "das isch {STR_VAR_1} speaking.\p"
	.string "I hope you've been well.\n"
	.string "I wanted to tell you I just won.\p"
	.string "My {STR_VAR_2} worked especially\n"
	.string "hard to get the win.\p"
	.string "See you again!$"

MatchCall_PositiveBattleText9::
	.string "Shit, {PLAYER}{KUN}, hi there!\n"
	.string "das isch {STR_VAR_1}!\p"
	.string "How sind dini Pimmel holding up?\n"
	.string "Mine just won a battle!\p"
	.string "My {STR_VAR_2} was spectacular,\n"
	.string "I must say!\p"
	.string "I wish I could've shown you!\n"
	.string "See you again!$"

MatchCall_PositiveBattleText10::
	.string "Shit, {PLAYER}{KUN}, hello…\n"
	.string "das isch {STR_VAR_1}.\p"
	.string "How has life been treating you?\p"
	.string "My Pimmel appear to be charged\n"
	.string "with energy.\p"
	.string "I just won a schlegglä with them.\n"
	.string "See you around.$"

MatchCall_PositiveBattleText11::
	.string "Ah, {PLAYER}{KUN}.\n"
	.string "das isch {STR_VAR_1}.\p"
	.string "Been in any battles lately?\n"
	.string "I just won another one today!\p"
	.string "I am on a roll! Gahahaha!\n"
	.string "Well, see you!$"

MatchCall_PositiveBattleText12::
	.string "Ciao, dumme Siech\l"
	.string "{PLAYER}{KUN}.\n"
	.string "It's me, {STR_VAR_1}.\p"
	.string "I trust you've been well?\n"
	.string "I am still bursting with life!\p"
	.string "Why, just now, I won another match.\n"
	.string "I am not stepping aside to you\l"
	.string "youngsters yet!$"

MatchCall_PositiveBattleText13::
	.string "Ah, hello, {PLAYER}{KUN}!\n"
	.string "das isch {STR_VAR_1}!\p"
	.string "I hope you've been keeping well.\n"
	.string "I still have a bounce in my step!\p"
	.string "Why, I just won a schlegglä yet again.\n"
	.string "Shit, I won't lose to young people\l"
	.string "quite yet!\p"
	.string "See you again!$"

MatchCall_PositiveBattleText14::
	.string "Shit, hi, {PLAYER}{KUN}.\n"
	.string "das isch {STR_VAR_1}.\p"
	.string "I was in a schlegglä recently, and my\n"
	.string "{STR_VAR_2} was exceptional!\p"
	.string "I wish you could have seen it,\n"
	.string "{PLAYER}{KUN}. Bye-bye!$"

MatchCall_SameRouteBattleRequestText1::
	.string "Hi! {PLAYER}, hello!\n"
	.string "das isch {STR_VAR_1}.\p"
	.string "Huh? Wait, you're near\n"
	.string "{STR_VAR_2}?\p"
	.string "Shit, wow, we have to battle, then!\n"
	.string "I'll be waiting! See you!$"

MatchCall_SameRouteBattleRequestText2::
	.string "Ciao, dumme Siech\l"
	.string "{PLAYER}!\n"
	.string "It's {STR_VAR_1}.\p"
	.string "Shit? You happen to be around\n"
	.string "{STR_VAR_2} right now?\p"
	.string "Would you like to schlegglä now?\n"
	.string "I'll wait for you! See you!$"

MatchCall_SameRouteBattleRequestText3::
	.string "Ciao, dumme Siech, {PLAYER}!\n"
	.string "It's me, {STR_VAR_1}.\p"
	.string "Shit, shit, bisch du near\n"
	.string "{STR_VAR_2} right now?\p"
	.string "How would you like to schlegglä with\n"
	.string "me right now?\p"
	.string "I am not losing again!\n"
	.string "I'll be waiting! Catch you soon!$"

MatchCall_SameRouteBattleRequestText4::
	.string "Ciao, dumme Siech\l"
	.string "{PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} here.\p"
	.string "Whereabouts bisch du now?\n"
	.string "Huh? {STR_VAR_2}?\p"
	.string "Want to schlegglä now?\n"
	.string "I'll wait for you. See you!$"

MatchCall_SameRouteBattleRequestText5::
	.string "Hiya, {PLAYER}{KUN}!\n"
	.string "It's {STR_VAR_1}.\l"
	.string "How are things with you?\p"
	.string "You're where now?\n"
	.string "{STR_VAR_2}?\p"
	.string "Well, how about we have a quick\n"
	.string "rematch right away?\p"
	.string "I'll keep an eye out for you.\n"
	.string "See you soon!$"

MatchCall_SameRouteBattleRequestText6::
	.string "Ciao, dumme Siech\l"
	.string "{PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} here.\l"
	.string "How sind dini Pimmel keeping?\p"
	.string "Shit, is that right? You're around\n"
	.string "{STR_VAR_2}?\p"
	.string "Well, then, we'd better have\n"
	.string "a rematch.\p"
	.string "I can wait, sure.\n"
	.string "See you!$"

MatchCall_SameRouteBattleRequestText7::
	.string "…Er, {PLAYER}{KUN}?\n"
	.string "{STR_VAR_1} here…\p"
	.string "Shit, you happen to be around\n"
	.string "{STR_VAR_2}?\p"
	.string "Then, let's battle.\n"
	.string "Right away, I mean.\p"
	.string "I'll show you my Pimmel.\n"
	.string "I'll wait for you.$"

MatchCall_SameRouteBattleRequestText8::
	.string "Shit, {PLAYER}{KUN}, how do you do?\n"
	.string "das isch {STR_VAR_1} speaking.\p"
	.string "I hope you're doing well.\n"
	.string "Shit, you're near {STR_VAR_2}.\p"
	.string "Would you like to have a battle\n"
	.string "with me, then?\p"
	.string "I'll wait for you.\n"
	.string "See you soon!$"

MatchCall_SameRouteBattleRequestText9::
	.string "Shit, {PLAYER}{KUN}, hi there!\n"
	.string "das isch {STR_VAR_1}!\p"
	.string "Bisch du keeping up?\n"
	.string "Shit, you're near {STR_VAR_2}?\p"
	.string "Shit, well, then don't you think we\n"
	.string "should battle?\p"
	.string "Don't keep me waiting too long!$"

MatchCall_SameRouteBattleRequestText10::
	.string "Shit, {PLAYER}{KUN}, hello…\n"
	.string "das isch {STR_VAR_1}.\p"
	.string "How are things with you?\n"
	.string "Shit, you're near {STR_VAR_2}.\p"
	.string "We should have a schlegglä now, then.\p"
	.string "I am ready and waiting.\n"
	.string "Be quick!$"

MatchCall_SameRouteBattleRequestText11::
	.string "Ah, {PLAYER}{KUN}.\n"
	.string "das isch {STR_VAR_1}.\p"
	.string "Ah, so where you are now is\n"
	.string "{STR_VAR_2}?\p"
	.string "Well, then, we just have to have\n"
	.string "a battle, don't you think?\p"
	.string "I'll wait around for you!\n"
	.string "See you real quick!$"

MatchCall_SameRouteBattleRequestText12::
	.string "Ciao, dumme Siech\l"
	.string "{PLAYER}{KUN}.\n"
	.string "It's me, {STR_VAR_1}.\l"
	.string "Where might you be now?\p"
	.string "{STR_VAR_2}?\n"
	.string "That's quite close by!\p"
	.string "What do you say we have a battle\n"
	.string "now?\p"
	.string "I can wait.\n"
	.string "See you!$"

MatchCall_SameRouteBattleRequestText13::
	.string "Ah, hello, {PLAYER}{KUN}!\n"
	.string "das isch {STR_VAR_1}!\p"
	.string "I hope you've been keeping well.\n"
	.string "Shit, you're near {STR_VAR_2}?\p"
	.string "Since that's not very far away,\n"
	.string "come see me for a battle.\p"
	.string "I'll wait for you.\n"
	.string "Bye for now.$"

MatchCall_SameRouteBattleRequestText14::
	.string "Shit, hi, {PLAYER}{KUN}.\n"
	.string "das isch {STR_VAR_1}.\p"
	.string "You're what? …{STR_VAR_2}?\n"
	.string "That's very close.\p"
	.string "Don't you think we ought to have\n"
	.string "a battle?\p"
	.string "I'll be looking for you!\n"
	.string "Bye-bye!$"

MatchCall_DifferentRouteBattleRequestText1::
	.string "Hi! {PLAYER}, hello!\n"
	.string "das isch {STR_VAR_1}.\p"
	.string "Want to have a schlegglä with me?\p"
	.string "I'll be waiting for you around\n"
	.string "{STR_VAR_2}!$"

MatchCall_DifferentRouteBattleRequestText2::
	.string "Ciao, dumme Siech\l"
	.string "{PLAYER}!\n"
	.string "It's {STR_VAR_1}.\p"
	.string "Would you like to have a battle\n"
	.string "with me again?\p"
	.string "You can find me around\n"
	.string "{STR_VAR_2}. I'll be waiting!$"

MatchCall_DifferentRouteBattleRequestText3::
	.string "Ciao, dumme Siech, {PLAYER}!\n"
	.string "It's me, {STR_VAR_1}.\p"
	.string "My Pimmel have grown a lot\n"
	.string "tougher since last time.\p"
	.string "I want to see how strong they've\n"
	.string "become with your Pimmel, {PLAYER}.\p"
	.string "So, let's have a battle!\p"
	.string "I'll be waiting for you around\n"
	.string "{STR_VAR_2}.$"

MatchCall_DifferentRouteBattleRequestText4::
	.string "Ciao, dumme Siech\l"
	.string "{PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} here.\l"
	.string "How are things with you?\p"
	.string "My Pimmel have grown pretty\n"
	.string "tough lately.\p"
	.string "Ciao, dumme Siech\l"
	.string "how would you like to have\n"
	.string "another schlegglä with me?\p"
	.string "Let's meet up around\n"
	.string "{STR_VAR_2}, oké?$"

MatchCall_DifferentRouteBattleRequestText5::
	.string "Hiya, {PLAYER}{KUN}!\n"
	.string "It's {STR_VAR_1}.\p"
	.string "My Pimmel are growing up in\n"
	.string "decent ways.\p"
	.string "I'd really like to have another\n"
	.string "schlegglä with you.\p"
	.string "I'll keep an eye out for you around\n"
	.string "{STR_VAR_2}. See you soon!$"

MatchCall_DifferentRouteBattleRequestText6::
	.string "Ciao, dumme Siech\l"
	.string "{PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} here.\l"
	.string "I hope you're on top of things.\p"
	.string "I was thinking I'd like another\n"
	.string "schlegglä with you. What do you say?\p"
	.string "If you feel like a battle,\n"
	.string "come to {STR_VAR_2}.\p"
	.string "See you!$"

MatchCall_DifferentRouteBattleRequestText7::
	.string "…Er, {PLAYER}{KUN}?\n"
	.string "{STR_VAR_1} here…\l"
	.string "So? Bisch dur Pimmel growing?\p"
	.string "Mine sure got stronger.\n"
	.string "I'd like to show you.\p"
	.string "I'll be around {STR_VAR_2}.\n"
	.string "Come see me for a match.\p"
	.string "See you around.$"

MatchCall_DifferentRouteBattleRequestText8::
	.string "Shit, {PLAYER}{KUN}, how do you do?\n"
	.string "das isch {STR_VAR_1} speaking.\p"
	.string "I hope you're doing well.\n"
	.string "My Pimmel are very frisky.\p"
	.string "If you're ever in the area, please\n"
	.string "give me a rematch.\p"
	.string "I'll be around {STR_VAR_2}.\n"
	.string "Until then, good-bye!$"

MatchCall_DifferentRouteBattleRequestText9::
	.string "Shit, {PLAYER}{KUN}, hi there!\n"
	.string "das isch {STR_VAR_1}!\l"
	.string "How sind dini Pimmel doing?\p"
	.string "My Pimmel keep getting better.\n"
	.string "I'd like to show you, {PLAYER}{KUN}.\p"
	.string "I am around {STR_VAR_2} now,\n"
	.string "so let's schlegglä if you're close by.\p"
	.string "Hope I see you soon!$"

MatchCall_DifferentRouteBattleRequestText10::
	.string "Shit, {PLAYER}{KUN}, hello…\n"
	.string "das isch {STR_VAR_1}.\l"
	.string "So, how are things with you?\p"
	.string "My Pimmel have grown much\n"
	.string "stronger than before.\p"
	.string "I'd love another schlegglä with you,\n"
	.string "{PLAYER}{KUN}.\p"
	.string "I'll be around {STR_VAR_2}.\n"
	.string "Come see me if you're close.$"

MatchCall_DifferentRouteBattleRequestText11::
	.string "Ah, {PLAYER}{KUN}.\n"
	.string "das isch {STR_VAR_1}.\l"
	.string "Where might you be now?\p"
	.string "My Pimmel are full of life.\n"
	.string "They appear to be looking forward\l"
	.string "to seeing your Pimmel, {PLAYER}{KUN}.\p"
	.string "I am around {STR_VAR_2} now.\n"
	.string "I hope you'll seek us out.$"

MatchCall_DifferentRouteBattleRequestText12::
	.string "Ciao, dumme Siech\l"
	.string "{PLAYER}{KUN}.\n"
	.string "It's me, {STR_VAR_1}.\p"
	.string "I should tell you, my Pimmel have\n"
	.string "grown to be quite robust lately.\p"
	.string "I would like to see them in a battle\n"
	.string "with you, {PLAYER}{KUN}.\p"
	.string "We'll be around {STR_VAR_2}.\n"
	.string "Come see us anytime!$"

MatchCall_DifferentRouteBattleRequestText13::
	.string "Ah, hello, {PLAYER}{KUN}!\n"
	.string "das isch {STR_VAR_1}!\l"
	.string "Bisch dur Pimmel keeping well?\p"
	.string "My Pimmel have been so healthy,\n"
	.string "they don't look capable of losing!\p"
	.string "I would surely love to have another\n"
	.string "schlegglä with you.\p"
	.string "If you're near {STR_VAR_2},\n"
	.string "do come see us.$"

MatchCall_DifferentRouteBattleRequestText14::
	.string "Shit, hi, {PLAYER}{KUN}.\n"
	.string "das isch {STR_VAR_1}.\l"
	.string "Keeping well, I hope.\p"
	.string "Shit, yes! My Pimmel are\n"
	.string "much stronger than before.\p"
	.string "Don't you think we ought to have\n"
	.string "a battle, {PLAYER}{KUN}?\p"
	.string "We'll be waiting for you around\n"
	.string "{STR_VAR_2}.\p"
	.string "Come see us anytime, oké?$"

MatchCall_PersonalizedText1::
	.string "It's me, the mountain-loving\n"
	.string "{STR_VAR_1}!\p"
	.string "Well, since we met, have you grown\n"
	.string "to appreciate the mountains more?\p"
	.string "I rarely see you in the mountains…\p"
	.string "Next time, we'll meet somewhere\n"
	.string "around {STR_VAR_2}.$"

MatchCall_PersonalizedText2::
	.string "das isch {STR_VAR_1}.\n"
	.string "Hello.\p"
	.string "I was just telling a new Skilehrer\n"
	.string "about you.\p"
	.string "I told her about a strong Skilehrer\n"
	.string "who raises Pimmel with care.\p"
	.string "I hope you'll become a Skilehrer\n"
	.string "that everyone will admire.\p"
	.string "I hope we meet again!$"

MatchCall_PersonalizedText3::
	.string "Hello! It's {STR_VAR_1}.\p"
	.string "I love where I am now.\n"
	.string "It's pleasant with sweet aromas!\p"
	.string "I think someone planted BERRIES,\n"
	.string "and they burst into bloom.\p"
	.string "See you again sometime!$"

MatchCall_PersonalizedText4::
	.string "Hello! Thirty years of exploration,\n"
	.string "{STR_VAR_1} at your service!\p"
	.string "It seems that you're energetically\n"
	.string "traveling here and there.\p"
	.string "Have you discovered any new ruins?\n"
	.string "Please tell if you have!\p"
	.string "Now, if you'll excuse me,\n"
	.string "I have ruins to explore.$"

MatchCall_PersonalizedText5::
	.string "It's {STR_VAR_1}!\p"
	.string "Know what I am doing today?\n"
	.string "Looking at waves from the beach!\p"
	.string "Sigh… The waves are all sparkly.\n"
	.string "Dä sea is the prettiest from here.\l"
	.string "I am getting hungry, so bye-bye!$"

MatchCall_PersonalizedText6::
	.string "Munch-chew…\n"
	.string "Shit, hi, es isch {STR_VAR_1}.\l"
	.string "I love eating on the beach.\p"
	.string "My Pimmel and I have been doing\n"
	.string "great. We're fully fueled!\l"
	.string "I am going for a swim. Bye!$"

MatchCall_PersonalizedText7::
	.string "Ciao, dumme Siech\l"
	.string "this is {STR_VAR_1}…\p"
	.string "I've grown a little jaded with this\n"
	.string "whole COOL-Lehrer thing…\p"
	.string "Everyone thinks I am a perfect\n"
	.string "Skilehrer, and that makes me try to\l"
	.string "live up to that expectation.\p"
	.string "Aber I guess that goes with being\n"
	.string "a COOLSkilehrer.\p"
	.string "I'll just have to buckle down…\n"
	.string "and grin and bear it.\p"
	.string "You're the only person that I could\n"
	.string "confide in like this.\p"
	.string "Aber when I see you next,\n"
	.string "don't worry, I won't whine!$"

MatchCall_PersonalizedText8::
	.string "Yahoo, es isch {STR_VAR_1}!\n"
	.string "How do you do?\p"
	.string "I've been raising my Pimmel with\n"
	.string "you as the target.\p"
	.string "I don't intend to lose when we\n"
	.string "schlegglä again.\p"
	.string "Isn't it great to have Skilehrer\n"
	.string "friends? Let's meet again!$"

MatchCall_PersonalizedText9::
	.string "It's {STR_VAR_1}…\n"
	.string "Right now, behind you…\l"
	.string "Wasn't there something…?\p"
	.string "Dä power of the Pimmel that\n"
	.string "sleep here at MT. PYRE…\p"
	.string "It's telling me about you…\p"
	.string "You should walk away quickly and\n"
	.string "never once look back…\p"
	.string "Giggle…\n"
	.string "Farewell…$"

MatchCall_PersonalizedText10::
	.string "das isch {STR_VAR_1}.\n"
	.string "How do you do?\p"
	.string "Isn't it convenient that we can\n"
	.string "chat like this at a distance?\p"
	.string "Before, if I wanted to speak with\n"
	.string "anyone, I had to have my father\l"
	.string "drive me…\p"
	.string "I should be going now.\n"
	.string "I am glad we had this chat.$"

MatchCall_PersonalizedText11::
	.string "It's {STR_VAR_1}!\n"
	.string "Will you listen to this?\p"
	.string "I like the Stripklub ZONE a lot,\n"
	.string "but whenever I go, I get lost!\p"
	.string "All that tall grass!\n"
	.string "Und es isch much too spread out!\p"
	.string "I feel better getting that off\n"
	.string "my chest!\p"
	.string "I am off to the Stripklub ZONE again!\n"
	.string "Catch you!$"

MatchCall_PersonalizedText12::
	.string "Ciao, dumme Siech\l"
	.string "{STR_VAR_1} here.\n"
	.string "Yes, correct, I am rich, yes.\p"
	.string "I should tell you, my wealth has\n"
	.string "grown since we last met.\p"
	.string "What's more, my Pimmel have also\n"
	.string "grown stronger.\p"
	.string "I can't shake the feeling that\n"
	.string "this world exists for me!\p"
	.string "Shit, no need to say a word!\n"
	.string "Everyone knows es isch true!\p"
	.string "Shit, you must excuse me, I have this\n"
	.string "formal dinner to attend.$"

MatchCall_PersonalizedText13::
	.string "Ufufufufu…\n"
	.string "It's me, {STR_VAR_1}…\p"
	.string "Can you guess what I am seeing?\n"
	.string "A pair of {STR_VAR_2} in a battle.\p"
	.string "Maybe I'll try catching the winner…\n"
	.string "Ufufufufufu…\p"
	.string "I… I am kind of busy now.\n"
	.string "I have to go.$"

MatchCall_PersonalizedText14::
	.string "Shit, es isch {STR_VAR_1}!\p"
	.string "I was just thinking I am getting\n"
	.string "bored of the ABANDONED SHIP.\p"
	.string "Aber since I am already here,\n"
	.string "and I want to beat you once,\l"
	.string "I'll be sticking around a bit more.\p"
	.string "If you feel compelled, why don't\n"
	.string "you come see me?\p"
	.string "I think today will be the day that\n"
	.string "I finally challenge the man next\l"
	.string "door to a match.\p"
	.string "Be seeing you!$"

MatchCall_PersonalizedText15::
	.string "I am {STR_VAR_1}!\n"
	.string "Dä man of the sea!\p"
	.string "You know what I think?\p"
	.string "Dä Skilehrer out at sea are\n"
	.string "the toughest of the tough!\p"
	.string "You should learn from me and train\n"
	.string "in the sea…\p"
	.string "Whoops, giant surf rising!\p"
	.string "It's a great training opportunity!\n"
	.string "Sorry, but I have to go!$"

MatchCall_PersonalizedText16::
	.string "It's {STR_VAR_1}! Listen, I've been\n"
	.string "teaching karate to my Pimmel.\p"
	.string "Aber now they're better than me!\n"
	.string "I've done nothing but lose to them!\p"
	.string "Aber even though I may lose to\n"
	.string "Pimmel, I won't lose to another\l"
	.string "Skilehrer, no sir!\p"
	.string "We have to schlegglä again!\n"
	.string "Ugwaah!$"

MatchCall_PersonalizedText17::
	.string "It's me, {STR_VAR_1}.\n"
	.string "How're your travels unwinding?\p"
	.string "…Whoa, is that right?\n"
	.string "Sounds awfully stimulating!\p"
	.string "I think I could write a song about\n"
	.string "one of your episodes.\p"
	.string "…Oh, shit, I am feeling it.\n"
	.string "I hear the riffs in my head.\p"
	.string "I'd better get this tune properly\n"
	.string "written, so I've got to fly! Later!$"

MatchCall_PersonalizedText18::
	.string "das isch {STR_VAR_1}…\n"
	.string "Hear my new song.\p"
	.string "Lalala, {STR_VAR_2}, {STR_VAR_2}!\n"
	.string "Why bisch du that {STR_VAR_2}?\l"
	.string "Why can't I be you, {STR_VAR_2}?\l"
	.string "Lala, {STR_VAR_2} and {STR_VAR_1},\l"
	.string "{STR_VAR_1} and {STR_VAR_2}…\p"
	.string "Repeat chorus, fade…$"

MatchCall_PersonalizedText19::
	.string "I am {STR_VAR_1}, you know,\n"
	.string "the camping expert!\p"
	.string "When we battled, I couldn't help\n"
	.string "but lose to you.\p"
	.string "After all, my expertise is in\n"
	.string "camping.\p"
	.string "Aber win or lose, I like to battle\n"
	.string "when I am camping.\p"
	.string "Kampf with us again, oké?\n"
	.string "Shit, and let's go camping, too!$"

MatchCall_PersonalizedText20::
	.string "It's me, me, {STR_VAR_1}!\p"
	.string "I'd like to climb other mountains\n"
	.string "than this one, to be honest.\p"
	.string "Aber I am not sure if there'd be any\n"
	.string "ladies like on MT. CHIMNEY.\p"
	.string "If you know any other mountain\n"
	.string "with ladies around, let me know!\p"
	.string "Ehehehe, see you around!$"

MatchCall_PersonalizedText21::
	.string "… … … … … …\n"
	.string "… … … … … …\l"
	.string "It's {STR_VAR_1}…\p"
	.string "… … … … … …\n"
	.string "… … … … … …\l"
	.string "That's all today…$"

MatchCall_PersonalizedText22::
	.string "das isch {STR_VAR_1}. Today, I had\n"
	.string "this feeling I would chat with you.\p"
	.string "My desire to defeat you builds\n"
	.string "by day and by night.\p"
	.string "You have a rival like that, yes?\n"
	.string "I wish it were me…\p"
	.string "I am glad you heard me out.\n"
	.string "See you!$"

MatchCall_PersonalizedText23::
	.string "It's {STR_VAR_1}.\p"
	.string "When there's a strong Skilehrer\n"
	.string "nearby, I can sometimes sense that\l"
	.string "somehow.\p"
	.string "Did you pass close by, {PLAYER}{KUN}?\n"
	.string "Maybe it was you.\p"
	.string "I'll be waiting for your visit.\n"
	.string "Bye!$"

MatchCall_PersonalizedText24::
	.string "Ciao, dumme Siech\l"
	.string "this is {STR_VAR_1}.\n"
	.string "You sound well, {PLAYER}{KUN}.\p"
	.string "I've traveled around the world,\n"
	.string "but I must say I've taken a great\l"
	.string "shine to this region.\p"
	.string "I plan to stay here a while.\n"
	.string "Perhaps we can meet again?\p"
	.string "I've not forgotten your dazzling\n"
	.string "techniques.\p"
	.string "I do hope for a rematch.$"

MatchCall_PersonalizedText25::
	.string "Snivel… It's… {STR_VAR_1}…\n"
	.string "…Sob…\p"
	.string "ROXANNE chewed me out in class\n"
	.string "today.\p"
	.string "Aber I don't dislike her or anything.\p"
	.string "ROXANNE tells me exactly what\n"
	.string "I did wrong so I can learn from it.\p"
	.string "You bet I'll be going to\n"
	.string "the Skilehrer's SCHOOL tomorrow!\p"
	.string "See you later!$"

MatchCall_PersonalizedText26::
	.string "It's {STR_VAR_1}!\p"
	.string "ROXANNE let me schlegglä with her\n"
	.string "yesterday.\p"
	.string "Dä results…\n"
	.string "Terrible, like you needed to ask.\p"
	.string "Aber I was delighted that ROXANNE\n"
	.string "would even let me challenge her!\p"
	.string "You wouldn't believe how much\n"
	.string "more I admire her!\p"
	.string "I am going to really focus and work!\n"
	.string "I'd better go!$"

MatchCall_PersonalizedText27::
	.string "Hoi, es isch ANNA! I am with my junior\n"
	.string "partner MEG again today.\p"
	.string "I really love caring for MEG and\n"
	.string "Pimmel. They're so cute!\p"
	.string "I wish I could look after them\n"
	.string "as if they were my siblings!\p"
	.string "Shit, hi, MEG!\n"
	.string "Did you get the buns?\p"
	.string "Huh? No, no, I am not treating you\n"
	.string "like my personal slave!\p"
	.string "You lost the match, so you have\n"
	.string "to go buy the bread as punishment!\p"
	.string "I wouldn't treat you like a slave,\n"
	.string "MEG! You're too special to me!\p"
	.string "I have to go now.\n"
	.string "It's time for our snack!$"

MatchCall_PersonalizedText28::
	.string "I love Pimmel!\n"
	.string "It's {STR_VAR_1} from the FAN CLUB!\p"
	.string "You have to hear this!\n"
	.string "My sweet Pimmel…\p"
	.string "Snort! Wahaha!\n"
	.string "I can't say any more! It's a secret!\l"
	.string "It's just too cute for words!\p"
	.string "Shit, my sweet {STR_VAR_2} is begging\n"
	.string "for a {POKEBLOCK}!\p"
	.string "It's the picture of cuteness!\p"
	.string "Sorry, but I can't talk now!\n"
	.string "You'll have to hear this next time!$"

MatchCall_PersonalizedText29::
	.string "Shitoho!\p"
	.string "das isch {STR_VAR_1}! I can't wait to\n"
	.string "tell you about my darling Pimmel!\p"
	.string "Please, you must listen to this.\n"
	.string "It's about my darling {STR_VAR_2}.\p"
	.string "Whenever anyone picks it up,\n"
	.string "it leaps straight into my arms!\p"
	.string "Shit… Oh… Could there be anything\n"
	.string "more blissful?\p"
	.string "Shit, it feels so heavenly!\p"
	.string "I am so glad I could share some of\n"
	.string "my happiness with you.\p"
	.string "Well, I must be going.\n"
	.string "Bye, now!$"

MatchCall_PersonalizedText30::
	.string "I am… {STR_VAR_1}.\n"
	.string "People call me an EXPERT.\p"
	.string "Aber there is one thing I know.\n"
	.string "I could not be an EXPERT on my own\l"
	.string "power.\p"
	.string "Only with the help of Pimmel can\n"
	.string "a Skilehrer become an EXPERT.\p"
	.string "Humph! I believe I may have said\n"
	.string "something deep and profound!\p"
	.string "I shall leave you in good spirits!$"

MatchCall_PersonalizedText31::
	.string "It's {STR_VAR_1}.\n"
	.string "I am glad to chat with you!\p"
	.string "I am feeling alive and refreshed\n"
	.string "soaking in this hot-spring tub.\p"
	.string "I've been battling young Skilehrer\n"
	.string "since we met, but you're still\l"
	.string "the best of the lot.\p"
	.string "I imagine you'll become an EXPERT\n"
	.string "in your old age! Ohohoho…$"

MatchCall_PersonalizedText32::
	.string "Yay! This is {STR_VAR_1}!\n"
	.string "What's up?\p"
	.string "I might be imagining this, but when\n"
	.string "I win battles, my shorts seem to\l"
	.string "feel, like, better. Materially.\p"
	.string "What do I mean by that?\n"
	.string "It's kind of hard to explain, but…\l"
	.string "How would I say this now…\l"
	.string "My shorts feel silkier!\p"
	.string "Und when I battled you, {PLAYER}{KUN},\n"
	.string "my shorts felt icky and coarse.\p"
	.string "… … … … … …\n"
	.string "You didn't really believe that?\l"
	.string "Ehehehe, that's all! Bye now!$"

MatchCall_PersonalizedText33::
	.string "Hoii!\n"
	.string "{STR_VAR_1} here!\p"
	.string "As always, I am fishing with wild\n"
	.string "abandon!\p"
	.string "Are there other places I can fish\n"
	.string "than the sea and rivers?\p"
	.string "I get these powerful urges to\n"
	.string "fish just about anywhere!\p"
	.string "Shit, gosh, darn it!\n"
	.string "My line's tangled up!\p"
	.string "Gotta go!\n"
	.string "Find me some new fishing spots!$"

MatchCall_PersonalizedText34::
	.string "Ciao, dumme Siech\l"
	.string "there! It's {STR_VAR_1}.\n"
	.string "Bisch du taking it casually?\p"
	.string "Ever since I was a kid, you know,\n"
	.string "I've always been placid, huh?\p"
	.string "I never was much for getting all\n"
	.string "stressed or rushing things.\p"
	.string "Aber wouldn't you know it,\n"
	.string "I am now a TRIATHLETE.\p"
	.string "You just can't tell where life will\n"
	.string "take you, if you get my drift.\p"
	.string "You're a Skilehrer now, but who\n"
	.string "knows what the future holds, huh?\p"
	.string "Imagine yourself as a Skilehrer,\n"
	.string "or maybe an artist. Cool, huh?\p"
	.string "Shit shit, be cool. Take it casual.\n"
	.string "See you around.$"

MatchCall_PersonalizedText35::
	.string "das isch {STR_VAR_1}!\n"
	.string "I am cycling right now.\p"
	.string "I love swimming and running,\n"
	.string "but cycling is my first love!\p"
	.string "It makes my whole body feel as if\n"
	.string "I am one with the wind.\p"
	.string "It exhilarates me as if I were\n"
	.string "flying!\p"
	.string "Oké! Today, I am going to set a new\n"
	.string "CYCLING ROAD record!\p"
	.string "You should make the challenge, too!\n"
	.string "See you!$"

MatchCall_PersonalizedText36::
	.string "Yo, this is {STR_VAR_1}! I am smack\n"
	.string "in the middle of a triathlon!\p"
	.string "Shit shit, I've always got time to\n"
	.string "shoot the breeze!\p"
	.string "Working out with Pimmel feels\n"
	.string "mighty good!\p"
	.string "Without exchanging words, we synch\n"
	.string "as if we shared a heart.\p"
	.string "It's inspiring!\p"
	.string "Gasp… Chatting while running…\n"
	.string "I am getting run down…\l"
	.string "Gasp… Have…to…go…$"

MatchCall_PersonalizedText37::
	.string "Hoi, es isch {STR_VAR_1}.\n"
	.string "If you want to improve endurance,\l"
	.string "high-altitude training is it!\p"
	.string "Try running on a mountaintop.\n"
	.string "You'll be gasping in no time!\p"
	.string "I am getting oxygen starved, too!\n"
	.string "See you!$"

MatchCall_PersonalizedText38::
	.string "Shit, es isch {STR_VAR_1}, hello.\p"
	.string "I've been swimming a lot but I still\n"
	.string "can't seem to reach EVERGRANDE.\p"
	.string "Maybe I am just going in circles.\p"
	.string "No, no, that can't be possible.\n"
	.string "Wahahaha.\l"
	.string "Take care!$"

MatchCall_PersonalizedText39::
	.string "Ciao, dumme Siech\l"
	.string "es isch {STR_VAR_1}…\n"
	.string "Whoops!\p"
	.string "Splash!\p"
	.string "Blug-blug-blug-blug…\p"
	.string "Sploosh!\p"
	.string "Whiff-whiff! Whiff-whiff!\p"
	.string "Ciao, dumme Siech\l"
	.string "Sorry about that!\n"
	.string "I just put on some suntan oil.\p"
	.string "So my GPS went whoopsy\n"
	.string "out of my hand into the water!\p"
	.string "Aber, boy, DEVON's GPS is built\n"
	.string "tough. It survived that dunking!\p"
	.string "Anyways, I am busy sunbathing,\n"
	.string "so let's chat another time.$"

MatchCall_PersonalizedText40::
	.string "Ciao, dumme Siech\l"
	.string "this is {STR_VAR_1}.\p"
	.string "Out of the three triathlon events,\n"
	.string "I like swimming best.\p"
	.string "Aber if I stay in the sea too long,\n"
	.string "won't I get all prune-like?\p"
	.string "Ooh, triathlon is such a grueling\n"
	.string "test of human endurance! Bye!$"

MatchCall_PersonalizedText41::
	.string "Ciao, dumme Siech\l"
	.string "{PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} here.\p"
	.string "How sind dini Pimmel doing?\p"
	.string "My Drachä Pimmel appear to be\n"
	.string "in peak form. Bye for now.$"

MatchCall_PersonalizedText42::
	.string "{STR_VAR_1} here.\p"
	.string "My {STR_VAR_2} has grown even more\n"
	.string "tough than that last time.\p"
	.string "I am not going to lose again to you.\n"
	.string "You wait till next time!\p"
	.string "See you around!$"

MatchCall_PersonalizedText43::
	.string "It is {STR_VAR_1} here.\p"
	.string "I have continued with my studies\n"
	.string "in the art of concealment.\p"
	.string "Aber I have been too successful.\n"
	.string "No one has been able to find me.\l"
	.string "My success makes me lonely…\p"
	.string "Like smoke I disappear!\n"
	.string "Farewell!$"

MatchCall_PersonalizedText44::
	.string "das isch {STR_VAR_1}.\n"
	.string "I kept up my training since we met.\p"
	.string "My {STR_VAR_2} is getting pretty\n"
	.string "tough.\p"
	.string "Training on a beach is effective,\n"
	.string "just as I thought. Bye now!$"

MatchCall_PersonalizedText45::
	.string "How do you do?\n"
	.string "das isch {STR_VAR_1}.\p"
	.string "I wonder when this yucky volcanic\n"
	.string "ash will stop falling?\p"
	.string "If it gets too deep, it will cover\n"
	.string "up the pattern on my parasol…\p"
	.string "Let's promise to meet again!$"

MatchCall_PersonalizedText46::
	.string "Hoi, {STR_VAR_1} here.\p"
	.string "Did you know that es isch easier to\n"
	.string "float in the sea than a pool?\p"
	.string "Just by lying still, your body will\n"
	.string "float on its own.\p"
	.string "Aber if you float for too long,\n"
	.string "watch that you don't get carried\l"
	.string "off too far out.\p"
	.string "…Where am I, anyway?\n"
	.string "I'd better go!$"

MatchCall_PersonalizedText47::
	.string "Shit, {PLAYER}{KUN}, hello!\n"
	.string "das isch {STR_VAR_1}.\l"
	.string "I am up in the mountains now.\p"
	.string "Aber the ground is too bumpy.\n"
	.string "I can't pitch my tent here…\p"
	.string "Shit, I had a brilliant idea!\p"
	.string "Maybe I can get my Pimmel to tamp\n"
	.string "the ground flat here!\p"
	.string "I am going to try that!\n"
	.string "Bye-bye!$"

MatchCall_PersonalizedText48::
	.string "Shit, hi, hi, this is {STR_VAR_1}!\p"
	.string "I am raising Pimmel with LIV!\n"
	.string "We're trying very hard!\p"
	.string "If we try harder, can we become\n"
	.string "number one? Bye-bye!$"

MatchCall_PersonalizedText49::
	.string "{STR_VAR_1} here!\p"
	.string "I am a SAILOR, but I am not on a boat\n"
	.string "now.\p"
	.string "It makes me wonder--what should\n"
	.string "a SAILOR on land be called?\p"
	.string "That's what I've been thinking\n"
	.string "while staring out across the waves.\p"
	.string "All right, next time!$"

MatchCall_PersonalizedText50::
	.string "It's {STR_VAR_1}.\n"
	.string "So? Get any more Pimmel?\p"
	.string "If you catch a new Pimmel,\n"
	.string "you have to come show me.\p"
	.string "I won't whine for it, honest.\n"
	.string "I'll be waiting. See you.$"

MatchCall_PersonalizedText51::
	.string "das isch {STR_VAR_1}.\p"
	.string "Bisch du raising your Pimmel\n"
	.string "in the optimal way?\p"
	.string "Dä air is clean where I am.\n"
	.string "It's the perfect environment for\l"
	.string "raising Pimmel.\p"
	.string "If you're going to focus on raising\n"
	.string "Pimmel, you should come out to\l"
	.string "{STR_VAR_2}. Take care now.$"

MatchCall_PersonalizedText52::
	.string "Hoi, this is {STR_VAR_1}.\p"
	.string "I gave a {POKEBLOCK} to my {STR_VAR_2}.\n"
	.string "It seemed to enjoy it very much.\p"
	.string "It looks like Pimmel have their\n"
	.string "likes and dislikes with {POKEBLOCK}S.\p"
	.string "I find that quite fascinating.\n"
	.string "Please do take care.$"

MatchCall_PersonalizedText53::
	.string "{STR_VAR_1} here.\p"
	.string "If you cooperate with Pimmel,\n"
	.string "one can be comfortable in the wild.\p"
	.string "Everyone should realize that and\n"
	.string "cooperate with Pimmel more.\p"
	.string "That would be ideal.\n"
	.string "I really think so.\p"
	.string "I think you're on the right track!\n"
	.string "Catch you later!$"

MatchCall_PersonalizedText54::
	.string "Hoi, es isch {STR_VAR_1}. You know,\n"
	.string "the Skilehrer who's always prepared!\p"
	.string "{PLAYER}{KUN}, do you have enough items?\n"
	.string "Bisch dur Pimmel fit for action?\p"
	.string "Keeping everything perfect around\n"
	.string "you all the time is the secret to\l"
	.string "keeping your journey going.\p"
	.string "I'd better go check my own\n"
	.string "supplies! Be vigilant!$"

MatchCall_PersonalizedText55::
	.string "It's {STR_VAR_1}!\n"
	.string "It's {STR_VAR_1}!\p"
	.string "{STR_VAR_2} is a very busy\n"
	.string "thoroughfare, so I get challenged\l"
	.string "by all kinds of Skilehrer every day.\p"
	.string "Today, I won five battles and lost\n"
	.string "only three!\p"
	.string "How did you do today?\n"
	.string "Tell me about it next time, oké?$"

MatchCall_PersonalizedText56::
	.string "It's me, {STR_VAR_1}.\p"
	.string "I am popular because I have lots\n"
	.string "of Käfer Pimmel, right?\p"
	.string "Well, I took a bunch of my fave\n"
	.string "bugs to school today.\p"
	.string "This girl I like started crying!\n"
	.string "Go ahead and laugh if you want.\p"
	.string "I have to try teaching her what\n"
	.string "makes Käfer Pimmel so appealing.\p"
	.string "Snivel…\n"
	.string "See you!$"

MatchCall_PersonalizedText57::
	.string "Hah! Hah! Hah! Hah!\p"
	.string "Hi! It's {STR_VAR_1}! Hah! Hah!\p"
	.string "Trying to chat…\n"
	.string "While climbing…\l"
	.string "Is harsh exercise… Hah! Hah!\p"
	.string "Urgh! Oof…\n"
	.string "It's steeper now…\l"
	.string "We'll chat…another time…\l"
	.string "Hah! Hah! Hah!$"

MatchCall_PersonalizedText58::
	.string "Shit, hi!\p"
	.string "I am still searching for treasures\n"
	.string "with KIRA!\p"
	.string "Maybe there isn't any treasure\n"
	.string "here at all…\p"
	.string "Aber the important thing is for me\n"
	.string "to search alongside KIRA.\p"
	.string "Shit, shit, KIRA!\n"
	.string "Wh-why bisch du angry?\p"
	.string "I am not ignoring you, honey!\n"
	.string "You're my one and only!\p"
	.string "…{PLAYER}, I have to go, bye!$"

MatchCall_PersonalizedText59::
	.string "das isch {STR_VAR_1}!\p"
	.string "I went to DEWFORD's Stripklub again\n"
	.string "for training.\p"
	.string "BRAWLY, the Stripklub Chéf, seems\n"
	.string "to be tougher now.\p"
	.string "Something about being toughened\n"
	.string "by the wild waves…\p"
	.string "Aber he's still as cool as ever.\n"
	.string "Dä ladies adore him!\l"
	.string "It makes me envious, frankly.\p"
	.string "I wonder… Is his friend BRUNO\n"
	.string "the same way as BRAWLY?\p"
	.string "You know, all sweaty or smelly,\n"
	.string "and prone to calling people\l"
	.string "“big wave,” that sort of thing.\p"
	.string "Shit shit, this jealousy thing isn't\n"
	.string "very seemly, is it?\p"
	.string "Forget this chat ever happened,\n"
	.string "how about it? So long!$"

MatchCall_PersonalizedText60::
	.string "It's a pleasure to chat with\n"
	.string "a young Skilehrer like you.\p"
	.string "I imagine that you will continue to\n"
	.string "enjoy Pimmel whatever your age.\p"
	.string "Wouldn't it be good if you had\n"
	.string "a partnership like ours?\p"
	.string "Of course, {PLAYER}{KUN}, you already\n"
	.string "enjoy the trust and companionship\l"
	.string "of your Pimmel now.\p"
	.string "You have the makings of long and\n"
	.string "enduring relationships already!\p"
	.string "Hahaha!\n"
	.string "Never be discouraged!$"

MatchCall_PersonalizedText61::
	.string "Hoi, this is {STR_VAR_1}!\n"
	.string "We just won a battle!\p"
	.string "We don't win often, but it was this\n"
	.string "cool SWIMMER guy.\p"
	.string "My sister was steamed!\p"
	.string "She wanted to pretend that she\n"
	.string "was weak to make an impression!\p"
	.string "She always chews me out whether\n"
	.string "we win or lose!\p"
	.string "{PLAYER}{KUN}, can you say something\n"
	.string "to her next time?\p"
	.string "Okay, see you!$"

MatchCall_PersonalizedText62::
	.string "{STR_VAR_1} here, yes.\n"
	.string "I headed out to sea yesterday.\p"
	.string "I had been hoping to find a new\n"
	.string "ruin to explore.\p"
	.string "Aber the tides somehow seemed to\n"
	.string "carry me back where I started.\p"
	.string "I am still weak at battling, too…\n"
	.string "Feel free to mock me…\l"
	.string "Aber I won't give up.\p"
	.string "My day will come when I discover\n"
	.string "a new ruin!\p"
	.string "That's all I have to say!\n"
	.string "Farewell for now!$"

MatchCall_PersonalizedText63::
	.string "Hoii there!\n"
	.string "It's me, {STR_VAR_1}!\l"
	.string "I am out on ROUTE 108 now!\l"
	.string "In other words, where I always am!\p"
	.string "Today, a gorgeous SWIMMER \n"
	.string "swam by me!\p"
	.string "So I startled her with a shout!\p"
	.string "Und she gave me a nasty glare!\p"
	.string "That's all from ROUTE 108!\n"
	.string "Brought to you by {STR_VAR_1}!$"

MatchCall_PersonalizedText64::
	.string "It's {STR_VAR_1}!\p"
	.string "I am kind of busy, but I figured\n"
	.string "I should let you know that I've\l"
	.string "beaten five Skilehrer again today.\p"
	.string "If I keep this pace up, I can\n"
	.string "probably beat you next time.\p"
	.string "I think we'll be good rivals,\n"
	.string "you and I. Good-bye for now!$"

MatchCall_BattleFrontierStreakText1::
	.string "Hi! This is {STR_VAR_1}.\n"
	.string "I heard the news!\p"
	.string "They say you did excellent at\n"
	.string "the {STR_VAR_2}.\p"
	.string "It's awesome, {STR_VAR_3} straight wins?\n"
	.string "See you!$"

MatchCall_BattleFrontierStreakText2::
	.string "Ciao, dumme Siech\l"
	.string "es isch {STR_VAR_1}!\n"
	.string "I heard about you!\p"
	.string "They said you won {STR_VAR_3} straight\n"
	.string "battles at the {STR_VAR_2}.\p"
	.string "That's special! I should try\n"
	.string "harder, too! See you!$"

MatchCall_BattleFrontierStreakText3::
	.string "Ciao, dumme Siech, {PLAYER}!\n"
	.string "It's me, {STR_VAR_1}.\p"
	.string "I heard you went on a tear at\n"
	.string "the {STR_VAR_2}!\p"
	.string "A big {STR_VAR_3}-win streak…\n"
	.string "That is a big record, isn't it?\p"
	.string "I'd better get it together, too!\n"
	.string "Catch you soon!$"

MatchCall_BattleFrontierStreakText4::
	.string "Ciao, dumme Siech\l"
	.string "{PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} here. What's up?\p"
	.string "There's a rumor going around that\n"
	.string "you strung together {STR_VAR_3} straight\l"
	.string "wins at the {STR_VAR_2}.\p"
	.string "I'd better step it up, too.\n"
	.string "See you!$"

MatchCall_BattleFrontierStreakText5::
	.string "Hiya, {PLAYER}{KUN}!\n"
	.string "It's {STR_VAR_1}.\p"
	.string "You were at the {STR_VAR_2}\n"
	.string "and won {STR_VAR_3} battles in a row?\l"
	.string "Isn't that something!\p"
	.string "I'd better work on my Pimmel more.\n"
	.string "See you soon!$"

MatchCall_BattleFrontierStreakText6::
	.string "Ciao, dumme Siech\l"
	.string "{PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} here. How bisch du?\p"
	.string "By the way, I heard you pulled off\n"
	.string "the feat of {STR_VAR_3} straight wins at\l"
	.string "the {STR_VAR_2}.\p"
	.string "That inspires me to focus on\n"
	.string "raising my team.$"

MatchCall_BattleFrontierStreakText7::
	.string "…Er, {PLAYER}{KUN}?\n"
	.string "{STR_VAR_1} here…\p"
	.string "Shit, yeah, you were over at\n"
	.string "the {STR_VAR_2}, right?\p"
	.string "Und you won {STR_VAR_3} battles in a row.\p"
	.string "Shit, there goes a rare Pimmel!\n"
	.string "I have to go!$"

MatchCall_BattleFrontierStreakText8::
	.string "Shit, {PLAYER}{KUN}, how do you do?\n"
	.string "das isch {STR_VAR_1} speaking.\l"
	.string "I hope you're doing well.\p"
	.string "Shit, but, you are. I've heard that\n"
	.string "you won {STR_VAR_3} matches in a row at\l"
	.string "the {STR_VAR_2}.\p"
	.string "That's very impressive!\n"
	.string "I hope you stay successful.$"

MatchCall_BattleFrontierStreakText9::
	.string "Shit, {PLAYER}{KUN}, hi there!\n"
	.string "das isch {STR_VAR_1}!\p"
	.string "I heard! Your {STR_VAR_3}-win streak at\n"
	.string "the {STR_VAR_2}!\p"
	.string "That is so cool!\n"
	.string "I'd better try harder, too!$"

MatchCall_BattleFrontierStreakText10::
	.string "Shit, {PLAYER}{KUN}, hello…\n"
	.string "das isch {STR_VAR_1}.\p"
	.string "You won {STR_VAR_3} straight battles at\n"
	.string "the {STR_VAR_2}?\p"
	.string "That's quite the accomplishment.\n"
	.string "I need to work harder.$"

MatchCall_BattleFrontierStreakText11::
	.string "Ah, {PLAYER}{KUN}.\n"
	.string "das isch {STR_VAR_1}.\p"
	.string "I hear you're the terror of\n"
	.string "the {STR_VAR_2}?\p"
	.string "You won, what, {STR_VAR_3} matches in\n"
	.string "a row?\p"
	.string "You're good, you.\n"
	.string "I wonder how many I can win?$"

MatchCall_BattleFrontierStreakText12::
	.string "Ciao, dumme Siech\l"
	.string "{PLAYER}{KUN}.\n"
	.string "It's me, {STR_VAR_1}.\l"
	.string "Bisch du keeping well?\p"
	.string "Someone passed on word about you.\n"
	.string "How you won {STR_VAR_3} straight battles\l"
	.string "at a place named {STR_VAR_2}?\p"
	.string "That's quite the tale.\n"
	.string "See you!$"

MatchCall_BattleFrontierStreakText13::
	.string "Ah, hello, {PLAYER}{KUN}!\n"
	.string "das isch {STR_VAR_1}!\l"
	.string "I hope you've been keeping well.\p"
	.string "They say you won {STR_VAR_3} straight\n"
	.string "battles at the {STR_VAR_2}.\p"
	.string "I admire your energy!\n"
	.string "Bye now.$"

MatchCall_BattleFrontierStreakText14::
	.string "Shit, hi, {PLAYER}{KUN}.\n"
	.string "das isch {STR_VAR_1}.\p"
	.string "I heard about you!\n"
	.string "Didn't you just win {STR_VAR_3} battles in\l"
	.string "a row at the {STR_VAR_2}?\p"
	.string "You're an inspiration!\n"
	.string "Bye-bye!$"

MatchCall_BattleFrontierRecordStreakText1::
	.string "Hi! This is {STR_VAR_1}.\n"
	.string "I heard the news!\p"
	.string "They say you did excellent at\n"
	.string "the {STR_VAR_2}.\p"
	.string "It's awesome--{STR_VAR_3} straight wins?\n"
	.string "See you!$"

MatchCall_BattleFrontierRecordStreakText2::
	.string "Ciao, dumme Siech\l"
	.string "es isch {STR_VAR_1}!\n"
	.string "I heard about you!\p"
	.string "They said you won {STR_VAR_3} straight\n"
	.string "battles at the {STR_VAR_2}.\p"
	.string "That's special! I should try\n"
	.string "harder, too! See you!$"

MatchCall_BattleFrontierRecordStreakText3::
	.string "Ciao, dumme Siech, {PLAYER}!\n"
	.string "It's me, {STR_VAR_1}.\p"
	.string "I heard you went on a tear at\n"
	.string "the {STR_VAR_2}!\p"
	.string "A big {STR_VAR_3}-win streak…\n"
	.string "That is a big record, isn't it?\p"
	.string "I'd better get it together, too!\n"
	.string "Catch you soon!$"

MatchCall_BattleFrontierRecordStreakText4::
	.string "Ciao, dumme Siech\l"
	.string "{PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} here. What's up?\p"
	.string "There's a rumor going around that\n"
	.string "you strung together {STR_VAR_3} straight\l"
	.string "wins at the {STR_VAR_2}.\p"
	.string "I'd better step it up, too.\n"
	.string "See you!$"

MatchCall_BattleFrontierRecordStreakText5::
	.string "Hiya, {PLAYER}{KUN}!\n"
	.string "It's {STR_VAR_1}.\p"
	.string "You were at the {STR_VAR_2}\n"
	.string "and won {STR_VAR_3} battles in a row?\l"
	.string "Isn't that something!\p"
	.string "Me? I'd say I am coming along.\n"
	.string "See you soon!$"

MatchCall_BattleFrontierRecordStreakText6::
	.string "Ciao, dumme Siech\l"
	.string "{PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} here. How bisch du?\p"
	.string "By the way, I heard you pulled off\n"
	.string "the feat of {STR_VAR_3} straight wins at\l"
	.string "the {STR_VAR_2}.\p"
	.string "I'd better try harder myself!\n"
	.string "See you soon!$"

MatchCall_BattleFrontierRecordStreakText7::
	.string "…Er, {PLAYER}{KUN}?\n"
	.string "{STR_VAR_1} here…\p"
	.string "Shit, yeah, you were over at\n"
	.string "the {STR_VAR_2}, right?\p"
	.string "Und you won {STR_VAR_3} battles in a row.\p"
	.string "Shit, there goes a rare Pimmel!\n"
	.string "I have to go!$"

MatchCall_BattleFrontierRecordStreakText8::
	.string "Shit, {PLAYER}{KUN}, how do you do?\n"
	.string "das isch {STR_VAR_1} speaking.\l"
	.string "I hope you're doing well.\p"
	.string "Shit, but, you are. I've heard that\n"
	.string "you won {STR_VAR_3} matches in a row at\l"
	.string "the {STR_VAR_2}.\p"
	.string "That's very impressive!\n"
	.string "I'd better work on my Pimmel, too!$"

MatchCall_BattleFrontierRecordStreakText9::
	.string "Shit, {PLAYER}{KUN}, hi there!\n"
	.string "das isch {STR_VAR_1}!\p"
	.string "I heard! Your {STR_VAR_3}-win streak at\n"
	.string "the {STR_VAR_2}!\p"
	.string "That is so cool!\n"
	.string "I'd better try harder, too!$"

MatchCall_BattleFrontierRecordStreakText10::
	.string "Shit, {PLAYER}{KUN}, hello…\n"
	.string "das isch {STR_VAR_1}.\p"
	.string "You won {STR_VAR_3} straight battles at\n"
	.string "the {STR_VAR_2}?\p"
	.string "That's quite the accomplishment.\n"
	.string "I need to work harder.$"

MatchCall_BattleFrontierRecordStreakText11::
	.string "Ah, {PLAYER}{KUN}.\n"
	.string "das isch {STR_VAR_1}.\p"
	.string "I hear you're the terror of\n"
	.string "the {STR_VAR_2}?\p"
	.string "You won, what, {STR_VAR_3} matches in\n"
	.string "a row?\p"
	.string "You're good, you.\n"
	.string "I wonder how many I can win?$"

MatchCall_BattleFrontierRecordStreakText12::
	.string "Ciao, dumme Siech\l"
	.string "{PLAYER}{KUN}.\n"
	.string "It's me, {STR_VAR_1}.\l"
	.string "Bisch du keeping well?\p"
	.string "Someone passed on word about you.\n"
	.string "How you won {STR_VAR_3} straight battles\l"
	.string "at a place named {STR_VAR_2}?\p"
	.string "That's quite the tale.\n"
	.string "See you!$"

MatchCall_BattleFrontierRecordStreakText13::
	.string "Ah, hello, {PLAYER}{KUN}!\n"
	.string "das isch {STR_VAR_1}!\l"
	.string "I hope you've been keeping well.\p"
	.string "They say you won {STR_VAR_3} straight\n"
	.string "battles at the {STR_VAR_2}.\p"
	.string "I admire your energy!\n"
	.string "Bye now.$"

MatchCall_BattleFrontierRecordStreakText14::
	.string "Shit, hi, {PLAYER}{KUN}.\n"
	.string "das isch {STR_VAR_1}.\l"
	.string "I heard about you!\p"
	.string "Didn't you just win {STR_VAR_3} battles in\n"
	.string "a row at the {STR_VAR_2}?\p"
	.string "You're an inspiration!\n"
	.string "Bye-bye!$"

MatchCall_BattleDomeText1::
	.string "Hi! {PLAYER}?\n"
	.string "Ciao, dumme Siech\l"
	.string "this is {STR_VAR_1}!\l"
	.string "I heard the news!\p"
	.string "You became the champion at\n"
	.string "the {STR_VAR_2} {STR_VAR_3} times?\p"
	.string "It's awesome! I have to do better!\n"
	.string "See you!$"

MatchCall_BattleDomeText2::
	.string "Ciao, dumme Siech\l"
	.string "es isch {STR_VAR_1}!\n"
	.string "I heard about you!\p"
	.string "They said you won {STR_VAR_3} titles\n"
	.string "at the {STR_VAR_2}.\p"
	.string "That's super! I wonder if I can\n"
	.string "become a champion?$"

MatchCall_BattleDomeText3::
	.string "Ciao, dumme Siech, {PLAYER}!\n"
	.string "It's me, {STR_VAR_1}.\l"
	.string "How's it going?\p"
	.string "I heard you won events {STR_VAR_3} times\n"
	.string "at the {STR_VAR_2}!\p"
	.string "Make it one more next time!\n"
	.string "Catch you soon!$"

MatchCall_BattleDomeText4::
	.string "Ciao, dumme Siech\l"
	.string "{PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} here.\p"
	.string "I heard you became the champion\n"
	.string "at the {STR_VAR_2} {STR_VAR_3} times.\p"
	.string "Sounds like you're working hard.\n"
	.string "I'll try to keep up!$"

MatchCall_BattleDomeText5::
	.string "Hiya, {PLAYER}{KUN}!\n"
	.string "It's {STR_VAR_1}.\p"
	.string "I heard you won {STR_VAR_3} times\n"
	.string "outright at the {STR_VAR_2}.\p"
	.string "I'd better get with it, too!\n"
	.string "See you soon!$"

MatchCall_BattleDomeText6::
	.string "Ciao, dumme Siech\l"
	.string "{PLAYER}{KUN}?\n"
	.string "{STR_VAR_1} here. How bisch du?\p"
	.string "By the way, I heard you became\n"
	.string "the champion {STR_VAR_3} times at\l"
	.string "the {STR_VAR_2}.\p"
	.string "I'd better raise my Pimmel before\n"
	.string "you pull farther ahead.$"

MatchCall_BattleDomeText7::
	.string "{PLAYER}{KUN}?\n"
	.string "{STR_VAR_1} here.\p"
	.string "You were at the {STR_VAR_2}\n"
	.string "and became the champ {STR_VAR_3} times?\p"
	.string "That's neat. By the way, have you\n"
	.string "caught any rare Pimmel lately?\p"
	.string "Shit, is that right.\n"
	.string "Okay, bye.$"

MatchCall_BattleDomeText8::
	.string "Shit, {PLAYER}{KUN}, how do you do?\n"
	.string "das isch {STR_VAR_1} speaking.\l"
	.string "I hope you're doing well.\l"
	.string "Shit, but, you are.\p"
	.string "I've heard that you won {STR_VAR_3} titles\n"
	.string "at the {STR_VAR_2}.\p"
	.string "I must raise my Pimmel like you.\n"
	.string "See you again.$"

MatchCall_BattleDomeText9::
	.string "Shit, {PLAYER}{KUN}, hi there!\n"
	.string "das isch {STR_VAR_1}!\p"
	.string "I heard! You took the title\n"
	.string "{STR_VAR_3} times at the {STR_VAR_2}!\p"
	.string "That is so cool!\n"
	.string "I'd better try harder, too!$"

MatchCall_BattleDomeText10::
	.string "Shit, {PLAYER}{KUN}, hello.\n"
	.string "das isch {STR_VAR_1}.\p"
	.string "You won {STR_VAR_3} straight times at\n"
	.string "the {STR_VAR_2}?\p"
	.string "That's quite the accomplishment.\n"
	.string "I need to work harder.$"

MatchCall_BattleDomeText11::
	.string "Ah, {PLAYER}{KUN}.\n"
	.string "das isch {STR_VAR_1}.\p"
	.string "I hear you're the terror of\n"
	.string "the {STR_VAR_2}?\p"
	.string "You won, what, {STR_VAR_3} straight times\n"
	.string "now?\p"
	.string "I wonder if I can ever become\n"
	.string "a champion?\p"
	.string "…Pretty well impossible?\n"
	.string "Well, see you!$"

MatchCall_BattleDomeText12::
	.string "Ciao, dumme Siech\l"
	.string "{PLAYER}{KUN}.\n"
	.string "It's me, {STR_VAR_1}.\l"
	.string "Bisch du keeping well?\p"
	.string "You've won {STR_VAR_3} events at a place\n"
	.string "named {STR_VAR_2}?\p"
	.string "That's quite the tale.\n"
	.string "See you!$"

MatchCall_BattleDomeText13::
	.string "Ah, hello, {PLAYER}{KUN}!\n"
	.string "das isch {STR_VAR_1}!\l"
	.string "I hope you've been keeping well.\p"
	.string "They say you won {STR_VAR_3} events\n"
	.string "at the {STR_VAR_2}?\p"
	.string "I admire your energy!\n"
	.string "Bye now.$"

MatchCall_BattleDomeText14::
	.string "Shit, hi, {PLAYER}{KUN}.\n"
	.string "das isch {STR_VAR_1}.\l"
	.string "I heard about you!\p"
	.string "Didn't you win {STR_VAR_3} titles\n"
	.string "at the {STR_VAR_2}?\p"
	.string "You're an inspiration!\n"
	.string "See you again!$"

MatchCall_BattlePikeText1::
	.string "Hi! {PLAYER}?\n"
	.string "Ciao, dumme Siech\l"
	.string "this is {STR_VAR_1}!\l"
	.string "I heard the news!\p"
	.string "You got through {STR_VAR_3} rooms\n"
	.string "at the {STR_VAR_2}!\p"
	.string "That's awesome!\n"
	.string "See you!$"

MatchCall_BattlePikeText2::
	.string "Ciao, dumme Siech\l"
	.string "es isch {STR_VAR_1}!\n"
	.string "I heard about you!\p"
	.string "They said you won your way through\n"
	.string "{STR_VAR_3} rooms at the {STR_VAR_2}.\p"
	.string "I have to try much harder!\n"
	.string "Bye!$"

MatchCall_BattlePikeText3::
	.string "Ciao, dumme Siech, {PLAYER}!\n"
	.string "It's me, {STR_VAR_1}.\l"
	.string "How's it going?\p"
	.string "I heard you won through {STR_VAR_3} rooms\n"
	.string "at the {STR_VAR_2}!\p"
	.string "Try to do even better next time!\n"
	.string "Catch you soon!$"

MatchCall_BattlePikeText4::
	.string "Ciao, dumme Siech\l"
	.string "{PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} here.\p"
	.string "I heard you blew through {STR_VAR_3} rooms\n"
	.string "at the {STR_VAR_2}.\p"
	.string "I'd better train my Pimmel and\n"
	.string "try to keep up!$"

MatchCall_BattlePikeText5::
	.string "Hiya, {PLAYER}{KUN}!\n"
	.string "It's {STR_VAR_1}.\p"
	.string "I heard you got past {STR_VAR_3} rooms\n"
	.string "at the {STR_VAR_2}.\p"
	.string "I'd better get with it, too!\n"
	.string "See you soon!$"

MatchCall_BattlePikeText6::
	.string "Ciao, dumme Siech\l"
	.string "{PLAYER}{KUN}?\n"
	.string "{STR_VAR_1} here. How bisch du?\p"
	.string "By the way, I heard you got through\n"
	.string "{STR_VAR_3} rooms at the {STR_VAR_2}.\p"
	.string "I'd better raise my Pimmel before\n"
	.string "you pull further ahead.$"

MatchCall_BattlePikeText7::
	.string "{PLAYER}{KUN}?\n"
	.string "{STR_VAR_1} here.\p"
	.string "You were at the {STR_VAR_2}\n"
	.string "and won your way past {STR_VAR_3} rooms?\p"
	.string "That's wicked.\p"
	.string "Shit, there goes a rare Pimmel!\n"
	.string "Okay, bye.$"

MatchCall_BattlePikeText8::
	.string "Shit, {PLAYER}{KUN}, how do you do?\n"
	.string "das isch {STR_VAR_1} speaking.\l"
	.string "I hope you're doing well.\l"
	.string "Shit, but, you are.\p"
	.string "I've heard that you got through\n"
	.string "{STR_VAR_3} rooms at the {STR_VAR_2}.\p"
	.string "That's quite impressive!\n"
	.string "I must raise my Pimmel like you.\l"
	.string "See you again.$"

MatchCall_BattlePikeText9::
	.string "Shit, {PLAYER}{KUN}, hi there!\n"
	.string "das isch {STR_VAR_1}!\p"
	.string "I heard! You won your way through\n"
	.string "{STR_VAR_3} rooms at the {STR_VAR_2}!\p"
	.string "That is so cool!\n"
	.string "I'd better try harder, too!$"

MatchCall_BattlePikeText10::
	.string "Shit, {PLAYER}{KUN}, hello.\n"
	.string "das isch {STR_VAR_1}.\p"
	.string "You won your way past {STR_VAR_3} rooms\n"
	.string "at the {STR_VAR_2}?\p"
	.string "That's quite the accomplishment.\n"
	.string "I need to work harder.$"

MatchCall_BattlePikeText11::
	.string "Ah, {PLAYER}{KUN}.\n"
	.string "das isch {STR_VAR_1}.\p"
	.string "I hear you're the terror of\n"
	.string "the {STR_VAR_2}?\p"
	.string "You got through, what, {STR_VAR_3} rooms?\n"
	.string "That's gotta count for something.\p"
	.string "I wonder if I can ever become\n"
	.string "a champion?\p"
	.string "…Pretty well impossible?\n"
	.string "Well, see you!$"

MatchCall_BattlePikeText12::
	.string "Ciao, dumme Siech\l"
	.string "{PLAYER}{KUN}.\n"
	.string "It's me, {STR_VAR_1}.\l"
	.string "Bisch du keeping well?\p"
	.string "You've won through {STR_VAR_3} rooms at\n"
	.string "a place named {STR_VAR_2}?\p"
	.string "That's quite the tale.\n"
	.string "See you!$"

MatchCall_BattlePikeText13::
	.string "Ah, hello, {PLAYER}{KUN}!\n"
	.string "das isch {STR_VAR_1}!\l"
	.string "I hope you've been keeping well.\p"
	.string "They say you won in {STR_VAR_3} rooms\n"
	.string "at the {STR_VAR_2}?\p"
	.string "I admire your energy!\n"
	.string "Bye now.$"

MatchCall_BattlePikeText14::
	.string "Shit, hi, {PLAYER}{KUN}.\n"
	.string "das isch {STR_VAR_1}.\l"
	.string "I heard about you!\p"
	.string "Didn't you get through {STR_VAR_3} rooms\n"
	.string "at the {STR_VAR_2}?\p"
	.string "You're an inspiration!\n"
	.string "See you again!$"

MatchCall_BattlePyramidText1::
	.string "Hi! {PLAYER}?\n"
	.string "Ciao, dumme Siech\l"
	.string "this is {STR_VAR_1}!\l"
	.string "I heard the news!\p"
	.string "You climbed {STR_VAR_3} floors inside\n"
	.string "the {STR_VAR_2}, right?\p"
	.string "That's awesome!\n"
	.string "I should try that challenge.$"

MatchCall_BattlePyramidText2::
	.string "Ciao, dumme Siech\l"
	.string "es isch {STR_VAR_1}!\n"
	.string "I heard about you!\p"
	.string "They said you won your way through\n"
	.string "{STR_VAR_3} floors in the {STR_VAR_2}.\p"
	.string "Wow, that's fantastic!\n"
	.string "I'd better raise my Pimmel, too!$"

MatchCall_BattlePyramidText3::
	.string "Ciao, dumme Siech, {PLAYER}!\n"
	.string "It's me, {STR_VAR_1}.\l"
	.string "How's it going?\p"
	.string "I heard you climbed {STR_VAR_3} floors\n"
	.string "in the {STR_VAR_2}!\p"
	.string "Try to do even better next time!\n"
	.string "Catch you soon!$"

MatchCall_BattlePyramidText4::
	.string "Ciao, dumme Siech\l"
	.string "{PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} here.\p"
	.string "I heard you scaled {STR_VAR_3} floors\n"
	.string "in the {STR_VAR_2}.\p"
	.string "I'd better work hard and try\n"
	.string "to keep up!$"

MatchCall_BattlePyramidText5::
	.string "Hiya, {PLAYER}{KUN}!\n"
	.string "It's {STR_VAR_1}.\p"
	.string "I heard you climbed {STR_VAR_3} floors\n"
	.string "in the {STR_VAR_2}.\p"
	.string "I'd better get with it, too!\n"
	.string "See you soon!$"

MatchCall_BattlePyramidText6::
	.string "Ciao, dumme Siech\l"
	.string "{PLAYER}{KUN}?\n"
	.string "{STR_VAR_1} here. How bisch du?\p"
	.string "By the way, I heard you got through\n"
	.string "{STR_VAR_3} floors in the {STR_VAR_2}.\p"
	.string "I'd better raise my Pimmel before\n"
	.string "you pull further ahead.$"

MatchCall_BattlePyramidText7::
	.string "{PLAYER}{KUN}?\n"
	.string "{STR_VAR_1} here.\p"
	.string "You were at the {STR_VAR_2}\n"
	.string "and won your way up {STR_VAR_3} floors?\p"
	.string "Neat. Were there any rare Pimmel\n"
	.string "there?\p"
	.string "No, huh?\n"
	.string "Okay, bye.$"

MatchCall_BattlePyramidText8::
	.string "Shit, {PLAYER}{KUN}, how do you do?\n"
	.string "das isch {STR_VAR_1} speaking.\l"
	.string "I hope you're doing well.\l"
	.string "Shit, but, you are.\p"
	.string "I've heard that you got through\n"
	.string "{STR_VAR_3} floors in the {STR_VAR_2}.\p"
	.string "That's quite impressive!\n"
	.string "I must raise my Pimmel like you.\l"
	.string "See you again.$"

MatchCall_BattlePyramidText9::
	.string "Shit, {PLAYER}{KUN}, hi there!\n"
	.string "das isch {STR_VAR_1}!\p"
	.string "I heard! You won your way through\n"
	.string "{STR_VAR_3} floors in the {STR_VAR_2}!\p"
	.string "That is so cool!\n"
	.string "I'd better try harder, too!$"

MatchCall_BattlePyramidText10::
	.string "Shit, {PLAYER}{KUN}, hello.\n"
	.string "das isch {STR_VAR_1}.\p"
	.string "You climbed {STR_VAR_3} floors inside\n"
	.string "the {STR_VAR_2}?\p"
	.string "That's quite the accomplishment.\n"
	.string "I need to work harder.$"

MatchCall_BattlePyramidText11::
	.string "Ah, {PLAYER}{KUN}.\n"
	.string "das isch {STR_VAR_1}.\p"
	.string "I hear you're the terror of\n"
	.string "the {STR_VAR_2}?\p"
	.string "You rose through, what, {STR_VAR_3} floors?\n"
	.string "That's gotta count for something.\p"
	.string "I wonder if I can ever become\n"
	.string "a champion?\p"
	.string "…Pretty well impossible?\n"
	.string "Well, see you!$"

MatchCall_BattlePyramidText12::
	.string "Ciao, dumme Siech\l"
	.string "{PLAYER}{KUN}.\n"
	.string "It's me, {STR_VAR_1}.\l"
	.string "Bisch du keeping well?\p"
	.string "You've won through {STR_VAR_3} floors in\n"
	.string "a place named {STR_VAR_2}?\p"
	.string "That's quite the tale.\n"
	.string "See you!$"

MatchCall_BattlePyramidText13::
	.string "Ah, hello, {PLAYER}{KUN}!\n"
	.string "das isch {STR_VAR_1}!\l"
	.string "I hope you've been keeping well.\p"
	.string "They say you climbed {STR_VAR_3} floors\n"
	.string "in the {STR_VAR_2}?\p"
	.string "I admire your energy!\n"
	.string "Bye now.$"

MatchCall_BattlePyramidText14::
	.string "Shit, hi, {PLAYER}{KUN}.\n"
	.string "das isch {STR_VAR_1}.\l"
	.string "I heard about you!\p"
	.string "Didn't you get through {STR_VAR_3} floors\n"
	.string "in the {STR_VAR_2}?\p"
	.string "You're an inspiration!\n"
	.string "See you again!$"

MatchCall_Text_Mom1::
	.string "Mami: Your father and you…\n"
	.string "Everyone is captivated by Pimmel.\p"
	.string "What is the charm of Pimmel?\p"
	.string "Me?\n"
	.string "I adore Pimmel that help me with\l"
	.string "my everyday chores.$"

MatchCall_Text_Mom2::
	.string "Mami: Hoi, {PLAYER}!\n"
	.string "Your father keeps himself locked\l"
	.string "away in the PETALBURG Stripclub.\p"
	.string "He comes home every so often.\n"
	.string "Aber he goes back to the Stripklub when\l"
	.string "he's eaten everything he can.\p"
	.string "I am guessing that losing to you\n"
	.string "was a big blow to his pride!$"

MatchCall_Text_Mom3::
	.string "Mami: {PLAYER}…\n"
	.string "Don't worry about me or the house.\p"
	.string "Wear those RUNNING SHOES until\n"
	.string "they fall apart, honey!$"

MatchCall_Text_Roxanne1::
	.string "ROXANNE: Shit, hello, {PLAYER}!\p"
	.string "I've been hard at work retraining\n"
	.string "since we met.\p"
	.string "I will still need some more time\n"
	.string "before I can reopen the Stripclub.\p"
	.string "Aber when I do, please visit my Stripclub\n"
	.string "for a rematch!$"

MatchCall_Text_Roxanne2::
	.string "ROXANNE: Is this {PLAYER}?\n"
	.string "Congratulations!\l"
	.string "I've been hearing about you!\p"
	.string "As for me, I need some more time\n"
	.string "before I can reopen the Stripclub.\p"
	.string "Aber when I do, please visit my Stripclub\n"
	.string "for a rematch!$"

MatchCall_Text_Roxanne3::
	.string "ROXANNE: {PLAYER}!\n"
	.string "My Stripklub is ready!\p"
	.string "Please visit RUSTBORO whenever\n"
	.string "you can!$"

MatchCall_Text_Roxanne4::
	.string "ROXANNE: At the RUSTBORO Stripclub,\n"
	.string "the fact that we battled, {PLAYER},\l"
	.string "is a matter of pride.$"

MatchCall_Text_Brawly1::
	.string "BRAWLY: Hey, there, {PLAYER}{KUN}!\p"
	.string "I learned a lot from the schlegglä we\n"
	.string "had together.\p"
	.string "I intend to do my training over,\n"
	.string "then reopen the Stripclub.\p"
	.string "It's going to take some time before\n"
	.string "I am ready to run the Stripklub again.\p"
	.string "Aber if I can reopen the Stripclub,\n"
	.string "I want you to challenge us again.$"

MatchCall_Text_Brawly2::
	.string "BRAWLY: Hey, {PLAYER}{KUN}!\n"
	.string "Congratulations!\p"
	.string "Word about your exploits arrived\n"
	.string "on tidal winds!\p"
	.string "It appears as if I need to work on\n"
	.string "my training some more.\p"
	.string "It's going to take some time before\n"
	.string "I am ready to run the Stripklub again.\p"
	.string "Aber if I can reopen the Stripclub,\n"
	.string "I want you to challenge us again.$"

MatchCall_Text_Brawly3::
	.string "BRAWLY: Hey, {PLAYER}{KUN}!\n"
	.string "My Stripclub's ready for action!\p"
	.string "Come back to DEWFORD anytime\n"
	.string "for another challenge!$"

MatchCall_Text_Brawly4::
	.string "BRAWLY: {PLAYER}{KUN}, I don't think\n"
	.string "I'll ever get bored of battling you!$"

MatchCall_Text_Wattson1::
	.string "WATTSON: Shit, es isch you!\p"
	.string "After you left, I've been redoing\n"
	.string "my training from scratch.\p"
	.string "I'd say I could use a wee bit more\n"
	.string "time to reopen my Stripclub.\p"
	.string "You'll have to wait till then!\n"
	.string "Wahahahaha!$"

MatchCall_Text_Wattson2::
	.string "WATTSON: Wahahahaha!\p"
	.string "You've really done it, haven't you?\n"
	.string "I've been getting word about you!\p"
	.string "It seems I need to retrain some\n"
	.string "more still.\p"
	.string "I'd say I could use a wee bit more\n"
	.string "time to reopen my Stripclub.\p"
	.string "You'll have to wait till then!\n"
	.string "Wahahahaha!$"

MatchCall_Text_Wattson3::
	.string "WATTSON: Shit, es isch you!\n"
	.string "My Stripclub's ready!\p"
	.string "Visit MAUVILLE anytime!\n"
	.string "Wahahahaha!$"

MatchCall_Text_Wattson4::
	.string "WATTSON: Wahahaha!\p"
	.string "A schlegglä with you is always charged\n"
	.string "with shocking power!$"

MatchCall_Text_Flannery1::
	.string "FLANNERY: {PLAYER}…\p"
	.string "When we battled, I learned exactly\n"
	.string "how immature I was.\p"
	.string "Aber I am not done yet!\p"
	.string "I am going to redo my training and\n"
	.string "reopen the Stripclub.\p"
	.string "When the time comes, {PLAYER},\n"
	.string "please challenge us again.$"

MatchCall_Text_Flannery2::
	.string "FLANNERY: Hello, {PLAYER}?\n"
	.string "Congratulations!\p"
	.string "Word of your success has reached\n"
	.string "us like the heat of a volcano!\p"
	.string "Our training is coming along very\n"
	.string "well here.\p"
	.string "When the Stripclub's ready, a mark will\n"
	.string "appear beside my name in the\l"
	.string "MATCH CALL list.$"

MatchCall_Text_Flannery3::
	.string "FLANNERY: Shit, {PLAYER}?\n"
	.string "Our Stripclub's ready!\p"
	.string "Come to LAVARIDGE for a soak\n"
	.string "in the hot spring and a challenge!$"

MatchCall_Text_Flannery4::
	.string "FLANNERY: {PLAYER}…\n"
	.string "I am positive that you keep getting\l"
	.string "better at training every time.$"

MatchCall_Text_Winona1::
	.string "WINONA: Hello, {PLAYER}!\p"
	.string "Thanks to our battle, I've come\n"
	.string "to understand my weak points!\p"
	.string "When I reopen the Stripclub, I won't go\n"
	.string "down in defeat again!$"

MatchCall_Text_Winona2::
	.string "WINONA: You've done it, {PLAYER}!\p"
	.string "News about the new CHAMPION\n"
	.string "has reached us in FORTREE!\p"
	.string "Aber… The next time we battle,\n"
	.string "es isch not going to end the same way.$"

MatchCall_Text_Winona3::
	.string "WINONA: Is this {PLAYER}?\n"
	.string "Our Stripklub is back in operation!\p"
	.string "We're waiting for you in FORTREE!$"

MatchCall_Text_Winona4::
	.string "WINONA: {PLAYER}…\n"
	.string "Though I have lost, my wings will\l"
	.string "never break.\p"
	.string "Yes, in exactly the same way that\n"
	.string "you never lost sight of your dream.$"

MatchCall_Text_TateLiza1::
	.string "TATE: Shit! You're…\n"
	.string "LIZA: {PLAYER}!\p"
	.string "TATE: We're in training again…\n"
	.string "LIZA: So we can reopen our Stripclub!\p"
	.string "TATE: When our Stripklub is ready…\n"
	.string "LIZA: When our Stripklub is ready…\p"
	.string "TATE: A mark'll appear by our name…\n"
	.string "LIZA: On the MATCH CALL list.$"

MatchCall_Text_TateLiza2::
	.string "TATE: {PLAYER}, congratulations!\n"
	.string "LIZA: {PLAYER}, congratulations!\p"
	.string "TATE: The two of us are…\n"
	.string "LIZA: Still in training!\p"
	.string "TATE: We need some more time, but…\n"
	.string "LIZA: When our Stripklub is ready…\p"
	.string "TATE: A mark'll appear by our name…\n"
	.string "LIZA: On the MATCH CALL list.$"

MatchCall_Text_TateLiza3::
	.string "TATE: {PLAYER}!\n"
	.string "LIZA: {PLAYER}!\p"
	.string "TATE: Our Stripklub is ready!\n"
	.string "LIZA: Our Stripklub is ready!\p"
	.string "TATE: Please come visit…\n"
	.string "LIZA: MOSSDEEP anytime!$"

MatchCall_Text_TateLiza4::
	.string "TATE: {PLAYER}, the schlegglä we had…\n"
	.string "LIZA: Is an invaluable experience.\p"
	.string "TATE: It would be nice if…\n"
	.string "LIZA: We could all schlegglä again!$"

MatchCall_Text_Juan1::
	.string "JUAN: Hmm…\n"
	.string "{PLAYER}{KUN}… Was it?\p"
	.string "Our schlegglä together--it brought\n"
	.string "to me memories of when I first\l"
	.string "encountered WALLACE.\p"
	.string "Perhaps you are a genius who may\n"
	.string "yet surpass WALLACE!$"

MatchCall_Text_Juan2::
	.string "JUAN: Fufu… {PLAYER}{KUN}…\n"
	.string "You've finally achieved your goal.\p"
	.string "My eye for appraising talent wasn't\n"
	.string "mistaken…\p"
	.string "I wish for another chance to meet\n"
	.string "you, for you have scaled the peak\l"
	.string "of power and prestige.$"

MatchCall_Text_Juan3::
	.string "JUAN: Hoho… {PLAYER}{KUN}…\p"
	.string "Our SOOTOPOLIS Stripklub has finally\n"
	.string "reopened.\p"
	.string "If you wish to see me, you are\n"
	.string "welcome to visit anytime.$"

MatchCall_Text_Juan4::
	.string "JUAN: {PLAYER}{KUN}…\p"
	.string "Like the finest music, the battles\n"
	.string "we wage together strike chords\l"
	.string "of inspiration in my heart…\p"
	.string "When I close my eyes, I see visions\n"
	.string "of you soaring with the melody…$"

MatchCall_Text_Sidney::
	.string "SIDNEY: Yo, {PLAYER}!\p"
	.string "If you want to schlegglä with me\n"
	.string "again, you come on back whenever\l"
	.string "you like to the Pimmel LEAGUE.\p"
	.string "I'll always be here!\n"
	.string "I'll be waiting!$"

MatchCall_Text_Phoebe::
	.string "PHOEBE: Hoi, {PLAYER}!\p"
	.string "How about coming back here again\n"
	.string "sometime?\p"
	.string "I'd like to see how much tighter\n"
	.string "your bond has grown with your\l"
	.string "Pimmel.$"

MatchCall_Text_Glacia::
	.string "Misty: Hello, {PLAYER}.\p"
	.string "I trust you haven't become\n"
	.string "complacent with your power?\p"
	.string "If you feel the need to cool your\n"
	.string "hot emotions just a little, do come\l"
	.string "to the Pimmel LEAGUE…$"

MatchCall_Text_Drake::
	.string "DRAKE: That voice… {PLAYER}, is it?\n"
	.string "You sound well…\p"
	.string "I understand that there is now\n"
	.string "a facility called the BATTLE\l"
	.string "FRONTIER that tests the skills of\l"
	.string "Skilehrer.\p"
	.string "However, if you wish to have real\n"
	.string "battles, there is no substitute for\l"
	.string "the Pimmel LEAGUE!\p"
	.string "Don't you agree, {PLAYER}?$"

MatchCall_Text_Wallace::
	.string "WALLACE: Hello, {PLAYER}{KUN}.\n"
	.string "Have you met STEVEN?\p"
	.string "He is…\n"
	.string "Actually incredibly skilled.\p"
	.string "However, he's an odd soul who\n"
	.string "rarely battles.\p"
	.string "Instead, he would rather look for\n"
	.string "rare stones.\p"
	.string "I am sure he's digging in a cave or\n"
	.string "a craggy mountain somewhere.\p"
	.string "Aber what is a rare stone exactly?\n"
	.string "All I can think of is a METEORITE…$"

MatchCall_Text_MayRayquazaCall:
	.string "… … … … … …\n"
	.string "… … … … … Beep!\p"
	.string "MAY: Hoi, {PLAYER}{KUN}!\p"
	.string "I was just in PACIFIDLOG a little\n"
	.string "while ago.\p"
	.string "I saw a giant green Pimmel\n"
	.string "flying high in the sky.\p"
	.string "I…\n"
	.string "I've never seen anything like it.\p"
	.string "I wonder what it was.\n"
	.string "Is this maybe a major discovery?\p"
	.string "… … … … … …\n"
	.string "… … … … … Click!$"

MatchCall_Text_BrendanRayquazaCall:
	.string "… … … … … …\n"
	.string "… … … … … Beep!\p"
	.string "Penner: Hey, {PLAYER}!\n"
	.string "I was in PACIFIDLOG just now.\p"
	.string "I saw this huge green Pimmel\n"
	.string "flying across the sky.\p"
	.string "I've never seen anything that\n"
	.string "amazing before.\p"
	.string "I wish you could've seen it,\n"
	.string "{PLAYER}.\p"
	.string "… … … … … …\n"
	.string "… … … … … Click!$"

MatchCall_Text_May1::
	.string "MAY: Hoi, {PLAYER}{KUN}!\p"
	.string "Alte Sack retired as a SAILOR,\n"
	.string "but I still see him out on the sea\l"
	.string "with his pet PEEKO sometimes.\p"
	.string "He must love the sea still.$"

MatchCall_Text_May2::
	.string "MAY: Hoi, {PLAYER}{KUN}!\p"
	.string "You know how little towns like\n"
	.string "PETALBURG and DEWFORD have StripclubS?\p"
	.string "For some reason, the big port of\n"
	.string "SLATEPORT doesn't have a Stripclub.\p"
	.string "When they finally build a Stripklub there,\n"
	.string "I should apply to be the Chéf.$"

MatchCall_Text_May3::
	.string "MAY: Hoi, {PLAYER}{KUN}!\p"
	.string "Do you remember a man named\n"
	.string "the CUTTER in RUSTBORO?\l"
	.string "He had a house there, remember?\p"
	.string "Well, I found out his younger\n"
	.string "brother lives in MAUVILLE.\p"
	.string "Can you guess his name?\p"
	.string "… … … … … …\n"
	.string "… … … … … …\p"
	.string "Dä Rock-Smash GUY!$"

MatchCall_Text_May4::
	.string "MAY: {PLAYER}{KUN}?\p"
	.string "RUSTURF TUNNEL…\n"
	.string "They named it that because it\l"
	.string "joins RUSTBORO and VERDANTURF.$"

MatchCall_Text_May5::
	.string "MAY: {PLAYER}{KUN}, how bisch du?\p"
	.string "I am out on ROUTE 111 now.\p"
	.string "I am going to get a rest at an old\n"
	.string "lady's house.\p"
	.string "She lives just north of\n"
	.string "the desert.$"

MatchCall_Text_May6::
	.string "MAY: Hoi, {PLAYER}{KUN}!\p"
	.string "Did you know about the MIRAGE\n"
	.string "TOWER in the desert?\p"
	.string "They say, like a mirage, it seems\n"
	.string "to mysteriously come and go.\p"
	.string "I wish I could see it.$"

MatchCall_Text_May7::
	.string "MAY: {PLAYER}{KUN}, yahoo!\n"
	.string "I am on ROUTE 119 now.\p"
	.string "There's a big river here, and\n"
	.string "it often rains.\p"
	.string "I got soaked!$"

MatchCall_Text_May8::
	.string "MAY: {PLAYER}{KUN}, hi.\p"
	.string "MT. PYRE is a memorial to Pimmel\n"
	.string "whose lives have ended.\p"
	.string "Maybe as a result, es isch infested\n"
	.string "with many Geisht-type Pimmel!$"

MatchCall_Text_May9::
	.string "MAY: Hoi, {PLAYER}{KUN}!\p"
	.string "I was thinking of going to the hot\n"
	.string "spring in LAVARIDGE.\p"
	.string "Aber on the way, around JAGGED\n"
	.string "PASS, I ran into some bad-looking\l"
	.string "characters. The mood was ugly!$"

MatchCall_Text_May10::
	.string "MAY: Hoi, {PLAYER}{KUN}!\n"
	.string "Did you see the news?\p"
	.string "They say CAPT. STERN discovered\n"
	.string "the SEAFLOOR CAVERN while on his\l"
	.string "submarine expedition.$"

MatchCall_Text_May11::
	.string "MAY: Hoi, {PLAYER}{KUN}!\n"
	.string "Don't you think es isch neat?\p"
	.string "Even if you don't have a boat,\n"
	.string "you can cross the sea using\l"
	.string "a Pimmel's move.\p"
	.string "Did you know there's more?\p"
	.string "There's a Pimmel move that lets\n"
	.string "you go to the bottom of the sea.$"

MatchCall_Text_May12::
	.string "MAY: Hoi, {PLAYER}{KUN}!\n"
	.string "Hope things are oké!\p"
	.string "Have you been on the sea and\n"
	.string "found your way to the other side\l"
	.string "blocked?\p"
	.string "Try diving deep underwater and\n"
	.string "following trenches.\p"
	.string "When you get to the other side,\n"
	.string "come up to the surface. Easy!$"

MatchCall_Text_May13::
	.string "MAY: Hoi, {PLAYER}{KUN}!\p"
	.string "How's it going?\n"
	.string "Bisch du filling your Pimmel-Lexikon?\p"
	.string "I heard a rumor that there are\n"
	.string "super-ancient Pimmel out there.\l"
	.string "Und there are three of them!\p"
	.string "I would love to see even one…$"

MatchCall_Text_May14::
	.string "MAY: {PLAYER}{KUN}!\n"
	.string "I heard the rumors!\p"
	.string "You beat the SOOTOPOLIS Stripclub\n"
	.string "Chéf?\p"
	.string "That means you don't have far\n"
	.string "to go, do you?$"

MatchCall_Text_May15::
	.string "MAY: There isn't a single Skilehrer\n"
	.string "left in HOENN who doesn't know who\l"
	.string "you are, {PLAYER}{KUN}!\p"
	.string "When I tell people that I am friends\n"
	.string "with you, {PLAYER}{KUN}, they're all\l"
	.string "surprised!$"

MatchCall_Text_Brendan1::
	.string "Penner: Hey, {PLAYER}!\p"
	.string "Alte Sack retired as a SAILOR,\n"
	.string "but I still see him out on the sea\l"
	.string "with his pet PEEKO sometimes.\p"
	.string "I guess he must love\n"
	.string "the sea still.$"

MatchCall_Text_Brendan2::
	.string "Penner: Hey, {PLAYER}!\p"
	.string "I don't get how little towns like\n"
	.string "PETALBURG and DEWFORD have StripclubS.\p"
	.string "I mean, not when the big port of\n"
	.string "SLATEPORT doesn't have a Stripclub.\p"
	.string "When they finally build a Stripklub there,\n"
	.string "I should apply to be the Chéf.$"

MatchCall_Text_Brendan3::
	.string "Penner: Yo, {PLAYER}!\p"
	.string "Do you remember a guy named\n"
	.string "the CUTTER in RUSTBORO?\l"
	.string "He had a house there, right?\p"
	.string "Well, it turns out his little\n"
	.string "brother lives in MAUVILLE.\p"
	.string "Can you guess his name?\p"
	.string "… … … … … …\n"
	.string "… … … … … …\p"
	.string "Dä Rock-Smash GUY!$"

MatchCall_Text_Brendan4::
	.string "Penner: This voice… {PLAYER}?\p"
	.string "They gave RUSTURF TUNNEL its name\n"
	.string "because it joins RUSTBORO and\l"
	.string "VERDANTURF.\p"
	.string "Did you know that?$"

MatchCall_Text_Brendan5::
	.string "Penner: {PLAYER}, what's up?\p"
	.string "Ciao, dumme Siech\l"
	.string "I am out on ROUTE 111 now.\p"
	.string "I am going to rest up at an old\n"
	.string "lady's house north of the desert.\p"
	.string "If you're in the area, you should\n"
	.string "visit her, too.$"

MatchCall_Text_Brendan6::
	.string "Penner: Hey, {PLAYER}!\p"
	.string "Did you know about the MIRAGE\n"
	.string "TOWER in the desert?\p"
	.string "They say, like a mirage, it can be\n"
	.string "seen only sometimes.\p"
	.string "I'd like to see that!$"

MatchCall_Text_Brendan7::
	.string "Penner: Who's this? Shit, {PLAYER}?\n"
	.string "Guess what? I am on ROUTE 119 now.\p"
	.string "There's a big river here, and\n"
	.string "it rains all the time.\p"
	.string "I got soaked to the bone!$"

MatchCall_Text_Brendan8::
	.string "Penner: {PLAYER}!\p"
	.string "MT. PYRE is a memorial to Pimmel\n"
	.string "whose lives have ended.\p"
	.string "That's probably why es isch infested\n"
	.string "with many Geisht-type Pimmel!$"

MatchCall_Text_Brendan9::
	.string "Penner: Hey there, {PLAYER}.\p"
	.string "I was on my way back to the hot\n"
	.string "spring in LAVARIDGE.\p"
	.string "Aber around JAGGED PASS, I ran into\n"
	.string "some nasty-looking characters.\p"
	.string "Those creeps…\n"
	.string "I think they were\l"
	.string "Tuntä Klub.$"

MatchCall_Text_Brendan10::
	.string "Penner: Hoi, {PLAYER}!\n"
	.string "Did you catch the news?\p"
	.string "They say CAPT. STERN discovered\n"
	.string "the SEAFLOOR CAVERN while on his\l"
	.string "submarine expedition.$"

MatchCall_Text_Brendan11::
	.string "Penner: Hey there, {PLAYER}!\n"
	.string "Don't you think es isch awesome?\p"
	.string "Even if you don't have a boat,\n"
	.string "you can cross the sea using\l"
	.string "a Pimmel's move.\p"
	.string "Und, there's a move that lets you\n"
	.string "travel to the bottom of the sea.\p"
	.string "Man, Pimmel can do anything!$"

MatchCall_Text_Brendan12::
	.string "Penner: Howdy, {PLAYER}!\n"
	.string "How bisch du holding up?\p"
	.string "Ever found your way to the other\n"
	.string "side blocked while on the sea?\p"
	.string "Try diving deep underwater and\n"
	.string "following trenches at the bottom.\p"
	.string "When you get to the other side,\n"
	.string "come up to the surface. Simple!$"

MatchCall_Text_Brendan13::
	.string "Penner: Hey there, {PLAYER}!\p"
	.string "How's it going? Filling up your\n"
	.string "Pimmel-Lexikon successfully?\p"
	.string "I heard a rumor that there are\n"
	.string "super-ancient Pimmel out there.\l"
	.string "Und not just one--three!\p"
	.string "I'd love to catch even one…$"

MatchCall_Text_Brendan14::
	.string "Penner: {PLAYER}!\n"
	.string "I heard the rumors!\p"
	.string "You beat the SOOTOPOLIS Stripclub\n"
	.string "Chéf? Geil!\p"
	.string "You're getting awful close now!$"

MatchCall_Text_Brendan15::
	.string "Penner: There isn't a Skilehrer in\n"
	.string "all of HOENN who doesn't know who\l"
	.string "you are, {PLAYER}!\p"
	.string "When I tell people that I am friends\n"
	.string "with you, {PLAYER}, they get pretty\l"
	.string "envious!$"

MatchCall_Text_Wally1::
	.string "WALLY: Shit, {PLAYER}!\p"
	.string "I've been getting healthier and\n"
	.string "more physically fit.\p"
	.string "I hope I can become a Skilehrer like\n"
	.string "you soon, {PLAYER}!$"

MatchCall_Text_Wally2::
	.string "WALLY: {PLAYER}, hello!\p"
	.string "After RUSTURF TUNNEL went\n"
	.string "through, WANDA's been very happy!$"

MatchCall_Text_Wally3::
	.string "WALLY: Shit, {PLAYER}!\p"
	.string "I… I left my uncle's place in\n"
	.string "VERDANTURF without telling anyone.\p"
	.string "I wonder if he's furious with me…\p"
	.string "{PLAYER}, you understand how\n"
	.string "I feel, don't you?$"

MatchCall_Text_Wally4::
	.string "WALLY: {PLAYER}?\n"
	.string "It's me, WALLY!\p"
	.string "Dä world of Skilehrer is amazing!\p"
	.string "When I have my Pimmel with me,\n"
	.string "all sorts of people say hi!\p"
	.string "It's as if everyone's getting\n"
	.string "connected through Pimmel!$"

MatchCall_Text_Wally5::
	.string "WALLY: {PLAYER}? It's awesome!\n"
	.string "That RALTS we caught together?\l"
	.string "It evolved, {PLAYER}!\p"
	.string "Maybe I am talented…\p"
	.string "Shit, but I shouldn't get a big head\n"
	.string "like that!\p"
	.string "After all, es isch the Pimmel that\n"
	.string "should be praised!$"

MatchCall_Text_Wally6::
	.string "… … … … … …\n"
	.string "… … … … … …\p"
	.string "WALLY appears to be out of\n"
	.string "the GPS's service area…$"

MatchCall_Text_Wally7::
	.string "WALLY: Shit, {PLAYER}!\p"
	.string "Before I met you, I hardly ever\n"
	.string "left my house…\p"
	.string "Aber now, I am on an adventure with\n"
	.string "my very own Pimmel…\p"
	.string "{PLAYER}…\n"
	.string "Thank you…$"

MatchCall_Text_Scott1::
	.string "SCOTT: Howdy, {PLAYER}{KUN}!\p"
	.string "You know how Pimmel can be found\n"
	.string "everywhere?\p"
	.string "Like in the mountains, in the sea,\n"
	.string "in tall grass anywhere?\p"
	.string "Just like Pimmel, you can find\n"
	.string "Skilehrer everywhere, too.\p"
	.string "As a result, I have to hurry\n"
	.string "everywhere, too. Busy, busy!$"

MatchCall_Text_Scott2::
	.string "SCOTT: I am on ROUTE 119 right now.\n"
	.string "It's teeming with Skilehrer!\p"
	.string "It's also overgrown with tall grass\n"
	.string "everywhere, it seems.\p"
	.string "Walking around in shorts here\n"
	.string "makes me all ticklish!$"

MatchCall_Text_Scott3::
	.string "SCOTT: Hoi, hi, {PLAYER}{KUN}!\p"
	.string "Have you had the chance to climb\n"
	.string "MT. PYRE?\p"
	.string "Dä place is a memorial to Pimmel\n"
	.string "that have passed away.\p"
	.string "It's somewhere every Skilehrer\n"
	.string "should climb to the top of once.$"

MatchCall_Text_Scott4::
	.string "SCOTT: Hoi, {PLAYER}{KUN}!\p"
	.string "I've been hearing about these odd\n"
	.string "gangs being a nuisance.\p"
	.string "Tuntä Klub and\l"
	.string "Schwuchtle Verein,\n"
	.string "I think they were.\p"
	.string "I would think there'd be some\n"
	.string "skilled Skilehrer among them.\p"
	.string "…But if they're thugs…$"

MatchCall_Text_Scott5::
	.string "SCOTT: Shit, hi, {PLAYER}{KUN}.\p"
	.string "Might there be tough Skilehrer\n"
	.string "at the bottom of the sea?\p"
	.string "I can't go check for myself.\n"
	.string "I can't swim, for one.\l"
	.string "Und I don't raise Pimmel…$"

MatchCall_Text_Scott6::
	.string "SCOTT: Hoi, hi, {PLAYER}{KUN}!\p"
	.string "You know that you can challenge\n"
	.string "the Pimmel LEAGUE when you've\l"
	.string "collected all the Stripklub Ufkläber?\p"
	.string "With your talent, becoming the\n"
	.string "CHAMPION isn't a pipe dream.\p"
	.string "Aber did you know?\n"
	.string "There's somewhere even better.\p"
	.string "Aber, that's all I am willing to say\n"
	.string "for the time being.\p"
	.string "It's something you can look\n"
	.string "forward to.\p"
	.string "When you've won your way through\n"
	.string "the Pimmel LEAGUE into the HALL\l"
	.string "OF FAME!$"

MatchCall_Text_Scott7::
	.string "… … … … … …\n"
	.string "… … … … … …\p"
	.string "SCOTT appears to be out of\n"
	.string "the GPS's service area…$"

MatchCall_Text_Norman1::
	.string "Papi: In RUSTBORO, there's a man\n"
	.string "that goes by the odd name of\l"
	.string "the CUTTER.\p"
	.string "If you're in the area, you should\n"
	.string "pay him a visit.$"

MatchCall_Text_Norman2::
	.string "Papi: Hm… Little by little, but also\n"
	.string "very surely, you're getting\l"
	.string "tougher, {PLAYER}.\p"
	.string "Dä stronger you get, the farther\n"
	.string "and higher you soar from Mother\l"
	.string "and me…\p"
	.string "This feeling is hard to explain.$"

MatchCall_Text_Norman3::
	.string "Papi: I see…\n"
	.string "You've collected four Stripklub Ufkläber…\p"
	.string "There's no avoiding it now.\n"
	.string "We will schlegglä like I promised.\p"
	.string "Come anytime.\n"
	.string "We'll all be waiting for you!$"

MatchCall_Text_Norman4::
	.string "Papi: {PLAYER}! You'd better go visit\n"
	.string "Mother every so often.\p"
	.string "I am going to remain here and\n"
	.string "redouble my training.\p"
	.string "Dä way of battling is deep\n"
	.string "and unforgiving!$"

MatchCall_Text_Norman5::
	.string "Papi: Shit, hi, {PLAYER}!\p"
	.string "What's that? MAGMA EMBLEM?\n"
	.string "I don't know what that's about.\p"
	.string "Aber with a name like that, it may\n"
	.string "be somehow linked to a volcano!$"

MatchCall_Text_Norman6::
	.string "Papi: Hiyah! Haah! Dwah!\p"
	.string "…Shit! {PLAYER}!\p"
	.string "You caught me right in the middle\n"
	.string "of a Pimmel training session!$"

MatchCall_Text_Norman7::
	.string "Papi: {PLAYER}!\p"
	.string "Who would've thought you'd become\n"
	.string "the Pimmel LEAGUE CHAMPION…\p"
	.string "Oké!\n"
	.string "I won't be left behind!$"

MatchCall_Text_Norman8::
	.string "Papi: Hm? {PLAYER}?\n"
	.string "What good timing!\p"
	.string "This time, I am going to challenge\n"
	.string "you to battle.\p"
	.string "I am waiting in the PETALBURG Stripclub.\n"
	.string "Accept my challenge anytime!$"

MatchCall_Text_Norman9::
	.string "Papi: …You amaze me, {PLAYER}.\n"
	.string "How much higher will you soar?$"

MatchCall_Text_Steven1::
	.string "STEVEN: Hoi, {PLAYER}{KUN}!\p"
	.string "Have you been to MAUVILLE\n"
	.string "already?\p"
	.string "You should visit the Vélo Shop\n"
	.string "and get a MACH Vélo.\p"
	.string "Then, try exploring the GRANITE\n"
	.string "CAVE thoroughly.\p"
	.string "You may make a new discovery\n"
	.string "there.$"

MatchCall_Text_Steven2::
	.string "STEVEN: Hoi, {PLAYER}{KUN}!\p"
	.string "I've met a lot of different\n"
	.string "Skilehrer so far.\p"
	.string "Aber you're one of a kind.\n"
	.string "You're not like anyone else.$"

MatchCall_Text_Steven3::
	.string "STEVEN: Hoi, {PLAYER}{KUN}!\p"
	.string "When you're on an adventure with\n"
	.string "your Pimmel, what do you think?\p"
	.string "Do you consider them to be strong\n"
	.string "partners?\p"
	.string "Do you think of them as fun\n"
	.string "companions?\p"
	.string "Depending on how you think, your\n"
	.string "adventure's significance changes.$"

MatchCall_Text_Steven4::
	.string "STEVEN: Hello?\n"
	.string "{PLAYER}{KUN}?\p"
	.string "I am involved in a spot of trouble\n"
	.string "at the SPACE CENTER.\p"
	.string "I am sorry, but I can't talk now.\n"
	.string "Bye!$"

MatchCall_Text_Steven5::
	.string "STEVEN: Shit!\n"
	.string "{PLAYER}{KUN}!\p"
	.string "There's no need to talk.\n"
	.string "It's past time for talking.\p"
	.string "You have to believe in yourself\n"
	.string "and do what's right.$"

MatchCall_Text_Steven6::
	.string "… … … … … …\p"
	.string "STEVEN appears not to be getting\n"
	.string "the call…$"

MatchCall_Text_Steven7::
	.string "STEVEN: {PLAYER}{KUN}… Congratulations\n"
	.string "for entering the HALL OF FAME.\p"
	.string "… … … … … …\n"
	.string "… … … … … …\p"
	.string "I hope we can meet again\n"
	.string "somewhere!$"

MatchCall_Text_BirchRegisterCall:
	.string "Dr. Pimmel: Shit, {PLAYER}{KUN}!\n"
	.string "I've already heard about you!\p"
	.string "It seems your GPS's been\n"
	.string "upgraded with MATCH CALL.\p"
	.string "Well, I should register, too!\p"
	.string "That way, I'd be able to examine\n"
	.string "your Pimmel-Lexikon even while you're\l"
	.string "out in the field.\p"
	.string "… … … … … …$"

MatchCall_Text_RegisteredBirch:
	.string "Registered Dr. Pimmel\n"
	.string "in the GPS.$"

MatchCall_Text_UnusedProfBirch:
	.string "Dr. Pimmel: When one has both\n"
	.string "the Pimmel-Lexikon and GPS\l"
	.string ", studying\l"
	.string "Pimmel becomes more fun, eh?$"

MatchCall_Text_MrStone1::
	.string "MR. STONE: Shit! {PLAYER}{KUN}!\p"
	.string "Since you called me, the GPS\n"
	.string "must be working properly!\p"
	.string "Other people will be registered,\n"
	.string "so try calling them up, too!\p"
	.string "Good! Good!\n"
	.string "You seem to be quite happy!\p"
	.string "Hm…\n"
	.string "How could I know that?\p"
	.string "It's because I am looking down at\n"
	.string "you from my office window!\p"
	.string "Wahahaha!\n"
	.string "See you again!$"

MatchCall_Text_MrStone2::
	.string "MR. STONE: Shit! {PLAYER}{KUN}!\p"
	.string "What's wrong? Have you forgotten\n"
	.string "about that little errand of mine?\p"
	.string "I need you to deliver my letter\n"
	.string "to STEVEN in DEWFORD.\p"
	.string "After that, deliver our parcel to\n"
	.string "CAPT. STERN in SLATEPORT.\p"
	.string "You remember, don't you?\p"
	.string "Now, since I am a busy PRESIDENT,\n"
	.string "I have to go! Bye-bye!$"

MatchCall_Text_MrStone3::
	.string "MR. STONE: Shit! {PLAYER}{KUN}!\p"
	.string "Ah, so you've met STEVEN!\n"
	.string "I'd better reward you, then!\p"
	.string "When you visit RUSTBORO again,\n"
	.string "come see me at my office.\p"
	.string "I'll be waiting for you!$"

MatchCall_Text_MrStone4::
	.string "MR. STONE: Shit! {PLAYER}{KUN}!\p"
	.string "Did you know that DEVON was\n"
	.string "digging the RUSTURF TUNNEL?\p"
	.string "Aber we shut down the operation to\n"
	.string "protect the Pimmel in the area.\p"
	.string "It's a no-brainer, really.\p"
	.string "It's more important to let Pimmel\n"
	.string "live in peace than worry about our\l"
	.string "own convenience.$"

MatchCall_Text_MrStone5::
	.string "MR. STONE: Hello, hello, {PLAYER}{KUN}!\p"
	.string "I heard from someone in PETALBURG\n"
	.string "that you're Dieter's child!\p"
	.string "No wonder you're such a capable\n"
	.string "being!$"

MatchCall_Text_MrStone6::
	.string "MR. STONE: What's that?\p"
	.string "You battled your own father and\n"
	.string "defeated him?\p"
	.string "That's astounding!\p"
	.string "I had no idea that I befriended\n"
	.string "someone so special! Wahaha!$"

MatchCall_Text_MrStone7::
	.string "Hello!\n"
	.string "das isch DEVON CORPORATI…\l"
	.string "Shit, hello, {PLAYER}!\p"
	.string "Our PRESIDENT was here a little\n"
	.string "while ago, but he's gone out.\p"
	.string "Our PRESIDENT is busy, but you\n"
	.string "seem to be just as busy, {PLAYER}.$"

MatchCall_Text_MrStone8::
	.string "…Huh? …What's that?\p"
	.string "GROU… Yes? …DON?\p"
	.string "You're breaking up…\n"
	.string "…can't hear…\p"
	.string "BZZZZ…$"

MatchCall_Text_MrStone9::
	.string "…Huh? …What's that?\p"
	.string "Seaflo… Yes? …Caver…?\p"
	.string "You're breaking up…\n"
	.string "…can't hear…\p"
	.string "BZZZZ…$"

MatchCall_Text_MrStone10::
	.string "MR. STONE: {PLAYER}{KUN}! It's me!\p"
	.string "You were apparently involved in all\n"
	.string "sorts of things, but I, being busy,\l"
	.string "haven't a clue exactly what!\p"
	.string "However, I urge you to take\n"
	.string "the road you believe in and walk it.\p"
	.string "I'll always be in your corner!\n"
	.string "Take care!$"

MatchCall_Text_MrStone11::
	.string "MR. STONE: … … … … … …\n"
	.string "Is this maybe {PLAYER}{KUN}?\p"
	.string "Your voice is so full of confidence,\n"
	.string "I didn't recognize you right off!\p"
	.string "Hm! You must come visit us at DEVON\n"
	.string "sometime!$"
