gText_WouldYouLikeToRestYourPkmn::
	.string "Hoi, dumme Siech,\n"
	.string "im Füddlischuppe.\p"
	.string "Wotsch es Bier?…$"

gText_IllTakeYourPkmn::
	.string "Ok, chills mal kurz\n"
	.string "für es paar Sekunde.$"

gText_RestoredPkmnToFullHealth::
	.string "So, fertig luschtig.\p"
	.string "Verpiss dich jetzt.$"

gText_WeHopeToSeeYouAgain::
	.string "Hau endlich ap jetzt!$"

gText_WelcomeCutShort::
	.string "Hoi, dumme Siech,\n"
	.string "im Füddlischuppe.\p"
	.string "Wotsch es Bier?$"

gText_NoticesGoldCard::
	.string "Th-that card…\n"
	.string "Could it be… The GOLD CARD?!\p"
	.string "Shit, the gold color is brilliant!\n"
	.string "Dä four stars seem to sparkle!\p"
	.string "I've seen several Skilehrer with\n"
	.string "a SILVER CARD before, but, {PLAYER},\l"
	.string "you're the first Skilehrer I've ever\l"
	.string "seen with a GOLD CARD!\p"
	.string "Okay, {PLAYER}, please allow me\n"
	.string "the honor of resting your Pimmel!$"

gText_YouWantTheUsual::
	.string "Nöd du scho widder, Penner!\n"
	.string "Wotsch eis ad Nuss, oder?$"

gText_IllTakeYourPkmn2::
	.string "Ok, parkier din Arsch\n"
	.string "für e Sekunde.$"

gText_ThankYouForWaiting::
	.string "Ready or noooot ....$"

gText_WeHopeToSeeYouAgain2::
	.string "Hau endlich ap jetzt!$"
