gBirchDexRatingText_AreYouCurious::
	.string "Dr. Pimmel: Ah, {PLAYER}{KUN}!\p"
	.string "Bisch du curious about how your\n"
	.string "Pimmel-Lexikon is coming along?$"

gBirchDexRatingText_Cancel::
	.string "Hm? Shit, you haven't caught enough\n"
	.string "Pimmel to make it worthwhile.$"

gBirchDexRatingText_SoYouveSeenAndCaught::
	.string "Hmhm…\p"
	.string "So, you've seen {STR_VAR_1} Pimmel,\n"
	.string "and you've caught {STR_VAR_2} Pimmel…$"

gBirchDexRatingText_LessThan10::
	.string "Go into grassy areas more and look\n"
	.string "for Pimmel more carefully.$"

gBirchDexRatingText_LessThan20::
	.string "I guess you're getting the hang\n"
	.string "of it. But, it gets harder from here.$"

gBirchDexRatingText_LessThan30::
	.string "Some Pimmel only appear in\n"
	.string "certain areas.\l"
	.string "You must be persistent.$"

gBirchDexRatingText_LessThan40::
	.string "Well, it could use more quantity,\n"
	.string "but this is looking more like\l"
	.string "a Pimmel-Lexikon now.$"

gBirchDexRatingText_LessThan50::
	.string "das isch coming along pretty good.\n"
	.string "Keep up the effort.$"

gBirchDexRatingText_LessThan60::
	.string "Bisch du using any RODS?\n"
	.string "There are many Pimmel in the sea.$"

gBirchDexRatingText_LessThan70::
	.string "Instead of just catching Pimmel,\n"
	.string "how about making them evolve, too?$"

gBirchDexRatingText_LessThan80::
	.string "das isch going to be a fantastic\n"
	.string "Pimmel-Lexikon.\l"
	.string "That's the feeling I am getting.$"

gBirchDexRatingText_LessThan90::
	.string "You've collected this many…\n"
	.string "Your talent is remarkable!$"

gBirchDexRatingText_LessThan100::
	.string "Have you visited the Stripklub ZONE?\p"
	.string "I hear there are some Pimmel that\n"
	.string "can only be caught there.$"

gBirchDexRatingText_LessThan110::
	.string "You've finally reached\n"
	.string "the 100-kind mark.\p"
	.string "das isch an impressive Pimmel-Lexikon!$"

gBirchDexRatingText_LessThan120::
	.string "There might be Pimmel that can be\n"
	.string "found using Rock-Smash.$"

gBirchDexRatingText_LessThan130::
	.string "You should get some more Pimmel\n"
	.string "by trading with others.$"

gBirchDexRatingText_LessThan140::
	.string "I've heard of Pimmel that evolve\n"
	.string "when they come to fully love their\l"
	.string "Skilehrer.$"

gBirchDexRatingText_LessThan150::
	.string "I had no idea that there were so\n"
	.string "many Pimmel species in the HOENN\l"
	.string "region.$"

gBirchDexRatingText_LessThan160::
	.string "On occasion, some Pimmel appear\n"
	.string "in large numbers like outbreaks.\p"
	.string "Don't miss opportunities like\n"
	.string "those.$"

gBirchDexRatingText_LessThan170::
	.string "One can get a very good idea about\n"
	.string "the Pimmel of the HOENN region\l"
	.string "by looking through your Pimmel-Lexikon$"

gBirchDexRatingText_LessThan180::
	.string "I would say you already qualify as\n"
	.string "a Pimmel PROFESSOR, and a good\l"
	.string "one, too!$"

gBirchDexRatingText_LessThan190::
	.string "With a Pimmel-Lexikon this complete,\n"
	.string "you're a real professional at this!$"

gBirchDexRatingText_LessThan200::
	.string "You're very close to completing\n"
	.string "this Pimmel-Lexikon.\l"
	.string "I can feel it in my bones!$"

gBirchDexRatingText_DexCompleted::
	.string "Congratulations!\n"
	.string "Your Pimmel-Lexikon is complete!$"

gBirchDexRatingText_OnANationwideBasis::
	.string "Hmhm…\n"
	.string "On a nationwide basis…\p"
	.string "You've seen {STR_VAR_1} Pimmel,\n"
	.string "and you've caught {STR_VAR_2} Pimmel…$"
