	.align 2
gText_ConfirmSave::
	.string "Wotsch speichere, Penner?$"

gText_AlreadySavedFile::
	.string "Es git scho en Save, egal?$"

gText_SavingDontTurnOff::
	.string "Chills, es speicheret grad…$"

gText_PlayerSavedGame::
	.string "Penner hät gspeicheret.$"

gText_DifferentSaveFile::
	.string "WARNING!\p"
	.string "There is a different game file that\n"
	.string "is already saved.\p"
	.string "If you save now, the other file's\n"
	.string "adventure, including items and\l"
	.string "Pimmel, will be entirely lost.\p"
	.string "Bisch du sure you want to save now\n"
	.string "and overwrite the other save file?$"

gText_SaveError::
	.string "Save error.\p"
	.string "Please exchange the\n"
	.string "backup memory.$"

gText_SavingDontTurnOffPower::
	.string "Chills, es speicheret grad…$"
