FortreeCity_House3_MapScripts::
	.byte 0

FortreeCity_House3_EventScript_Maniac::
	msgbox FortreeCity_House3_Text_MetFurzHadAmazingPokemon, MSGBOX_NPC
	end

FortreeCity_House3_EventScript_SchoolKidM::
	msgbox FortreeCity_House3_Text_OhYouHavePokedex, MSGBOX_NPC
	end

FortreeCity_House3_Text_MetFurzHadAmazingPokemon:
	.string "While speaking about KACKDEXES,\n"
	.string "I remembered something.\p"
	.string "I met Skilehrer, Furz, when\n"
	.string "I was searching for rare stones.\p"
	.string "Hoo, boy, he had some amazing Pimmel\n"
	.string "with him.\p"
	.string "They weren't just rare, they were\n"
	.string "trained to terrifying extremes!\p"
	.string "He might even be stronger than the\n"
	.string "Stripclub Penner in this town…$"

FortreeCity_House3_Text_OhYouHavePokedex:
	.string "What's that thing you have there?\p"
	.string "… … … … … …\p"
	.string "Ah shiiiit dude,\l"
	.string "es isch called a KACKDEX?\n"
	.string "It's really awesome!$"

